{-# LANGUAGE RankNTypes #-}

{- | Join one exact admitted project plan to its protected, verified stable
snapshot.

The fresh leaf performs the ordered persist, readback, local descriptive
binding, and lease transition.  The older verification-only functions remain
available for already-persisted callers.
-}
module HostBootstrap.ProjectPlan.Snapshot
    ( PlanDigestBinding
    , BoundPlanSnapshot
    , boundPlanSnapshotBytes
    , SnapshotError (..)
    , withPlanDigestBinding
    , withFreshBoundPlanSnapshot
    , withPersistedPlanSnapshot
    , withBoundPlanSnapshot
    )
where

import Data.ByteString (ByteString)
import HostBootstrap.Authority
    ( InstalledProjectIdentity
    , RootInvocationAuthority
    , VerbUp
    )
import HostBootstrap.Lifecycle.Mode
    ( BoundInvocationRecovery
    , BoundRunLease
    , InvocationCloseKey
    , LeaseConflict
    , ModeError
    , NormalActiveRecovery
    , ProductionMode
    , ProjectModeLease
    , UnboundRunLease
    , VerifiedPlanSnapshot
    , bindRunLeaseWithPlanRecovery
    , persistAndVerifyIndexedPlanSnapshotKernel
    , planSnapshotPlanDigest
    , validateFreshPlanSnapshotEvidence
    , verifyIndexedPlanSnapshot
    , withBoundPlanSnapshotKernel
    )
import HostBootstrap.Lifecycle.Plan
    ( BoundPlanSnapshot
    , PlanDigestBinding
    , boundPlanSnapshotBytesKernel
    , existingBoundSnapshotAdmissionKernel
    , mintBoundPlanSnapshotKernel
    , mintPlanDigestBindingKernel
    , projectPlanIndexedSnapshotKernel
    )
import HostBootstrap.ProjectScope (Production)
import HostBootstrap.Protected (ProtectedStore)
import HostBootstrap.ProjectPlan (ProjectPlan)

-- | The protected fresh-snapshot protocol refused before yielding authority.
data SnapshotError
    = SnapshotVerificationError ModeError
    | SnapshotLeaseConflict LeaseConflict
    deriving (Eq, Show)

{- | Read and verify the already-persisted snapshot for one exact project plan,
then jointly yield the refined verified snapshot and its non-authorizing local
digest binding.

The plan's private indexed snapshot fixes @scope@, @specDigest@, and @planId@.
Only @planDigest@ is generated by reading the protected snapshot, and the
binding is minted only after exact specification, configuration, byte, and
digest agreement.
-}
withPlanDigestBinding ::
    UnboundRunLease scope brokerGeneration ->
    ProjectPlan scope specDigest planId configId cfg ->
    ( forall planDigest.
      VerifiedPlanSnapshot scope specDigest planDigest ->
      PlanDigestBinding scope specDigest planDigest planId ->
      IO result
    ) ->
    IO (Either SnapshotError result)
withPlanDigestBinding unbound plan use = do
    verified <-
        verifyIndexedPlanSnapshot unbound indexed $ \snapshot ->
            Right
                <$> use
                    snapshot
                    ( mintPlanDigestBindingKernel
                        indexed
                        (planSnapshotPlanDigest snapshot)
                    )
    pure $ case verified of
        Left failure -> Left (SnapshotVerificationError failure)
        Right result -> Right result
  where
    indexed = projectPlanIndexedSnapshotKernel plan

-- | The exact canonical bytes retained by a locally bound snapshot.
--
-- This projection is descriptive only.  It exposes no constructor, plan
-- identity, lease transition, or operation authority.
boundPlanSnapshotBytes ::
    BoundPlanSnapshot scope specDigest planDigest planId ->
    ByteString
boundPlanSnapshotBytes = boundPlanSnapshotBytesKernel

{- | Interpret one freshly admitted local plan under its exact protected
snapshot.

This is the fresh-plan counterpart to the existing-snapshot admission below.
It performs no persistence or lease binding: it delegates all
protected comparison to 'withPlanDigestBinding', then adds the locally bound
snapshot beside that verifier's exact verified snapshot and digest binding.
The one continuation quantifier therefore fixes the stable digest across all
three values.
-}
withFreshBoundPlanSnapshot ::
    UnboundRunLease scope brokerGeneration ->
    ProjectPlan scope specDigest planId configId cfg ->
    ( forall planDigest.
      VerifiedPlanSnapshot scope specDigest planDigest ->
      BoundPlanSnapshot scope specDigest planDigest planId ->
      PlanDigestBinding scope specDigest planDigest planId ->
      IO result
    ) ->
    IO (Either SnapshotError result)
withFreshBoundPlanSnapshot unbound plan use =
    withPlanDigestBinding unbound plan $ \verified binding ->
        use
            verified
            (mintBoundPlanSnapshotKernel indexed binding)
            binding
  where
    indexed = projectPlanIndexedSnapshotKernel plan

{- | Persist, flush, read back, and exactly verify one freshly admitted plan,
then bind the matching unbound run lease.

All root, lease, profile, project, store, and epoch evidence is checked before
the protected snapshot entry.  The immutable snapshot is persisted and read
back in that one entry; only after it succeeds does a separate fresh-only lease
CAS run.  Consequently a crash between those stages leaves the exact
snapshot-persisted/unbound state, and retrying this function is idempotent.

The continuation is the only place the protected @planDigest@ exists.  Its
five arguments therefore share the exact specification, plan digest, local
plan identity, broker generation, and scope established by this protocol.
-}
withPersistedPlanSnapshot ::
    RootInvocationAuthority scope brokerGeneration VerbUp ->
    UnboundRunLease scope brokerGeneration ->
    ProjectPlan scope specDigest planId configId cfg ->
    ( forall planDigest.
      VerifiedPlanSnapshot scope specDigest planDigest ->
      BoundPlanSnapshot scope specDigest planDigest planId ->
      PlanDigestBinding scope specDigest planDigest planId ->
      BoundRunLease scope specDigest planDigest brokerGeneration ->
      NormalActiveRecovery scope specDigest planDigest planId brokerGeneration ->
      IO result
    ) ->
    IO (Either SnapshotError result)
withPersistedPlanSnapshot root unbound plan use =
    case
        validateFreshPlanSnapshotEvidence root unbound plan
    of
        Left failure -> pure (Left (SnapshotVerificationError failure))
        Right () -> do
            persisted <-
                persistAndVerifyIndexedPlanSnapshotKernel unbound indexed $ \verified -> do
                    let binding =
                            mintPlanDigestBindingKernel
                                indexed
                                (planSnapshotPlanDigest verified)
                        boundSnapshot = mintBoundPlanSnapshotKernel indexed binding
                    bound <-
                        bindRunLeaseWithPlanRecovery
                            unbound
                            indexed
                            verified
                            binding
                            (use verified boundSnapshot binding)
                    pure $ case bound of
                        Left failure -> Left (SnapshotLeaseConflict failure)
                        Right result -> Right result
            pure $ case persisted of
                Left failure -> Left (SnapshotVerificationError failure)
                Right result -> result
  where
    indexed = projectPlanIndexedSnapshotKernel plan

{- | Read-only admission of the existing Production invocation retained in a
protected store.

A terminal acknowledgment yields only its exact close key.  Only an Open
invocation generates a local @planId@ and jointly yields the exact ProjectUp
root, Production mode, existing bound lease, verified canonical snapshot,
local snapshot binding, and fully indexed Open-recovery observation.
-}
withBoundPlanSnapshot ::
    ProtectedStore ->
    InstalledProjectIdentity projectId ->
    (InvocationCloseKey -> IO result) ->
    ( forall brokerGeneration specDigest planDigest planId.
      RootInvocationAuthority (Production projectId) brokerGeneration VerbUp ->
      ProjectModeLease projectId ProductionMode brokerGeneration ->
      BoundRunLease (Production projectId) specDigest planDigest brokerGeneration ->
      VerifiedPlanSnapshot (Production projectId) specDigest planDigest ->
      BoundPlanSnapshot (Production projectId) specDigest planDigest planId ->
      PlanDigestBinding (Production projectId) specDigest planDigest planId ->
      BoundInvocationRecovery
        (Production projectId)
        specDigest
        planDigest
        planId
        brokerGeneration ->
      IO result
    ) ->
    IO (Either SnapshotError result)
withBoundPlanSnapshot store project terminal useOpen = do
    admitted <-
        withBoundPlanSnapshotKernel
            existingBoundSnapshotAdmissionKernel
            store
            project
            terminal
            useOpen
    pure (either (Left . SnapshotVerificationError) Right admitted)
