{-# LANGUAGE GADTs #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RankNTypes #-}

{- | Join one exact admitted project plan to its protected, verified stable
snapshot.

The fresh leaf performs the ordered persist, readback, local descriptive
binding, and lease transition.  The older verification-only functions remain
available for already-persisted callers.
-}
module HostBootstrap.ProjectPlan.Snapshot (
    PlanDigestBinding,
    BoundPlanSnapshot,
    boundPlanSnapshotBytes,
    SnapshotError (..),
    withPlanDigestBinding,
    withFreshBoundPlanSnapshot,
    withPersistedPlanSnapshot,
    withRestartedBoundPlanSnapshot,
    withBoundPlanSnapshot,
    withReauthorizedBoundPlanSnapshotKernel,
)
where

import Data.ByteString (ByteString)
import qualified Data.Text as Text
import HostBootstrap.Authority (
    InstalledProjectIdentity,
    ProjectVerb (ProjectDestroy, ProjectDown, ProjectUp),
    RootInvocationAuthority,
    TeardownPhase,
    VerbUp,
    brokerEpochWord,
    installedProjectName,
    rootAuthorityEpoch,
    rootAuthorityProjectName,
 )
import HostBootstrap.Authority.Kernel (rootAuthorityStoreIdentity)
import HostBootstrap.Lifecycle.Context (ValidatedLifecycleContext)
import HostBootstrap.Lifecycle.Mode (
    AcquisitionJournal,
    BoundInvocationRecovery,
    BoundRunLease,
    InvocationCloseKey,
    LeaseConflict,
    LifecycleCursor,
    ModeError (..),
    NormalActiveRecovery,
    ProductionMode,
    ProjectModeLease,
    RecoveredProductionLifecycleProfile,
    UnboundRunLease,
    VerifiedPlanSnapshot,
    bindRunLeaseWithPlanRecovery,
    boundRunLeasePlanDigest,
    boundRunLeaseSpecDigest,
    persistAndVerifyIndexedPlanSnapshotKernel,
    planSnapshotCanonicalBytes,
    planSnapshotConfigDigest,
    planSnapshotPlanDigest,
    planSnapshotProjectName,
    planSnapshotSpecDigest,
    planSnapshotStoreIdentity,
    validateFreshPlanSnapshotEvidence,
    verifyIndexedPlanSnapshot,
    withBoundPlanSnapshotKernel,
    withFreshExistingBoundReverseRootKernel,
    withResumedExistingBoundReverseRootKernel,
 )
import HostBootstrap.Lifecycle.Plan (
    BoundPlanSnapshot,
    ExistingBoundSnapshotAdmission,
    PlanDigestBinding,
    boundPlanSnapshotBytesKernel,
    canonicalPlanSnapshotBytes,
    canonicalPlanSnapshotConfigDigest,
    canonicalPlanSnapshotDigest,
    canonicalPlanSnapshotSpecDigest,
    consumeExistingBoundSnapshotAdmissionKernel,
    existingBoundSnapshotAdmissionKernel,
    indexedPlanSnapshotCanonicalKernel,
    mintBoundPlanSnapshotKernel,
    mintPlanDigestBindingKernel,
    projectPlanIndexedSnapshotKernel,
    projectPlanProfileEpochKernel,
    projectPlanProfileProjectNameKernel,
    projectPlanProfileStoreIdentityKernel,
 )
import HostBootstrap.ProjectPlan (ProjectPlan)
import HostBootstrap.ProjectScope (Production)
import HostBootstrap.Protected (
    ProtectedError,
    ProtectedStore,
    withRunLiveness,
 )

-- | The protected fresh-snapshot protocol refused before yielding authority.
data SnapshotError
    = SnapshotVerificationError ModeError
    | SnapshotLeaseConflict LeaseConflict
    | SnapshotLivenessFailure ProtectedError
    | SnapshotLivenessContended
    | SnapshotReverseRootTerminal
    deriving (Eq, Show)

{- | Read and verify the already-persisted snapshot for one exact project plan,
then jointly yield the refined verified snapshot and its non-authorizing local
digest binding.

The plan's private indexed snapshot fixes @scope@, @specDigest@, and @planId@.
Only @planDigest@ is generated by reading the protected snapshot, and the
binding is minted only after exact specification, configuration, byte, and
digest agreement.
-}
withPlanDigestBinding ::
    UnboundRunLease scope brokerGeneration ->
    ProjectPlan scope specDigest planId configId cfg ->
    ( forall planDigest.
      VerifiedPlanSnapshot scope specDigest planDigest ->
      PlanDigestBinding scope specDigest planDigest planId ->
      IO result
    ) ->
    IO (Either SnapshotError result)
withPlanDigestBinding unbound plan use = do
    verified <-
        verifyIndexedPlanSnapshot unbound indexed $ \snapshot ->
            Right
                <$> use
                    snapshot
                    ( mintPlanDigestBindingKernel
                        indexed
                        (planSnapshotPlanDigest snapshot)
                    )
    pure $ case verified of
        Left failure -> Left (SnapshotVerificationError failure)
        Right result -> Right result
  where
    indexed = projectPlanIndexedSnapshotKernel plan

{- | The exact canonical bytes retained by a locally bound snapshot.

This projection is descriptive only.  It exposes no constructor, plan
identity, lease transition, or operation authority.
-}
boundPlanSnapshotBytes ::
    BoundPlanSnapshot scope specDigest planDigest planId ->
    ByteString
boundPlanSnapshotBytes = boundPlanSnapshotBytesKernel

{- | Interpret one freshly admitted local plan under its exact protected
snapshot.

This is the fresh-plan counterpart to the existing-snapshot admission below.
It performs no persistence or lease binding: it delegates all
protected comparison to 'withPlanDigestBinding', then adds the locally bound
snapshot beside that verifier's exact verified snapshot and digest binding.
The one continuation quantifier therefore fixes the stable digest across all
three values.
-}
withFreshBoundPlanSnapshot ::
    UnboundRunLease scope brokerGeneration ->
    ProjectPlan scope specDigest planId configId cfg ->
    ( forall planDigest.
      VerifiedPlanSnapshot scope specDigest planDigest ->
      BoundPlanSnapshot scope specDigest planDigest planId ->
      PlanDigestBinding scope specDigest planDigest planId ->
      IO result
    ) ->
    IO (Either SnapshotError result)
withFreshBoundPlanSnapshot unbound plan use =
    withPlanDigestBinding unbound plan $ \verified binding ->
        use
            verified
            (mintBoundPlanSnapshotKernel indexed binding)
            binding
  where
    indexed = projectPlanIndexedSnapshotKernel plan

{- | Persist, flush, read back, and exactly verify one freshly admitted plan,
then bind the matching unbound run lease.

All root, lease, profile, project, store, and epoch evidence is checked before
the protected snapshot entry.  The immutable snapshot is persisted and read
back in that one entry; only after it succeeds does a separate fresh-only lease
CAS run.  Consequently a crash between those stages leaves the exact
snapshot-persisted/unbound state, and retrying this function is idempotent.

The continuation is the only place the protected @planDigest@ exists.  Its
five arguments therefore share the exact specification, plan digest, local
plan identity, broker generation, and scope established by this protocol.
-}
withPersistedPlanSnapshot ::
    RootInvocationAuthority scope brokerGeneration VerbUp ->
    UnboundRunLease scope brokerGeneration ->
    ProjectPlan scope specDigest planId configId cfg ->
    ( forall planDigest.
      VerifiedPlanSnapshot scope specDigest planDigest ->
      BoundPlanSnapshot scope specDigest planDigest planId ->
      PlanDigestBinding scope specDigest planDigest planId ->
      BoundRunLease scope specDigest planDigest brokerGeneration ->
      NormalActiveRecovery scope specDigest planDigest planId brokerGeneration ->
      IO result
    ) ->
    IO (Either SnapshotError result)
withPersistedPlanSnapshot root unbound plan use =
    case validateFreshPlanSnapshotEvidence root unbound plan of
        Left failure -> pure (Left (SnapshotVerificationError failure))
        Right () -> do
            persisted <-
                persistAndVerifyIndexedPlanSnapshotKernel unbound indexed $ \verified -> do
                    let binding =
                            mintPlanDigestBindingKernel
                                indexed
                                (planSnapshotPlanDigest verified)
                        boundSnapshot = mintBoundPlanSnapshotKernel indexed binding
                    bound <-
                        bindRunLeaseWithPlanRecovery
                            unbound
                            indexed
                            verified
                            binding
                            (use verified boundSnapshot binding)
                    pure $ case bound of
                        Left failure -> Left (SnapshotLeaseConflict failure)
                        Right result -> Right result
            pure $ case persisted of
                Left failure -> Left (SnapshotVerificationError failure)
                Right result -> result
  where
    indexed = projectPlanIndexedSnapshotKernel plan

{- | Bind a freshly re-admitted local plan identity to the immutable snapshot
and already-rotated bound lease of a same-run Harness invocation.

No snapshot or lease mutation occurs here. The restart transition has already
advanced the broker generation; this leaf compares every stable plan byte and
all root/profile origins before minting the new local plan binding.
-}
withRestartedBoundPlanSnapshot ::
    RootInvocationAuthority scope brokerGeneration verb ->
    BoundRunLease scope specDigest planDigest brokerGeneration ->
    VerifiedPlanSnapshot scope specDigest planDigest ->
    ProjectPlan scope specDigest planId configId cfg ->
    ( BoundPlanSnapshot scope specDigest planDigest planId ->
      PlanDigestBinding scope specDigest planDigest planId ->
      IO result
    ) ->
    IO (Either SnapshotError result)
withRestartedBoundPlanSnapshot root bound verified plan use =
    case validate of
        Left failure -> pure (Left (SnapshotVerificationError failure))
        Right () -> Right <$> use boundSnapshot binding
  where
    indexed = projectPlanIndexedSnapshotKernel plan
    canonical = indexedPlanSnapshotCanonicalKernel indexed
    binding = mintPlanDigestBindingKernel indexed (planSnapshotPlanDigest verified)
    boundSnapshot = mintBoundPlanSnapshotKernel indexed binding
    validate = do
        match "root project" (rootAuthorityProjectName root) (projectPlanProfileProjectNameKernel plan)
        match "root store" (rootAuthorityStoreIdentity root) (projectPlanProfileStoreIdentityKernel plan)
        matchWord "root epoch" (brokerEpochWord (rootAuthorityEpoch root)) (projectPlanProfileEpochKernel plan)
        match "snapshot project" (planSnapshotProjectName verified) (rootAuthorityProjectName root)
        match "snapshot store" (planSnapshotStoreIdentity verified) (rootAuthorityStoreIdentity root)
        match "snapshot specification" (planSnapshotSpecDigest verified) (canonicalPlanSnapshotSpecDigest canonical)
        match "snapshot plan" (planSnapshotPlanDigest verified) (canonicalPlanSnapshotDigest canonical)
        if planSnapshotConfigDigest verified == Just (canonicalPlanSnapshotConfigDigest canonical)
            then Right ()
            else Left (ModeEvidenceMismatch "configuration digest" "exact persisted digest" "different digest")
        if planSnapshotCanonicalBytes verified == Just (canonicalPlanSnapshotBytes canonical)
            then Right ()
            else Left (ModeEvidenceMismatch "canonical bytes" "exact persisted bytes" "different bytes")
        match "bound specification" (planSnapshotSpecDigest verified) (boundRunLeaseSpecDigest bound)
        match "bound plan" (planSnapshotPlanDigest verified) (boundRunLeasePlanDigest bound)
    match subject expected observed
        | expected == observed = Right ()
        | otherwise = Left (ModeEvidenceMismatch subject expected observed)
    matchWord subject expected observed =
        match subject (Text.pack (show expected)) (Text.pack (show observed))

{- | Read-only admission of the existing Production invocation retained in a
protected store.

A terminal acknowledgment yields only its exact close key.  Only an Open
invocation generates a local @planId@ and jointly yields the exact ProjectUp
root, Production mode, existing bound lease, verified canonical snapshot,
local snapshot binding, and fully indexed Open-recovery observation.
-}
withBoundPlanSnapshot ::
    ProtectedStore ->
    InstalledProjectIdentity projectId ->
    (InvocationCloseKey -> IO result) ->
    ( forall brokerGeneration specDigest planDigest planId.
      RootInvocationAuthority (Production projectId) brokerGeneration VerbUp ->
      ProjectModeLease projectId ProductionMode brokerGeneration ->
      BoundRunLease (Production projectId) specDigest planDigest brokerGeneration ->
      VerifiedPlanSnapshot (Production projectId) specDigest planDigest ->
      BoundPlanSnapshot (Production projectId) specDigest planDigest planId ->
      PlanDigestBinding (Production projectId) specDigest planDigest planId ->
      BoundInvocationRecovery
        (Production projectId)
        specDigest
        planDigest
        planId
        brokerGeneration ->
      IO result
    ) ->
    IO (Either SnapshotError result)
withBoundPlanSnapshot store project terminal useOpen = do
    admitted <-
        withBoundPlanSnapshotKernel
            existingBoundSnapshotAdmissionKernel
            store
            project
            terminal
            useOpen
    pure (either (Left . SnapshotVerificationError) Right admitted)

{- | Reauthorize one existing-bound Production root for Down or Destroy while
holding the sole same-name run-liveness extent.

The hidden admission is forced before the verb or any effect.  Absence alone
may reconstruct the exact source package; an existing reverse-root intent
instead resumes entirely from its recorded coordinates.  The target callback
runs before liveness is released and remains the only place its fresh indices
exist.
-}
withReauthorizedBoundPlanSnapshotKernel ::
    ExistingBoundSnapshotAdmission ->
    ProtectedStore ->
    InstalledProjectIdentity projectId ->
    ProjectVerb verb ->
    ( forall sourceBrokerGeneration sourceSpecDigest sourcePlanDigest sourcePlanId sourceResult.
      RootInvocationAuthority (Production projectId) sourceBrokerGeneration VerbUp ->
      ProjectModeLease projectId ProductionMode sourceBrokerGeneration ->
      BoundRunLease
        (Production projectId)
        sourceSpecDigest
        sourcePlanDigest
        sourceBrokerGeneration ->
      VerifiedPlanSnapshot
        (Production projectId)
        sourceSpecDigest
        sourcePlanDigest ->
      BoundPlanSnapshot
        (Production projectId)
        sourceSpecDigest
        sourcePlanDigest
        sourcePlanId ->
      PlanDigestBinding
        (Production projectId)
        sourceSpecDigest
        sourcePlanDigest
        sourcePlanId ->
      BoundInvocationRecovery
        (Production projectId)
        sourceSpecDigest
        sourcePlanDigest
        sourcePlanId
        sourceBrokerGeneration ->
      ( forall sourceConfigId cfg frame.
        ProjectPlan
            (Production projectId)
            sourceSpecDigest
            sourcePlanId
            sourceConfigId
            cfg ->
        ValidatedLifecycleContext
            (Production projectId)
            sourceSpecDigest
            sourcePlanId
            sourceConfigId
            frame ->
        AcquisitionJournal
            (Production projectId)
            sourcePlanId
            sourceBrokerGeneration ->
        LifecycleCursor
            (Production projectId)
            sourcePlanId
            frame
            sourceBrokerGeneration
            VerbUp
            TeardownPhase ->
        IO (Either SnapshotError sourceResult)
      ) ->
      IO (Either SnapshotError sourceResult)
    ) ->
    ( forall targetBrokerGeneration targetSpecDigest targetPlanDigest targetPlanId.
      ProjectVerb verb ->
      RootInvocationAuthority (Production projectId) targetBrokerGeneration verb ->
      ProjectModeLease projectId ProductionMode targetBrokerGeneration ->
      BoundRunLease
        (Production projectId)
        targetSpecDigest
        targetPlanDigest
        targetBrokerGeneration ->
      VerifiedPlanSnapshot (Production projectId) targetSpecDigest targetPlanDigest ->
      BoundPlanSnapshot
        (Production projectId)
        targetSpecDigest
        targetPlanDigest
        targetPlanId ->
      PlanDigestBinding
        (Production projectId)
        targetSpecDigest
        targetPlanDigest
        targetPlanId ->
      RecoveredProductionLifecycleProfile
        projectId
        targetSpecDigest
        targetPlanDigest
        targetPlanId
        targetBrokerGeneration ->
      IO result
    ) ->
    IO (Either SnapshotError result)
{-# OPAQUE withReauthorizedBoundPlanSnapshotKernel #-}
withReauthorizedBoundPlanSnapshotKernel admission =
    case consumeExistingBoundSnapshotAdmissionKernel admission of
        () -> \store project verb initialSource use ->
            let fromMode = either (Left . SnapshotVerificationError) Right
                select = do
                    selected <-
                        withBoundPlanSnapshotKernel
                            admission
                            store
                            project
                            (\_closeKey -> pure (Left SnapshotReverseRootTerminal))
                            ( \root modeLease boundLease verified boundSnapshot binding recovery ->
                                initialSource
                                    root
                                    modeLease
                                    boundLease
                                    verified
                                    boundSnapshot
                                    binding
                                    recovery
                                    ( \plan lifecycleContext journal cursor -> do
                                        transitioned <-
                                            withFreshExistingBoundReverseRootKernel
                                                admission
                                                store
                                                project
                                                verb
                                                root
                                                modeLease
                                                boundLease
                                                verified
                                                boundSnapshot
                                                binding
                                                recovery
                                                plan
                                                lifecycleContext
                                                journal
                                                cursor
                                                use
                                        pure (fromMode transitioned)
                                    )
                            )
                    case selected of
                        Left ModeReverseRootInProgress -> do
                            resumed <-
                                withResumedExistingBoundReverseRootKernel
                                    admission
                                    store
                                    project
                                    verb
                                    use
                            pure (fromMode resumed)
                        Left failure -> pure (Left (SnapshotVerificationError failure))
                        Right outcome -> pure outcome

                underLiveness = do
                    held <- withRunLiveness store (installedProjectName project) select
                    pure $ case held of
                        Left failure -> Left (SnapshotLivenessFailure failure)
                        Right Nothing -> Left SnapshotLivenessContended
                        Right (Just outcome) -> outcome
             in case verb of
                    ProjectUp ->
                        pure
                            ( Left
                                ( SnapshotVerificationError
                                    (ModeWrongRecoveryScope "reverse root" "up")
                                )
                            )
                    ProjectDown -> underLiveness
                    ProjectDestroy -> underLiveness
