"""The thin pre-binary bootstrapper.

The Python layer does only what must run *before any project binary exists*
(see ``DEVELOPMENT_PLAN/development_plan_standards.md`` §§ M, N):

1. derive the project name from the project's single Cabal file;
2. assert the fail-fast host minimums;
3. ensure the host Haskell build toolchain and package index (Homebrew -> ``ghcup``
   -> GHC/Cabal on Apple silicon; ``ghcup`` -> GHC/Cabal on Linux; a
   PowerShell-downloaded GHCup -> GHC/Cabal on Windows) -- the prerequisites to
   *build* the binary;
4. build the project binary **host-native** at ``./.build/<executable>`` on every
   substrate;
5. ``exec`` the binary, handing control to ``hostbootstrap-core``'s command tree
   extended by the project.

Python does not read, write, *or* initialize Dhall -- the binary owns its config.
A normal command fails fast (exit 1) when no sibling ``<project>.dhall`` exists;
the config is created by an explicit ``project init`` or generated by the test
harness. Ensuring Docker, building the project container, writing/decoding config,
and applying the budget cordon are the project binary's job once it is running.
"""

from __future__ import annotations

import asyncio
import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import NamedTuple

from . import prereqs, process, substrate
from .substrate import Substrate, SubstrateName

_BREW: str = "brew"
_GHCUP: str = "ghcup"
_CABAL: str = "cabal"
_POWERSHELL: str = r"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"

# The family-pinned GHC every project's ``cabal.project`` selects.
GHC_VERSION: str = "9.12.4"

# The host-native build output directory; ./.build/<executable> is always present.
_BUILD_DIR: str = ".build"

# The host-native cabal package store, kept repo-local under ./.build/.
_STORE_DIR: str = f"{_BUILD_DIR}/cabal-store"

_WINDOWS_TOOLCHAIN_PATHS: tuple[Path, ...] = (
    Path("C:/ghcup/bin"),
    Path("C:/cabal/bin"),
)
_WINDOWS_GHCUP: str = r"C:\ghcup\bin\ghcup.exe"
_WINDOWS_CABAL: str = r"C:\ghcup\bin\cabal.exe"
_GHCUP_WINDOWS_BOOTSTRAP: str = (
    "New-Item -ItemType Directory -Force C:/ghcup/bin | Out-Null; "
    "$ghcup = 'C:/ghcup/bin/ghcup.exe'; "
    "if ((Test-Path $ghcup) -and ((Get-Item $ghcup).Length -gt 0)) { exit 0 }; "
    "Invoke-WebRequest "
    "https://downloads.haskell.org/ghcup/0.2.6.2/x86_64-mingw64-ghcup-0.2.6.2.exe "
    "-OutFile $ghcup"
)
# The POSIX ghcup bootstrap (Linux): install ghcup itself, non-interactively and
# without pulling GHC/Cabal (the ghcup_steps below install the pinned toolchain).
_GHCUP_POSIX_BOOTSTRAP: str = (
    "curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org "
    "| BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_MINIMAL=1 sh"
)


class ProjectDiscoveryError(RuntimeError):
    """Raised when the project name cannot be derived from Cabal files."""


@dataclass(frozen=True)
class ProjectBuildSpec:
    """The only project facts Python needs before the binary exists."""

    project: str
    executable: str
    cabal_file: Path


def discover_project(project_root: Path) -> ProjectBuildSpec:
    """Derive the project and executable names from the single Cabal file."""
    cabal_files = sorted(path for path in project_root.glob("*.cabal") if path.is_file())
    if not cabal_files:
        raise ProjectDiscoveryError(f"no .cabal file found in {project_root}")
    if len(cabal_files) > 1:
        names = ", ".join(path.name for path in cabal_files)
        raise ProjectDiscoveryError(f"multiple .cabal files found in {project_root}: {names}")
    cabal_file = cabal_files[0]
    return ProjectBuildSpec(
        project=cabal_file.stem,
        executable=_discover_executable(cabal_file),
        cabal_file=cabal_file,
    )


def _discover_executable(cabal_file: Path) -> str:
    """Return the single executable stanza name from *cabal_file*."""
    executables: list[str] = []
    for raw_line in cabal_file.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("--"):
            continue
        parts = line.split()
        if len(parts) == 2 and parts[0] == "executable":
            executables.append(parts[1])
    if not executables:
        raise ProjectDiscoveryError(f"no executable stanza found in {cabal_file}")
    if len(executables) > 1:
        names = ", ".join(executables)
        raise ProjectDiscoveryError(f"multiple executable stanzas found in {cabal_file}: {names}")
    return executables[0]


# ---------------------------------------------------------------------------
# Pure command-builders
# ---------------------------------------------------------------------------


class ToolchainStep(NamedTuple):
    """A single toolchain-ensure step: a quiet *probe* and its *install* fallback."""

    probe: tuple[str, ...]
    install: tuple[str, ...]


def toolchain_ensure_steps(sub: Substrate) -> tuple[ToolchainStep, ...]:
    """The host build-toolchain ensure steps (development_plan_standards.md § N), run before the build."""
    ghcup = _WINDOWS_GHCUP if sub.is_windows else _GHCUP
    ghcup_steps = (
        ToolchainStep(
            probe=(ghcup, "whereis", "ghc", GHC_VERSION),
            install=(ghcup, "install", "ghc", GHC_VERSION, "--set"),
        ),
        ToolchainStep(
            probe=(ghcup, "whereis", "cabal"),
            install=(ghcup, "install", "cabal", "--set"),
        ),
    )
    if sub.name is SubstrateName.APPLE_SILICON:
        return (
            ToolchainStep(
                probe=(_GHCUP, "--version"),
                install=(_BREW, "install", "ghcup"),
            ),
            *ghcup_steps,
        )
    if sub.is_windows:
        return (
            ToolchainStep(
                probe=(_WINDOWS_GHCUP, "--version"),
                install=(
                    _POWERSHELL,
                    "-NoProfile",
                    "-ExecutionPolicy",
                    "Bypass",
                    "-Command",
                    _GHCUP_WINDOWS_BOOTSTRAP,
                ),
            ),
            *ghcup_steps,
        )
    # Linux (linux-cpu / linux-gpu): bootstrap ghcup via its POSIX installer first,
    # mirroring the Apple/Windows shape so a pristine host is not assumed to ship it.
    return (
        ToolchainStep(
            probe=(_GHCUP, "--version"),
            install=("sh", "-c", _GHCUP_POSIX_BOOTSTRAP),
        ),
        *ghcup_steps,
    )


def native_build_command(spec: ProjectBuildSpec, project_root: Path) -> tuple[str, ...]:
    """Build the project binary host-native, in place."""
    cabal = _WINDOWS_CABAL if os.name == "nt" else _CABAL
    return (
        cabal,
        "--store-dir",
        str(project_root / _STORE_DIR),
        "build",
        f"exe:{spec.executable}",
    )


def cabal_update_command() -> tuple[str, ...]:
    """Refresh Cabal's package index before the first host-native build."""
    cabal = _WINDOWS_CABAL if os.name == "nt" else _CABAL
    return (cabal, "update")


def native_listbin_command(spec: ProjectBuildSpec, project_root: Path) -> tuple[str, ...]:
    """Print the built exe's path under ``dist-newstyle/``."""
    cabal = _WINDOWS_CABAL if os.name == "nt" else _CABAL
    return (
        cabal,
        "--store-dir",
        str(project_root / _STORE_DIR),
        "list-bin",
        f"exe:{spec.executable}",
    )


def binary_path(spec: ProjectBuildSpec, project_root: Path) -> Path:
    """The single stable ``./.build/<executable>`` location every consumer execs."""
    suffix = ".exe" if os.name == "nt" else ""
    return project_root / _BUILD_DIR / f"{spec.executable}{suffix}"


def exec_argv(spec: ProjectBuildSpec, project_root: Path, args: tuple[str, ...]) -> tuple[str, ...]:
    """The argv handed to ``os.execv``: the built binary plus trailing args."""
    return (str(binary_path(spec, project_root)), *args)


def _toolchain_env() -> dict[str, str]:
    """Environment that sees tools installed during this bootstrap invocation.

    ghcup installs its shims outside the default PATH mid-bootstrap: under
    ``C:/ghcup/bin`` on Windows and ``~/.ghcup/bin`` (with the cabal/local bins
    alongside) on Apple/Linux, so prepend them here for every substrate.
    """
    env = dict(os.environ)
    if os.name == "nt":
        toolchain_paths: tuple[Path, ...] = _WINDOWS_TOOLCHAIN_PATHS
    else:
        home = Path.home()
        toolchain_paths = (
            home / ".ghcup" / "bin",
            home / ".cabal" / "bin",
            home / ".local" / "bin",
        )
    existing = env.get("PATH", "")
    prefix = os.pathsep.join(str(path) for path in toolchain_paths)
    env["PATH"] = f"{prefix}{os.pathsep}{existing}" if existing else prefix
    return env


# ---------------------------------------------------------------------------
# Async driver
# ---------------------------------------------------------------------------


async def _assert_minimums(sub: Substrate) -> None:
    await prereqs.run_doctor(sub)


async def _already_present(probe: tuple[str, ...]) -> bool:
    """Whether *probe* reports its tool present."""
    for _attempt in range(6):
        try:
            result = await process.run(probe, quiet=True, env=_toolchain_env())
        except FileNotFoundError:
            return False
        except OSError as exc:
            if os.name == "nt" and getattr(exc, "winerror", None) == 32:
                await asyncio.sleep(5)
                continue
            raise
        return result.ok
    return False


async def _ensure_toolchain(sub: Substrate) -> None:
    """Ensure the host build toolchain."""
    for step in toolchain_ensure_steps(sub):
        if await _already_present(step.probe):
            continue
        await process.run_checked(step.install, env=_toolchain_env())


async def _build_native(spec: ProjectBuildSpec, *, project_root: Path) -> None:
    """Build the binary host-native and copy it to ``./.build/<executable>``."""
    binary_path(spec, project_root).parent.mkdir(parents=True, exist_ok=True)
    await process.run_checked(cabal_update_command(), cwd=project_root, env=_toolchain_env())
    await process.run_checked(
        native_build_command(spec, project_root), cwd=project_root, env=_toolchain_env()
    )
    located = await process.run_checked(
        native_listbin_command(spec, project_root),
        cwd=project_root,
        quiet=True,
        env=_toolchain_env(),
    )
    shutil.copy2(Path(located.stdout.strip()), binary_path(spec, project_root))


async def build_binary(spec: ProjectBuildSpec, *, project_root: Path) -> Path:
    """Run the pre-binary bootstrap (development_plan_standards.md §§ M, N) and build the binary host-native."""
    sub = substrate.detect()
    await _assert_minimums(sub)
    await _ensure_toolchain(sub)
    await _build_native(spec, project_root=project_root)
    return binary_path(spec, project_root)


async def bootstrap(
    spec: ProjectBuildSpec,
    *,
    project_root: Path,
    args: tuple[str, ...] = (),
) -> None:
    """Build the project binary host-native, then ``exec`` it with ``args``."""
    await build_binary(spec, project_root=project_root)
    argv = exec_argv(spec, project_root, args)
    _exec_project_binary(argv)


def _exec_project_binary(argv: tuple[str, ...]) -> None:
    if os.name == "nt":
        completed = subprocess.run(list(argv), check=False)
        raise SystemExit(completed.returncode)
    os.execv(argv[0], list(argv))  # pragma: no cover
