"""The thin pre-binary bootstrapper.

The Python layer does only what must run *before any project binary exists*
(see ``DEVELOPMENT_PLAN/development_plan_standards.md`` §§ M, N):

1. derive the project name from the project's single Cabal file;
2. assert the fail-fast host minimums;
3. ensure the host Haskell build toolchain and package index (Homebrew -> ``ghcup``
   -> GHC/Cabal on Apple silicon; ``ghcup`` -> GHC/Cabal on Linux; a
   PowerShell-downloaded GHCup -> GHC/Cabal on Windows) -- the prerequisites to
   *build* the binary;
4. build the project binary **host-native** at ``./.build/<executable>`` on every
   substrate;
5. ``exec`` the binary, handing control to ``hostbootstrap-core``'s command tree
   extended by the project.

Python does not read, write, *or* initialize Dhall -- the binary owns its config.
A normal command fails fast (exit 1) when no sibling ``<project>.dhall`` exists;
the config is created by an explicit ``project init`` or generated by the test
harness. Ensuring Docker, building the project container, writing/decoding config,
and applying the budget cordon are the project binary's job once it is running.
"""

from __future__ import annotations

import asyncio
import hashlib
import os
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import NamedTuple

from . import prereqs, process, substrate
from .substrate import Substrate, SubstrateName

_BREW: str = "brew"
_GHCUP: str = "ghcup"
_CABAL: str = "cabal"
_POWERSHELL: str = r"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"

# The family-pinned GHC every project's ``cabal.project`` selects.
GHC_VERSION: str = "9.12.4"

# The host-native build output directory; ./.build/<executable> is always present.
_BUILD_DIR: str = ".build"

# The host-native cabal package store, kept repo-local under ./.build/.
_STORE_DIR: str = f"{_BUILD_DIR}/cabal-store"

# A week-old package index is stale enough to refresh on an online build while
# keeping ordinary warm invocations independent of the network.
_CABAL_INDEX_MAX_AGE_SECONDS: int = 7 * 24 * 60 * 60

_WINDOWS_TOOLCHAIN_PATHS: tuple[Path, ...] = (
    Path("C:/ghcup/bin"),
    Path("C:/cabal/bin"),
)
_WINDOWS_GHCUP: str = r"C:\ghcup\bin\ghcup.exe"
_WINDOWS_CABAL: str = r"C:\ghcup\bin\cabal.exe"
_GHCUP_VERSION: str = "0.2.6.2"
_GHCUP_DOWNLOADS: dict[tuple[str, str], tuple[str, str]] = {
    ("linux", "amd64"): (
        f"https://downloads.haskell.org/ghcup/{_GHCUP_VERSION}/x86_64-linux-ghcup-{_GHCUP_VERSION}",
        "9ed5da5449b48043a0d17e767c05d2ef585e25a639bb934329496c6d2fad9cf8",
    ),
    ("linux", "arm64"): (
        f"https://downloads.haskell.org/ghcup/{_GHCUP_VERSION}/aarch64-linux-ghcup-{_GHCUP_VERSION}",
        "65a5f05120288ee4f1a81d28825374b6af317456a351a586adfce90c6dc29e3b",
    ),
    ("windows", "amd64"): (
        f"https://downloads.haskell.org/ghcup/{_GHCUP_VERSION}/x86_64-mingw64-ghcup-{_GHCUP_VERSION}.exe",
        "94da902a2853b1de1df509d04da900a05258480759efdb4f654e66956b6f30db",
    ),
}


class ProjectDiscoveryError(RuntimeError):
    """Raised when the project name cannot be derived from Cabal files."""


@dataclass(frozen=True)
class ProjectBuildSpec:
    """One validated project identity plus its selected Cabal file."""

    identity: str
    cabal_file: Path

    @property
    def project(self) -> str:
        return self.identity

    @property
    def executable(self) -> str:
        return self.identity


def discover_project(
    project_root: Path, *, selected_cabal_file: Path | None = None
) -> ProjectBuildSpec:
    """Select one Cabal file and validate its stem/package/executable identity."""
    cabal_files = sorted(path for path in project_root.glob("*.cabal") if path.is_file())
    if selected_cabal_file is not None:
        candidate = (
            selected_cabal_file
            if selected_cabal_file.is_absolute()
            else project_root / selected_cabal_file
        ).resolve()
        root = project_root.resolve()
        if candidate.parent != root or candidate.suffix != ".cabal" or not candidate.is_file():
            raise ProjectDiscoveryError(
                f"selected Cabal file must be an existing .cabal file directly under {root}: "
                f"{selected_cabal_file}"
            )
        cabal_file = candidate
    elif not cabal_files:
        raise ProjectDiscoveryError(f"no .cabal file found in {project_root}")
    elif len(cabal_files) > 1:
        names = ", ".join(path.name for path in cabal_files)
        raise ProjectDiscoveryError(
            f"multiple .cabal files found in {project_root}: {names}; "
            "select one explicitly with --cabal-file"
        )
    else:
        cabal_file = cabal_files[0]

    package = _discover_package_name(cabal_file)
    executable = _discover_executable(cabal_file)
    stem = cabal_file.stem
    if len({stem, package, executable}) != 1:
        raise ProjectDiscoveryError(
            "project identity mismatch before build: "
            f"Cabal file stem={stem!r}, package name={package!r}, "
            f"executable={executable!r}; all three must agree"
        )
    return ProjectBuildSpec(identity=package, cabal_file=cabal_file)


def _discover_package_name(cabal_file: Path) -> str:
    """Return the single top-level package ``name`` field."""
    names: list[str] = []
    for raw_line in cabal_file.read_text(encoding="utf-8").splitlines():
        if raw_line[:1].isspace():
            continue
        line = raw_line.strip()
        if not line or line.startswith("--"):
            continue
        field, separator, value = line.partition(":")
        if separator and field.strip().lower() == "name" and value.strip():
            names.append(value.strip())
    if not names:
        raise ProjectDiscoveryError(f"no package name field found in {cabal_file}")
    if len(names) > 1:
        raise ProjectDiscoveryError(f"multiple package name fields found in {cabal_file}")
    return names[0]


def _discover_executable(cabal_file: Path) -> str:
    """Return the single executable stanza name from *cabal_file*."""
    executables: list[str] = []
    for raw_line in cabal_file.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("--"):
            continue
        parts = line.split()
        if len(parts) == 2 and parts[0] == "executable":
            executables.append(parts[1])
    if not executables:
        raise ProjectDiscoveryError(f"no executable stanza found in {cabal_file}")
    if len(executables) > 1:
        names = ", ".join(executables)
        raise ProjectDiscoveryError(f"multiple executable stanzas found in {cabal_file}: {names}")
    return executables[0]


# ---------------------------------------------------------------------------
# Pure command-builders
# ---------------------------------------------------------------------------


class ToolchainStep(NamedTuple):
    """A single toolchain-ensure step: a quiet *probe* and its *install* fallback."""

    probe: tuple[str, ...]
    install: tuple[str, ...]


def toolchain_ensure_steps(sub: Substrate) -> tuple[ToolchainStep, ...]:
    """The host build-toolchain ensure steps (development_plan_standards.md § N), run before the build."""
    ghcup = _WINDOWS_GHCUP if sub.is_windows else _GHCUP
    ghcup_steps = (
        ToolchainStep(
            probe=(ghcup, "whereis", "ghc", GHC_VERSION),
            install=(ghcup, "install", "ghc", GHC_VERSION, "--set"),
        ),
        ToolchainStep(
            probe=(ghcup, "whereis", "cabal"),
            install=(ghcup, "install", "cabal", "--set"),
        ),
    )
    if sub.name is SubstrateName.APPLE_SILICON:
        return (
            ToolchainStep(
                probe=(_GHCUP, "--version"),
                install=(_BREW, "install", "ghcup"),
            ),
            *ghcup_steps,
        )
    if sub.is_windows:
        return (
            ToolchainStep(
                probe=(_WINDOWS_GHCUP, "--version"),
                install=(),
            ),
            *ghcup_steps,
        )
    # Linux (linux-cpu / linux-gpu): bootstrap ghcup via its POSIX installer first,
    # mirroring the Apple/Windows shape so a pristine host is not assumed to ship it.
    return (
        ToolchainStep(
            probe=(_GHCUP, "--version"),
            install=(),
        ),
        *ghcup_steps,
    )


def native_build_command(
    spec: ProjectBuildSpec, project_root: Path, *, offline: bool = False
) -> tuple[str, ...]:
    """Build the project binary host-native, in place."""
    cabal = _WINDOWS_CABAL if os.name == "nt" else _CABAL
    command: tuple[str, ...] = (
        cabal,
        "--store-dir",
        str(project_root / _STORE_DIR),
        "build",
    )
    if offline:
        command += ("--offline",)
    return (*command, f"exe:{spec.executable}")


def cabal_update_command() -> tuple[str, ...]:
    """Refresh Cabal's package index when its local state requires it."""
    cabal = _WINDOWS_CABAL if os.name == "nt" else _CABAL
    return (cabal, "update")


class CabalIndexState(StrEnum):
    MISSING = "missing"
    FRESH = "fresh"
    STALE = "stale"


def cabal_index_path() -> Path:
    """The standard secure Hackage index used by Cabal."""
    configured = os.environ.get("CABAL_DIR")
    cabal_dir = Path(configured) if configured else Path.home() / ".cabal"
    return cabal_dir / "packages" / "hackage.haskell.org" / "01-index.tar"


def cabal_index_state(index: Path, *, now: float | None = None) -> CabalIndexState:
    if not index.is_file():
        return CabalIndexState.MISSING
    current_time = time.time() if now is None else now
    age = max(0.0, current_time - index.stat().st_mtime)
    if age > _CABAL_INDEX_MAX_AGE_SECONDS:
        return CabalIndexState.STALE
    return CabalIndexState.FRESH


def native_listbin_command(spec: ProjectBuildSpec, project_root: Path) -> tuple[str, ...]:
    """Print the built exe's path under ``dist-newstyle/``."""
    cabal = _WINDOWS_CABAL if os.name == "nt" else _CABAL
    return (
        cabal,
        "--store-dir",
        str(project_root / _STORE_DIR),
        "list-bin",
        f"exe:{spec.executable}",
    )


def binary_path(spec: ProjectBuildSpec, project_root: Path) -> Path:
    """The single stable ``./.build/<executable>`` location every consumer execs."""
    suffix = ".exe" if os.name == "nt" else ""
    return project_root / _BUILD_DIR / f"{spec.executable}{suffix}"


def exec_argv(spec: ProjectBuildSpec, project_root: Path, args: tuple[str, ...]) -> tuple[str, ...]:
    """The argv handed to ``os.execv``: the built binary plus trailing args."""
    return (str(binary_path(spec, project_root)), *args)


def _toolchain_env() -> dict[str, str]:
    """Environment that sees tools installed during this bootstrap invocation.

    ghcup installs its shims outside the default PATH mid-bootstrap: under
    ``C:/ghcup/bin`` on Windows and ``~/.ghcup/bin`` (with the cabal/local bins
    alongside) on Apple/Linux, so prepend them here for every substrate.
    """
    env = dict(os.environ)
    if os.name == "nt":
        toolchain_paths: tuple[Path, ...] = _WINDOWS_TOOLCHAIN_PATHS
    else:
        home = Path.home()
        toolchain_paths = (
            home / ".ghcup" / "bin",
            home / ".cabal" / "bin",
            home / ".local" / "bin",
        )
    existing = env.get("PATH", "")
    prefix = os.pathsep.join(str(path) for path in toolchain_paths)
    env["PATH"] = f"{prefix}{os.pathsep}{existing}" if existing else prefix
    return env


# ---------------------------------------------------------------------------
# Async driver
# ---------------------------------------------------------------------------


async def _assert_minimums(sub: Substrate) -> None:
    # One floor for both `run` and `build`: the wrapper asserts only the
    # pre-binary build minimums (see prereqs._run_linux); runtime host
    # preconditions are the binary's `ensure` responsibility.
    await prereqs.run_doctor(sub)


async def _already_present(probe: tuple[str, ...]) -> bool:
    """Whether *probe* reports its tool present."""
    for _attempt in range(6):
        try:
            result = await process.run(probe, quiet=True, env=_toolchain_env())
        except FileNotFoundError:
            return False
        except OSError as exc:
            if os.name == "nt" and getattr(exc, "winerror", None) == 32:
                await asyncio.sleep(5)
                continue
            raise
        return result.ok
    return False


async def _ensure_toolchain(sub: Substrate, *, offline: bool = False) -> None:
    """Ensure the host build toolchain."""
    for step in toolchain_ensure_steps(sub):
        if await _already_present(step.probe):
            continue
        if offline:
            missing = " ".join(step.probe)
            raise RuntimeError(
                f"offline build requires the host build tool to be preinstalled: {missing}"
            )
        if not step.install:
            await _install_verified_ghcup(sub)
            continue
        await process.run_checked(step.install, env=_toolchain_env())


async def _install_verified_ghcup(sub: Substrate) -> None:
    """Retrieve the pinned GHCup binary, verify its SHA-256, then install it."""
    platform_key = "windows" if sub.is_windows else "linux"
    try:
        url, expected_sha256 = _GHCUP_DOWNLOADS[(platform_key, sub.arch)]
    except KeyError as exc:
        raise RuntimeError(f"no pinned GHCup download for {platform_key}/{sub.arch}") from exc

    destination = Path(_WINDOWS_GHCUP) if sub.is_windows else Path.home() / ".ghcup/bin/ghcup"
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="hostbootstrap-ghcup-") as temp_dir:
        downloaded = Path(temp_dir) / destination.name
        command: tuple[str, ...]
        if sub.is_windows:
            command = (
                _POWERSHELL,
                "-NoProfile",
                "-Command",
                f"Invoke-WebRequest -Uri '{url}' -OutFile '{downloaded}'",
            )
        else:
            curl = shutil.which("curl")
            if curl is None:
                raise RuntimeError("curl disappeared after the prerequisite check")
            command = (curl, "--proto", "=https", "--tlsv1.2", "-fsSL", url, "-o", str(downloaded))
        await process.run_checked(command, env=_toolchain_env())
        actual_sha256 = hashlib.sha256(downloaded.read_bytes()).hexdigest()
        if actual_sha256 != expected_sha256:
            raise RuntimeError(
                f"GHCup download digest mismatch: expected {expected_sha256}, got {actual_sha256}"
            )
        if not sub.is_windows:
            downloaded.chmod(0o755)
        shutil.copy2(downloaded, destination)


def _files_identical(left: Path, right: Path) -> bool:
    if not left.is_file() or not right.is_file():
        return False
    if left.stat().st_size != right.stat().st_size:
        return False
    return hashlib.sha256(left.read_bytes()).digest() == hashlib.sha256(right.read_bytes()).digest()


def _copy_if_changed(source: Path, destination: Path) -> bool:
    """Copy *source* only when the stable artifact bytes changed."""
    if _files_identical(source, destination):
        return False
    shutil.copy2(source, destination)
    return True


async def _build_native(
    spec: ProjectBuildSpec, *, project_root: Path, offline: bool = False
) -> None:
    """Build host-native, refreshing only a stale index and copying only changed bytes."""
    binary_path(spec, project_root).parent.mkdir(parents=True, exist_ok=True)
    index_state = cabal_index_state(cabal_index_path())
    if offline and index_state is CabalIndexState.MISSING:
        raise RuntimeError(
            "offline build requires a cached Cabal package index; "
            "run an online build once before retrying with --offline"
        )
    if not offline and index_state is not CabalIndexState.FRESH:
        await process.run_checked(cabal_update_command(), cwd=project_root, env=_toolchain_env())
    try:
        await process.run_checked(
            native_build_command(spec, project_root, offline=offline),
            cwd=project_root,
            env=_toolchain_env(),
        )
    except process.CommandError as exc:
        if offline:
            raise RuntimeError(
                "offline Cabal build could not resolve all inputs from the cached index/store"
            ) from exc
        raise
    located = await process.run_checked(
        native_listbin_command(spec, project_root),
        cwd=project_root,
        quiet=True,
        env=_toolchain_env(),
    )
    _copy_if_changed(Path(located.stdout.strip()), binary_path(spec, project_root))


async def build_binary(
    spec: ProjectBuildSpec, *, project_root: Path, offline: bool = False
) -> Path:
    """Run the pre-binary bootstrap (development_plan_standards.md §§ M, N) and build the binary host-native."""
    sub = substrate.detect()
    await _assert_minimums(sub)
    await _ensure_toolchain(sub, offline=offline)
    await _build_native(spec, project_root=project_root, offline=offline)
    return binary_path(spec, project_root)


async def bootstrap(
    spec: ProjectBuildSpec,
    *,
    project_root: Path,
    args: tuple[str, ...] = (),
    offline: bool = False,
) -> None:
    """Build the project binary host-native, then ``exec`` it with ``args``."""
    sub = substrate.detect()
    await _assert_minimums(sub)
    await _ensure_toolchain(sub, offline=offline)
    await _build_native(spec, project_root=project_root, offline=offline)
    argv = exec_argv(spec, project_root, args)
    _exec_project_binary(argv, project_root)


def _exec_project_binary(argv: tuple[str, ...], project_root: Path) -> None:
    # Run the binary with cwd = the project home so its cwd is deterministic on
    # every substrate, regardless of where the caller invoked ``hostbootstrap``.
    # ``argv[0]`` is absolute (``binary_path`` of the resolved ``project_root``),
    # so the POSIX ``os.chdir``-before-``os.execv`` cannot break the exec.
    if os.name == "nt":
        completed = subprocess.run(list(argv), cwd=project_root, check=False)
        raise SystemExit(completed.returncode)
    os.chdir(project_root)
    os.execv(argv[0], list(argv))  # pragma: no cover
