"""The thin pre-binary bootstrapper.

The Python layer does only what must run *before any project binary exists*
(see ``documents/architecture/python_haskell_boundary.md`` §§ M, N):

1. derive the project name from the project's single Cabal file;
2. assert the fail-fast host minimums;
3. ensure the host build toolchain (Homebrew -> ``ghcup`` -> GHC/Cabal on Apple
   silicon; ``ghcup`` -> GHC/Cabal on Linux) -- the prerequisites to *build* the
   binary;
4. build the project binary **host-native** at ``./.build/<project>`` on every
   substrate;
5. ``exec`` the binary, handing control to ``hostbootstrap-core``'s command tree
   extended by the project.

Python does not read, write, *or* initialize Dhall -- the binary owns its config.
A normal command fails fast (exit 1) when no sibling ``<project>.dhall`` exists;
the config is created by an explicit ``project init`` or generated by the test
harness. Ensuring Docker, building the project container, writing/decoding config,
and applying the budget cordon are the project binary's job once it is running.
"""

from __future__ import annotations

import os
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import NamedTuple

from . import prereqs, process, substrate
from .substrate import Substrate, SubstrateName

_BREW: str = "brew"
_GHCUP: str = "ghcup"
_CABAL: str = "cabal"

# The family-pinned GHC every project's ``cabal.project`` selects.
GHC_VERSION: str = "9.12.4"

# The host-native build output directory; ./.build/<project> is always present.
_BUILD_DIR: str = ".build"

# The host-native cabal package store, kept repo-local under ./.build/.
_STORE_DIR: str = f"{_BUILD_DIR}/cabal-store"


class ProjectDiscoveryError(RuntimeError):
    """Raised when the project name cannot be derived from Cabal files."""


@dataclass(frozen=True)
class ProjectBuildSpec:
    """The only project facts Python needs before the binary exists."""

    project: str
    cabal_file: Path


def discover_project(project_root: Path) -> ProjectBuildSpec:
    """Derive the project name from the single ``*.cabal`` file in *project_root*."""
    cabal_files = sorted(path for path in project_root.glob("*.cabal") if path.is_file())
    if not cabal_files:
        raise ProjectDiscoveryError(f"no .cabal file found in {project_root}")
    if len(cabal_files) > 1:
        names = ", ".join(path.name for path in cabal_files)
        raise ProjectDiscoveryError(f"multiple .cabal files found in {project_root}: {names}")
    cabal_file = cabal_files[0]
    return ProjectBuildSpec(project=cabal_file.stem, cabal_file=cabal_file)


# ---------------------------------------------------------------------------
# Pure command-builders
# ---------------------------------------------------------------------------


class ToolchainStep(NamedTuple):
    """A single toolchain-ensure step: a quiet *probe* and its *install* fallback."""

    probe: tuple[str, ...]
    install: tuple[str, ...]


def toolchain_ensure_steps(sub: Substrate) -> tuple[ToolchainStep, ...]:
    """The host build-toolchain ensure steps (§ N), run before the build."""
    ghcup_steps = (
        ToolchainStep(
            probe=(_GHCUP, "whereis", "ghc", GHC_VERSION),
            install=(_GHCUP, "install", "ghc", GHC_VERSION, "--set"),
        ),
        ToolchainStep(
            probe=(_GHCUP, "whereis", "cabal"),
            install=(_GHCUP, "install", "cabal", "--set"),
        ),
    )
    if sub.name is SubstrateName.APPLE_SILICON:
        return (
            ToolchainStep(
                probe=(_GHCUP, "--version"),
                install=(_BREW, "install", "ghcup"),
            ),
            *ghcup_steps,
        )
    return ghcup_steps


def native_build_command(spec: ProjectBuildSpec, project_root: Path) -> tuple[str, ...]:
    """Build the project binary host-native, in place."""
    return (
        _CABAL,
        "--store-dir",
        str(project_root / _STORE_DIR),
        "build",
        f"exe:{spec.project}",
    )


def native_listbin_command(spec: ProjectBuildSpec, project_root: Path) -> tuple[str, ...]:
    """Print the built exe's path under ``dist-newstyle/``."""
    return (
        _CABAL,
        "--store-dir",
        str(project_root / _STORE_DIR),
        "list-bin",
        f"exe:{spec.project}",
    )


def binary_path(spec: ProjectBuildSpec, project_root: Path) -> Path:
    """The single stable ``./.build/<project>`` location every consumer execs."""
    return project_root / _BUILD_DIR / spec.project


def exec_argv(spec: ProjectBuildSpec, project_root: Path, args: tuple[str, ...]) -> tuple[str, ...]:
    """The argv handed to ``os.execv``: the built binary plus trailing args."""
    return (str(binary_path(spec, project_root)), *args)


# ---------------------------------------------------------------------------
# Async driver
# ---------------------------------------------------------------------------


async def _assert_minimums(sub: Substrate) -> None:
    await prereqs.run_doctor(sub)


async def _already_present(probe: tuple[str, ...]) -> bool:
    """Whether *probe* reports its tool present."""
    try:
        result = await process.run(probe, quiet=True)
    except FileNotFoundError:
        return False
    return result.ok


async def _ensure_toolchain(sub: Substrate) -> None:
    """Ensure the host build toolchain."""
    for step in toolchain_ensure_steps(sub):
        if await _already_present(step.probe):
            continue
        await process.run_checked(step.install)


async def _build_native(spec: ProjectBuildSpec, *, project_root: Path) -> None:
    """Build the binary host-native and copy it to ``./.build/<project>``."""
    binary_path(spec, project_root).parent.mkdir(parents=True, exist_ok=True)
    await process.run_checked(native_build_command(spec, project_root), cwd=project_root)
    located = await process.run_checked(
        native_listbin_command(spec, project_root), cwd=project_root, quiet=True
    )
    shutil.copy2(Path(located.stdout.strip()), binary_path(spec, project_root))


async def build_binary(spec: ProjectBuildSpec, *, project_root: Path) -> Path:
    """Run the pre-binary bootstrap (§§ M, N) and build the binary host-native."""
    sub = substrate.detect()
    await _assert_minimums(sub)
    await _ensure_toolchain(sub)
    await _build_native(spec, project_root=project_root)
    return binary_path(spec, project_root)


async def bootstrap(
    spec: ProjectBuildSpec,
    *,
    project_root: Path,
    args: tuple[str, ...] = (),
) -> None:
    """Build the project binary host-native, then ``exec`` it with ``args``."""
    await build_binary(spec, project_root=project_root)
    argv = exec_argv(spec, project_root, args)
    os.execv(argv[0], list(argv))  # pragma: no cover
