module HostBootstrap.Ensure.Colima.Backend.Resolver.Program
  ( resolverProgram,
    resolverProgramForFixtureRoot,
    resolverProgramForFixtureRootAndHomeRoot,
  )
where

import System.FilePath ((</>))

resolverProgram :: String
resolverProgram = resolverProgramWithLayout productionLayout

-- | Render the production resolver against an isolated, caller-owned tree.
-- This is consumed only by the private test facade; production resolution
-- always uses 'resolverProgram' and therefore the fixed Apple candidate table.
resolverProgramForFixtureRoot :: FilePath -> Either String String
resolverProgramForFixtureRoot root@('/' : _)
  | any (`elem` ['\0', '\r', '\n']) root = Left "resolver-fixture-root"
  | otherwise = Right (resolverProgramWithLayout (fixtureLayout root))
resolverProgramForFixtureRoot _ = Left "resolver-fixture-root"

resolverProgramForFixtureRootAndHomeRoot :: FilePath -> FilePath -> Either String String
resolverProgramForFixtureRootAndHomeRoot root@('/' : _) homeRoot@('/' : _)
  | any invalid (root ++ homeRoot) = Left "resolver-fixture-layout"
  | otherwise =
      Right
        ( resolverProgramWithLayout
            (fixtureLayout root) {layoutUserHomeRoot = homeRoot}
        )
  where
    invalid character = character `elem` ['\0', '\r', '\n']
resolverProgramForFixtureRootAndHomeRoot _ _ = Left "resolver-fixture-layout"

data ResolverLayout = ResolverLayout
  { layoutRoot :: FilePath,
    layoutPython :: FilePath,
    layoutBrew :: FilePath,
    layoutColima :: FilePath,
    layoutLima :: FilePath,
    layoutDockerBrew :: FilePath,
    layoutDockerApp :: FilePath,
    layoutSystemHelpers :: [FilePath],
    layoutAdministrativeDirectories :: [FilePath],
    layoutHomebrewRoot :: FilePath,
    layoutApplicationRoot :: FilePath,
    layoutUserHomeRoot :: FilePath,
    layoutSystemOwner :: String,
    layoutPlatform :: String,
    layoutMachine :: String
  }

productionLayout :: ResolverLayout
productionLayout =
  ResolverLayout
    { layoutRoot = "/",
      layoutPython = "/usr/bin/python3",
      layoutBrew = "/opt/homebrew/bin/brew",
      layoutColima = "/opt/homebrew/bin/colima",
      layoutLima = "/opt/homebrew/bin/limactl",
      layoutDockerBrew = "/opt/homebrew/bin/docker",
      layoutDockerApp = "/Applications/Docker.app/Contents/Resources/bin/docker",
      layoutSystemHelpers = ["/usr/bin", "/bin", "/usr/sbin", "/sbin"],
      layoutAdministrativeDirectories =
        [ "/opt/homebrew",
          "/opt/homebrew/bin",
          "/opt/homebrew/Cellar",
          "/opt/homebrew/opt",
          "/Applications"
        ],
      layoutHomebrewRoot = "/opt/homebrew",
      layoutApplicationRoot = "/Applications",
      layoutUserHomeRoot = "/Users",
      layoutSystemOwner = "0",
      layoutPlatform = "sys.platform",
      layoutMachine = "os.uname().machine"
    }

fixtureLayout :: FilePath -> ResolverLayout
fixtureLayout root =
  let homebrew = root </> "opt" </> "homebrew"
      applications = root </> "Applications"
   in ResolverLayout
        { layoutRoot = root,
          layoutPython = root </> "usr" </> "bin" </> "python3",
          layoutBrew = homebrew </> "bin" </> "brew",
          layoutColima = homebrew </> "bin" </> "colima",
          layoutLima = homebrew </> "bin" </> "limactl",
          layoutDockerBrew = homebrew </> "bin" </> "docker",
          layoutDockerApp = applications </> "Docker.app" </> "Contents" </> "Resources" </> "bin" </> "docker",
          layoutSystemHelpers =
            [root </> "usr" </> "bin", root </> "bin", root </> "usr" </> "sbin", root </> "sbin"],
          layoutAdministrativeDirectories =
            [ homebrew,
              homebrew </> "bin",
              homebrew </> "Cellar",
              homebrew </> "opt",
              applications
            ],
          layoutHomebrewRoot = homebrew,
          layoutApplicationRoot = applications,
          layoutUserHomeRoot = root </> "Users",
          layoutSystemOwner = "EUID",
          layoutPlatform = pythonLiteral "darwin",
          layoutMachine = pythonLiteral "arm64"
        }

resolverProgramWithLayout :: ResolverLayout -> String
resolverProgramWithLayout layout =
  unlines
    [ "import os",
      "import stat",
      "import sys",
      "",
      "class Rejected(Exception):",
      "    pass",
      "",
      "EUID = os.geteuid()",
      "ROOT = " ++ pythonLiteral (layoutRoot layout),
      "PYTHON = " ++ pythonLiteral (layoutPython layout),
      "BREW = " ++ pythonLiteral (layoutBrew layout),
      "COLIMA = " ++ pythonLiteral (layoutColima layout),
      "LIMA = " ++ pythonLiteral (layoutLima layout),
      "DOCKER_BREW = " ++ pythonLiteral (layoutDockerBrew layout),
      "DOCKER_APP = " ++ pythonLiteral (layoutDockerApp layout),
      "HOMEBREW_ROOT = " ++ pythonLiteral (layoutHomebrewRoot layout),
      "APPLICATION_ROOT = " ++ pythonLiteral (layoutApplicationRoot layout),
      "USER_HOME_ROOT = " ++ pythonLiteral (layoutUserHomeRoot layout),
      "SYSTEM_HELPERS = " ++ pythonTuple (layoutSystemHelpers layout),
      "SYSTEM_OWNER = " ++ layoutSystemOwner layout,
      "PLATFORM = " ++ layoutPlatform layout,
      "MACHINE = " ++ layoutMachine layout,
      "ADMIN_GROUP_WRITABLE = frozenset(" ++ pythonTuple (layoutAdministrativeDirectories layout) ++ ")",
      "DIR_FLAGS = os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC | os.O_NOFOLLOW",
      "FILE_FLAGS = os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW",
      "",
      "def reject(reason):",
      "    raise Rejected(reason)",
      "",
      "def normalized_absolute(path):",
      "    return (",
      "        isinstance(path, str)",
      "        and path.startswith('/')",
      "        and path == os.path.normpath(path)",
      "        and '\\x00' not in path",
      "        and '\\t' not in path",
      "        and '\\r' not in path",
      "        and '\\n' not in path",
      "    )",
      "",
      "def same_identity(left, right):",
      "    return left.st_dev == right.st_dev and left.st_ino == right.st_ino",
      "",
      "def writable_by_world(status):",
      "    return bool(stat.S_IMODE(status.st_mode) & stat.S_IWOTH)",
      "",
      "def writable_by_group(status):",
      "    return bool(stat.S_IMODE(status.st_mode) & stat.S_IWGRP)",
      "",
      "def expected_owner(path, policy, home):",
      "    if policy == 'system':",
      "        return (SYSTEM_OWNER,)",
      "    if policy == 'homebrew':",
      "        if path in (ROOT, os.path.dirname(HOMEBREW_ROOT)):",
      "            return (SYSTEM_OWNER,)",
      "        return (EUID,)",
      "    if policy == 'application':",
      "        if path in (ROOT, APPLICATION_ROOT):",
      "            return (SYSTEM_OWNER,)",
      "        return (0, EUID)",
      "    if policy == 'home':",
      "        if path == home:",
      "            return (EUID,)",
      "        return (SYSTEM_OWNER,)",
      "    reject('unknown-policy')",
      "",
      "def validate_directory(status, path, policy, home=None):",
      "    if not stat.S_ISDIR(status.st_mode):",
      "        reject('directory-type')",
      "    if status.st_uid not in expected_owner(path, policy, home):",
      "        reject('directory-owner')",
      "    if writable_by_world(status):",
      "        reject('directory-world-write')",
      "    if writable_by_group(status) and path not in ADMIN_GROUP_WRITABLE:",
      "        reject('directory-group-write')",
      "",
      "def open_directory(path, policy, home=None):",
      "    if not normalized_absolute(path):",
      "        reject('directory-path')",
      "    current = ROOT",
      "    fd = os.open(ROOT, DIR_FLAGS)",
      "    try:",
      "        validate_directory(os.fstat(fd), current, policy, home)",
      "        if ROOT == '/':",
      "            relative = path[1:]",
      "        elif path == ROOT:",
      "            relative = ''",
      "        elif path.startswith(ROOT + '/'):",
      "            relative = path[len(ROOT) + 1:]",
      "        else:",
      "            reject('directory-root')",
      "        for component in [part for part in relative.split('/') if part]:",
      "            child = os.open(component, DIR_FLAGS, dir_fd=fd)",
      "            child_status = os.fstat(child)",
      "            current = os.path.join(current, component)",
      "            try:",
      "                validate_directory(child_status, current, policy, home)",
      "            except Exception:",
      "                os.close(child)",
      "                raise",
      "            os.close(fd)",
      "            fd = child",
      "        return fd",
      "    except Exception:",
      "        os.close(fd)",
      "        raise",
      "",
      "def policy_for(path):",
      "    if path == HOMEBREW_ROOT or path.startswith(HOMEBREW_ROOT + '/'):",
      "        return 'homebrew'",
      "    if path == APPLICATION_ROOT or path.startswith(APPLICATION_ROOT + '/'):",
      "        return 'application'",
      "    if any(path == root or path.startswith(root + '/') for root in SYSTEM_HELPERS):",
      "        return 'system'",
      "    reject('path-policy')",
      "",
      "def inspect_entry(path, policy, allow_missing=False, allow_symlink=False):",
      "    parent = os.path.dirname(path)",
      "    name = os.path.basename(path)",
      "    try:",
      "        parent_fd = open_directory(parent, policy)",
      "    except FileNotFoundError:",
      "        if allow_missing:",
      "            return None",
      "        reject('candidate-parent-missing')",
      "    try:",
      "        try:",
      "            entry = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)",
      "        except FileNotFoundError:",
      "            if allow_missing:",
      "                return None",
      "            reject('candidate-missing')",
      "        if stat.S_ISLNK(entry.st_mode):",
      "            if not allow_symlink:",
      "                reject('candidate-symlink')",
      "            if entry.st_uid != EUID:",
      "                reject('symlink-owner')",
      "            target = os.readlink(name, dir_fd=parent_fd)",
      "            if os.path.isabs(target):",
      "                canonical = os.path.normpath(target)",
      "            else:",
      "                canonical = os.path.normpath(os.path.join(parent, target))",
      "            if not normalized_absolute(canonical):",
      "                reject('symlink-target')",
      "        elif stat.S_ISREG(entry.st_mode):",
      "            canonical = path",
      "        else:",
      "            reject('candidate-type')",
      "    finally:",
      "        os.close(parent_fd)",
      "    canonical_policy = policy_for(canonical)",
      "    canonical_parent = os.path.dirname(canonical)",
      "    canonical_name = os.path.basename(canonical)",
      "    try:",
      "        canonical_parent_fd = open_directory(canonical_parent, canonical_policy)",
      "        try:",
      "            opened = os.open(canonical_name, FILE_FLAGS, dir_fd=canonical_parent_fd)",
      "        except Exception:",
      "            os.close(canonical_parent_fd)",
      "            raise",
      "    except FileNotFoundError:",
      "        reject('candidate-dangling')",
      "    try:",
      "        status = os.fstat(opened)",
      "        named = os.stat(canonical_name, dir_fd=canonical_parent_fd, follow_symlinks=False)",
      "        if not same_identity(status, named):",
      "            reject('candidate-race')",
      "        if not stat.S_ISREG(status.st_mode):",
      "            reject('executable-type')",
      "        owners = (SYSTEM_OWNER,) if canonical_policy == 'system' else ((EUID,) if canonical_policy == 'homebrew' else (0, EUID))",
      "        if status.st_uid not in owners:",
      "            reject('executable-owner')",
      "        if writable_by_group(status) or writable_by_world(status):",
      "            reject('executable-write-mode')",
      "        if not (stat.S_IMODE(status.st_mode) & 0o111):",
      "            reject('executable-mode')",
      "        return (canonical, status.st_dev, status.st_ino)",
      "    finally:",
      "        os.close(opened)",
      "        os.close(canonical_parent_fd)",
      "",
      "def require_formula(tool, formula, binary):",
      "    path = tool[0]",
      "    prefix = HOMEBREW_ROOT + '/Cellar/' + formula + '/'",
      "    if not path.startswith(prefix):",
      "        reject(formula + '-formula-root')",
      "    suffix = path[len(prefix):].split('/')",
      "    if len(suffix) != 3 or not suffix[0] or suffix[1:] != ['bin', binary]:",
      "        reject(formula + '-formula-shape')",
      "    if suffix[0] in ('.', '..') or any(ch in suffix[0] for ch in '\\t\\r\\n'):",
      "        reject(formula + '-formula-version')",
      "",
      "def validate_home(home):",
      "    if not normalized_absolute(home):",
      "        reject('home-path')",
      "    if os.path.dirname(home) != USER_HOME_ROOT or os.path.basename(home) in ('', '.', '..'):",
      "        reject('home-shape')",
      "    fd = open_directory(home, 'home', home)",
      "    os.close(fd)",
      "",
      "def validate_helper_directory(path):",
      "    fd = open_directory(path, policy_for(path))",
      "    try:",
      "        status = os.fstat(fd)",
      "        return (path, status.st_dev, status.st_ino)",
      "    finally:",
      "        os.close(fd)",
      "",
      "def helper_path(paths):",
      "    admitted = []",
      "    bindings = []",
      "    for path in paths:",
      "        if path not in admitted:",
      "            binding = validate_helper_directory(path)",
      "            admitted.append(path)",
      "            bindings.append(','.join((binding[0], str(binding[1]), str(binding[2]))))",
      "    return (os.pathsep.join(admitted), ';'.join(bindings))",
      "",
      "def fields(tool):",
      "    return [tool[0], str(tool[1]), str(tool[2])]",
      "",
      "def emit(parts):",
      "    if any(('\\t' in part or '\\r' in part or '\\n' in part) for part in parts):",
      "        reject('protocol-field')",
      "    sys.stdout.write('\\t'.join(parts) + '\\n')",
      "    sys.stdout.flush()",
      "",
      "def resolve(home):",
      "    if PLATFORM != 'darwin' or MACHINE != 'arm64':",
      "        emit(['UNSUPPORTED', 'apple-silicon-required'])",
      "        return",
      "    validate_home(home)",
      "    python = inspect_entry(PYTHON, 'system')",
      "    if python[0] != PYTHON:",
      "        reject('python-canonical')",
      "    colima = inspect_entry(COLIMA, 'homebrew', allow_missing=True, allow_symlink=True)",
      "    if colima is None:",
      "        brew = inspect_entry(BREW, 'homebrew')",
      "        if brew[0] != BREW:",
      "            reject('brew-canonical')",
      "        path, bindings = helper_path([os.path.join(HOMEBREW_ROOT, 'bin')] + list(SYSTEM_HELPERS))",
      "        emit(['MISSING_COLIMA'] + fields(python) + fields(brew) + [path, bindings])",
      "        return",
      "    require_formula(colima, 'colima', 'colima')",
      "    lima = inspect_entry(LIMA, 'homebrew', allow_symlink=True)",
      "    require_formula(lima, 'lima', 'limactl')",
      "    docker = inspect_entry(DOCKER_BREW, 'homebrew', allow_missing=True, allow_symlink=True)",
      "    if docker is None:",
      "        docker = inspect_entry(DOCKER_APP, 'application', allow_missing=True)",
      "        if docker is None:",
      "            reject('docker-missing')",
      "        if docker[0] != DOCKER_APP:",
      "            reject('docker-app-canonical')",
      "    else:",
      "        require_formula(docker, 'docker', 'docker')",
      "    path, bindings = helper_path([",
      "        os.path.dirname(colima[0]),",
      "        os.path.dirname(lima[0]),",
      "        os.path.dirname(docker[0]),",
      "        os.path.join(HOMEBREW_ROOT, 'bin'),",
      "    ] + list(SYSTEM_HELPERS))",
      "    emit(",
      "        ['READY']",
      "        + fields(python)",
      "        + fields(colima)",
      "        + fields(docker)",
      "        + fields(lima)",
      "        + [path, bindings]",
      "    )",
      "",
      "try:",
      "    if len(sys.argv) != 2:",
      "        reject('argument-count')",
      "    resolve(sys.argv[1])",
      "except Rejected as error:",
      "    emit(['UNSUPPORTED', str(error)])",
      "except (OSError, ValueError):",
      "    emit(['UNSUPPORTED', 'resolver-system-error'])"
    ]

pythonTuple :: [String] -> String
pythonTuple values = "(" ++ concatMap ((++ ",") . pythonLiteral) values ++ ")"

pythonLiteral :: String -> String
pythonLiteral value = "'" ++ concatMap escape value ++ "'"
  where
    escape '\\' = "\\\\"
    escape '\'' = "\\'"
    escape '\n' = "\\n"
    escape '\r' = "\\r"
    escape '\t' = "\\t"
    escape character = [character]
