module HostBootstrap.Ensure.Colima.Backend.Program.Acquire
  ( acquireProgram,
  )
where

import HostBootstrap.Ensure.Colima.Backend.Program.Common (commonProgram)

-- One child owns the profile-global flock and every retained filesystem
-- descriptor from first absence proof through durable origin, isolated Colima
-- and Docker namespace publication, mutation, and exact settlement.
acquireProgram :: String
acquireProgram =
  unlines commonProgram
    ++ unlines
      [ "colima,docker,lima,profile,lock_path,state_root,record,expected_owner,expected_invocation,cpu_raw,memory_raw,disk_raw,root_raw,timeout_raw,test_crash,*start_args=sys.argv[1:]",
        "if any(re.fullmatch(r'[1-9][0-9]*',value) is None for value in (cpu_raw,memory_raw,disk_raw,root_raw,timeout_raw)): finish('UNSUPPORTED numeric-argument')",
        "if test_crash not in ('none','after-home-stage','after-context-stage','during-start','after-start'): finish('UNSUPPORTED test-crash-point')",
        "cpu=int(cpu_raw); memory=int(memory_raw); disk=int(disk_raw); root_disk=int(root_raw); expected_wall=(cpu,memory,disk,root_disk); command_timeout=int(timeout_raw)",
        "if re.fullmatch(r'h-[0-9a-f]{6}',profile) is None: finish('UNSUPPORTED profile')",
        "if not valid_owner(expected_owner) or not valid_nonce(expected_invocation): finish('UNSUPPORTED owner-token')",
        "lock_root=os.path.dirname(lock_path); lock_root_descriptor,lock_chain=open_directory(lock_root,'lock-root')",
        "lock_descriptor=open_lock(lock_root,lock_root_descriptor,lock_path,True); lock_identity=identity(os.fstat(lock_descriptor)); validate_lock_empty(lock_descriptor)",
        "root_descriptor,root_chain=open_directory(state_root,'state-root')",
        "state_directory,state_descriptor,record_name,opened_state_chain,docker_descriptor,docker_identity,docker_created=ensure_state_directory(state_root,root_descriptor,root_chain,record,True,os.environ.get('DOCKER_CONFIG',''))",
        "state_directory_chain=[entry for entry in opened_state_chain if docker_descriptor is None or entry[1] != docker_descriptor]",
        "state_base_chain=lock_chain+state_directory_chain",
        "colima_parent,colima_name,colima_parent_descriptor,colima_chain,colima_descriptor,colima_identity=open_colima_home(os.environ.get('COLIMA_HOME',''))",
        "state_chain=state_base_chain+colima_chain",
        "if docker_descriptor is not None: state_chain.append((os.environ.get('DOCKER_CONFIG',''),docker_descriptor,state_descriptor,record_name+'.docker'))",
        "def crash_during_start():",
        "    time.sleep(0.2)",
        "    marker=os.path.join(os.path.dirname(state_root),'backend-killed')",
        "    descriptor=os.open(marker,os.O_WRONLY|os.O_CREAT|os.O_EXCL|nofollow,0o600)",
        "    os.write(descriptor,b'killed\\n'); os.fsync(descriptor); os.close(descriptor)",
        "    os.kill(os.getpid(),signal.SIGKILL)",
        "def command(stage,args):",
        "    if stage == 'start' and test_crash == 'during-start': threading.Thread(target=crash_during_start,daemon=True).start()",
        "    return bounded_command(stage,args,command_timeout,lock_descriptor,lock_path,state_chain,lock_identity)",
        "def finish_owned(kind,parsed):",
        "    validate_lock(lock_descriptor,lock_path,lock_identity); validate_chain_identity(state_chain,parsed.chain)",
        "    observed=open_record_retained(state_descriptor,record_name)",
        "    if observed is None or observed[1].data != parsed.data or observed[1].record != parsed.record: finish('FAILED record-final-readback')",
        "    os.close(observed[0])",
        "    finish(kind+' '+parsed.nonce+' '+parsed.machine+' '+parsed.context+' '+str(parsed.epoch)+' '+str(lock_identity[0])+' '+str(lock_identity[1])+' '+str(parsed.record[0])+' '+str(parsed.record[1])+' '+str(parsed.docker[0])+' '+str(parsed.docker[1])+' '+str(parsed.colima[0])+' '+str(parsed.colima[1])+' '+str(parsed.disk[0])+' '+str(parsed.disk[1])+' '+parsed.artifacts+' '+','.join(identity_text(value) for value in parsed.chain))",
        "def observe():",
        "    if colima_descriptor is None: return None",
        "    raw=command('list',[colima,'list','--json'])",
        "    if raw.returncode != 0: finish('FAILED list')",
        "    values=strict_colima_values(raw); matches=[value for value in values if value.get('name') == profile]",
        "    if len(matches) > 1: finish('CONFLICT duplicate-profile')",
        "    return matches[0] if matches else None",
        "def require_running(value):",
        "    if not exact_wall(value,cpu,memory,disk): finish('CONFLICT wall-mismatch')",
        "    if type(value.get('status')) is not str or value.get('status').lower() != 'running': finish('UNSUPPORTED stable-identity')",
        "def settle_running():",
        "    current=observe()",
        "    if current is None: finish('FAILED settle-absent')",
        "    require_running(current); machine,epoch_value=read_machine(command,profile)",
        "    context_digest=context_fingerprint(command,docker,'colima-'+profile,docker_descriptor)",
        "    artifacts=observe_profile_artifacts(command,lima,profile,os.environ.get('COLIMA_HOME',''),colima_descriptor,expected_wall)",
        "    if artifacts is None: finish('FAILED settle-disk-absent')",
        "    state_chain.extend(artifacts.chain); validate_artifact_entries(artifacts.entries)",
        "    return machine,epoch_value,context_digest,artifacts",
        "def managed_stage(nonce,machine,epoch_value,context_digest,artifacts):",
        "    validate_artifact_entries(artifacts.entries)",
        "    path,parsed=create_transition_stage(record_name,state_descriptor,'managed',expected_owner,nonce,expected_invocation,machine,epoch_value,context_digest,lock_identity,docker_identity,colima_identity,artifacts.disk,artifacts.wall,artifacts.digest,state_chain)",
        "    return (path,parsed,1)",
        "def finish_new(prepared_descriptor,prepared,nonce):",
        "    existing=observe_profile_artifacts(command,lima,profile,os.environ.get('COLIMA_HOME',''),colima_descriptor)",
        "    if existing is not None: finish('CONFLICT residual-disk')",
        "    if not profile_artifacts_absent(colima_descriptor,profile): finish('CONFLICT residual-profile-data')",
        "    if named_context_present(command,docker,'colima-'+profile): finish('CONFLICT docker-context-present')",
        "    started=command('start',[colima]+start_args)",
        "    if started.returncode != 0: finish('FAILED start')",
        "    if test_crash == 'after-start': os.kill(os.getpid(),signal.SIGKILL)",
        "    machine,epoch_value,context_digest,artifacts=settle_running()",
        "    entry=managed_stage(nonce,machine,epoch_value,context_digest,artifacts)",
        "    promote_transition(record_name,state_descriptor,prepared_descriptor,prepared,entry,state_chain,lock_descriptor,lock_path,lock_identity)",
        "    managed=open_record_retained(state_descriptor,record_name)",
        "    if managed is None: finish('FAILED record-missing')",
        "    parsed=managed[1]; os.close(managed[0]); finish_owned('APPLIED',parsed)",
        "final,stages=load_protocol_state(record_name,state_descriptor,expected_owner,expected_invocation,docker_descriptor)",
        "if final is None:",
        "    if colima_descriptor is not None or docker_descriptor is not None: finish('CONFLICT namespace-present')",
        "    old_release=open_record_retained(state_descriptor,released_marker_name(record_name),(1,))",
        "    if old_release is not None:",
        "        if old_release[1].state != 'released' or old_release[1].owner != expected_owner or old_release[1].lock != lock_identity: finish('CONFLICT released-marker')",
        "        if old_release[1].invocation == expected_invocation: finish('CONFLICT invocation-released')",
        "        old_manifest=open_release_manifest(state_descriptor,record_name,expected_owner,old_release[1].nonce)",
        "        if old_manifest is not None:",
        "            if old_manifest[1].identity != old_release[1].manifest or old_manifest[1].digest != old_release[1].manifest_digest: finish('CONFLICT docker-manifest-identity')",
        "            unlink_release_manifest(state_descriptor,record_name,old_manifest[0],old_manifest[1])",
        "        unlink_parsed_record(state_descriptor,released_marker_name(record_name),old_release[1]); os.close(old_release[0])",
        "    nonce=secrets.token_hex(32); publish_reserved(record_name,state_descriptor,expected_owner,nonce,expected_invocation,lock_identity,state_chain)",
        "    final,stages=load_protocol_state(record_name,state_descriptor,expected_owner,expected_invocation,docker_descriptor)",
        "record_descriptor,parsed=final",
        "if parsed.lock != lock_identity: finish('CONFLICT lock-record')",
        "if parsed.state == 'reserved':",
        "    if colima_descriptor is not None or docker_descriptor is not None: finish('CONFLICT namespace-present')",
        "    if set(stages)-{'reserved','home-staged'}: finish('CONFLICT stage-state')",
        "    pending=stages.get('home-staged')",
        "    colima_parent,colima_name,colima_parent_descriptor,home_stage_chain,home_stage_descriptor,colima_identity=create_colima_home_stage(os.environ.get('COLIMA_HOME',''),expected_owner,parsed.nonce,None if pending is None else pending[1].colima)",
        "    if pending is None and test_crash == 'after-home-stage': os.kill(os.getpid(),signal.SIGKILL)",
        "    state_chain=state_base_chain+home_stage_chain",
        "    if pending is None:",
        "        path,target=create_transition_stage(record_name,state_descriptor,'home-staged',expected_owner,parsed.nonce,expected_invocation,'absent','absent','absent',lock_identity,None,colima_identity,None,None,None,state_chain); pending=(path,target,1)",
        "    if pending[1].colima != colima_identity or pending[1].chain != chain_identity(state_chain): finish('CONFLICT home-stage-transition')",
        "    promote_transition(record_name,state_descriptor,record_descriptor,parsed,pending,state_chain,lock_descriptor,lock_path,lock_identity)",
        "    final=open_record_retained(state_descriptor,record_name); record_descriptor,parsed=final",
        "if parsed.state == 'home-staged':",
        "    if set(stages)-{'reserved','home-ready','home-staged'}: finish('CONFLICT stage-state')",
        "    colima_descriptor,colima_identity,colima_chain=publish_colima_home(os.environ.get('COLIMA_HOME',''),expected_owner,parsed.nonce,parsed.colima)",
        "    state_chain=state_base_chain+colima_chain",
        "    pending=stages.get('home-ready')",
        "    if pending is None:",
        "        path,target=create_transition_stage(record_name,state_descriptor,'home-ready',expected_owner,parsed.nonce,expected_invocation,'absent','absent','absent',lock_identity,None,colima_identity,None,None,None,state_chain); pending=(path,target,1)",
        "    if pending[1].colima != colima_identity or pending[1].chain != chain_identity(state_chain): finish('CONFLICT home-ready-transition')",
        "    promote_transition(record_name,state_descriptor,record_descriptor,parsed,pending,state_chain,lock_descriptor,lock_path,lock_identity)",
        "    final=open_record_retained(state_descriptor,record_name); record_descriptor,parsed=final",
        "if parsed.state == 'home-ready':",
        "    if colima_descriptor is None or colima_identity != parsed.colima: finish('CONFLICT colima-home-identity')",
        "    validate_colima_home_marker(colima_descriptor,expected_owner,parsed.nonce,colima_identity)",
        "    if observe() is not None: finish('CONFLICT home-ready-profile-present')",
        "    residual=observe_profile_artifacts(command,lima,profile,os.environ.get('COLIMA_HOME',''),colima_descriptor)",
        "    if residual is not None: finish('CONFLICT residual-disk')",
        "    if not profile_artifacts_absent(colima_descriptor,profile): finish('CONFLICT residual-profile-data')",
        "    if docker_descriptor is not None: finish('CONFLICT docker-namespace-present')",
        "    if set(stages)-{'reserved','context-staged','home-ready'}: finish('CONFLICT stage-state')",
        "    pending=stages.get('context-staged')",
        "    stage_path_value,stage_descriptor,docker_identity=create_context_stage(state_directory,state_descriptor,record_name,parsed.nonce,os.environ.get('DOCKER_CONFIG',''),None if pending is None else pending[1].docker)",
        "    if pending is None and test_crash == 'after-context-stage': os.kill(os.getpid(),signal.SIGKILL)",
        "    state_chain=state_base_chain+colima_chain+[(stage_path_value,stage_descriptor,state_descriptor,os.path.basename(stage_path_value))]",
        "    if pending is None:",
        "        path,target=create_transition_stage(record_name,state_descriptor,'context-staged',expected_owner,parsed.nonce,expected_invocation,'absent','absent','absent',lock_identity,docker_identity,colima_identity,None,None,None,state_chain); pending=(path,target,1)",
        "    if pending[1].docker != docker_identity or pending[1].colima != colima_identity or pending[1].chain != chain_identity(state_chain): finish('CONFLICT context-stage-transition')",
        "    promote_transition(record_name,state_descriptor,record_descriptor,parsed,pending,state_chain,lock_descriptor,lock_path,lock_identity)",
        "    final=open_record_retained(state_descriptor,record_name); record_descriptor,parsed=final",
        "if parsed.state == 'context-staged':",
        "    if colima_descriptor is None or colima_identity != parsed.colima: finish('CONFLICT colima-home-identity')",
        "    if set(stages)-{'reserved','prepared','context-staged'}: finish('CONFLICT stage-state')",
        "    if docker_descriptor is None:",
        "        stage_path_value,stage_descriptor,docker_identity=create_context_stage(state_directory,state_descriptor,record_name,parsed.nonce,os.environ.get('DOCKER_CONFIG',''),parsed.docker)",
        "        state_chain=state_base_chain+colima_chain+[(stage_path_value,stage_descriptor,state_descriptor,os.path.basename(stage_path_value))]",
        "    elif docker_identity != parsed.docker: finish('CONFLICT docker-identity')",
        "    docker_path,docker_descriptor,docker_identity=publish_context_target(state_directory,state_descriptor,record_name,parsed.nonce,os.environ.get('DOCKER_CONFIG',''),parsed.docker)",
        "    state_chain=state_base_chain+colima_chain+[(docker_path,docker_descriptor,state_descriptor,record_name+'.docker')]",
        "    pending=stages.get('prepared')",
        "    if pending is None:",
        "        path,target=create_transition_stage(record_name,state_descriptor,'prepared',expected_owner,parsed.nonce,expected_invocation,'absent','absent','absent',lock_identity,docker_identity,colima_identity,None,None,None,state_chain); pending=(path,target,1)",
        "    if pending[1].chain != chain_identity(state_chain): finish('CONFLICT prepared-transition')",
        "    promote_transition(record_name,state_descriptor,record_descriptor,parsed,pending,state_chain,lock_descriptor,lock_path,lock_identity)",
        "    final=open_record_retained(state_descriptor,record_name); record_descriptor,parsed=final",
        "if parsed.state == 'prepared':",
        "    if colima_descriptor is None or colima_identity != parsed.colima or docker_descriptor is None or docker_identity != parsed.docker: finish('CONFLICT namespace-record')",
        "    validate_colima_home_marker(colima_descriptor,expected_owner,parsed.nonce,colima_identity)",
        "    unexpected=set(stages)-{'reserved','managed'}",
        "    if unexpected: finish('CONFLICT stage-state')",
        "    pending=stages.get('managed')",
        "    current=observe()",
        "    if pending is not None:",
        "        if current is None: finish('CONFLICT managed-stage-profile-absent')",
        "        require_running(current); machine,epoch_value=read_machine(command,profile); context_digest=context_fingerprint(command,docker,'colima-'+profile,docker_descriptor)",
        "        artifacts=observe_profile_artifacts(command,lima,profile,os.environ.get('COLIMA_HOME',''),colima_descriptor,expected_wall)",
        "        if artifacts is None: finish('CONFLICT managed-stage-disk-absent')",
        "        state_chain.extend(artifacts.chain); validate_artifact_entries(artifacts.entries)",
        "        if pending[1].machine != machine or pending[1].epoch != epoch_value or pending[1].context != context_digest or pending[1].disk != artifacts.disk or pending[1].wall != artifacts.wall or pending[1].artifacts != artifacts.digest or pending[1].chain != chain_identity(state_chain): finish('CONFLICT managed-stage-identity')",
        "        promote_transition(record_name,state_descriptor,record_descriptor,parsed,pending,state_chain,lock_descriptor,lock_path,lock_identity)",
        "        managed=open_record_retained(state_descriptor,record_name); result=managed[1]; os.close(managed[0]); finish_owned('APPLIED',result)",
        "    if current is not None: finish('CONFLICT prepared-profile-present')",
        "    finish_new(record_descriptor,parsed,parsed.nonce)",
        "if parsed.state in ('releasing','context-released','released'): finish('CONFLICT cleanup-in-progress')",
        "if parsed.state != 'managed': finish('CONFLICT record-state')",
        "if colima_descriptor is None or colima_identity != parsed.colima or docker_descriptor is None or docker_identity != parsed.docker: finish('CONFLICT namespace-record')",
        "validate_colima_home_marker(colima_descriptor,expected_owner,parsed.nonce,colima_identity)",
        "current=observe()",
        "if current is None: finish('FAILED owned-profile-absent')",
        "require_running(current); machine,epoch_value=read_machine(command,profile); context_digest=context_fingerprint(command,docker,'colima-'+profile,docker_descriptor)",
        "artifacts=observe_profile_artifacts(command,lima,profile,os.environ.get('COLIMA_HOME',''),colima_descriptor,expected_wall)",
        "if artifacts is None or artifacts.disk != parsed.disk or artifacts.wall != parsed.wall or artifacts.digest != parsed.artifacts: finish('CONFLICT disk-identity')",
        "state_chain.extend(artifacts.chain); validate_chain_identity(state_chain,parsed.chain); validate_artifact_entries(artifacts.entries)",
        "if machine != parsed.machine or epoch_value != parsed.epoch or context_digest != parsed.context: finish('CONFLICT identity-mismatch')",
        "os.close(record_descriptor); finish_owned('EXACT',parsed)"
      ]
