module HostBootstrap.Ensure.Colima.Backend.Program.Cleanup
  ( cleanupProgram,
  )
where

import HostBootstrap.Ensure.Colima.Backend.Program.Common (commonProgram)

-- The acquisition invocation, independent teardown invocation, stable VM,
-- profile-global Colima home, Lima data disk, Docker context, state-directory
-- chain, and release manifest are all revalidated under one retained flock.
cleanupProgram :: String
cleanupProgram =
  unlines commonProgram
    ++ unlines
      [ "colima,docker,lima,profile,lock_path,state_root,record,expected_owner,expected_acquire_invocation,expected_cleanup_invocation,expected_nonce,expected_machine,expected_context,expected_epoch_raw,expected_cpu_raw,expected_memory_raw,expected_data_raw,expected_root_raw,expected_artifacts,lock_device_raw,lock_inode_raw,record_device_raw,record_inode_raw,docker_device_raw,docker_inode_raw,colima_device_raw,colima_inode_raw,disk_device_raw,disk_inode_raw,expected_chain_raw,timeout_raw,test_crash=sys.argv[1:]",
        "if not valid_owner(expected_owner) or not valid_nonce(expected_acquire_invocation) or not valid_nonce(expected_cleanup_invocation): finish('CONFLICT owner-token')",
        "if re.fullmatch(r'h-[0-9a-f]{6}',profile) is None: finish('CONFLICT profile')",
        "if not valid_nonce(expected_nonce) or not valid_machine(expected_machine) or not valid_nonce(expected_context): finish('CONFLICT authority-format')",
        "expected_epoch=uint(expected_epoch_raw,True); expected_cpu=uint(expected_cpu_raw,True); expected_memory=uint(expected_memory_raw,True); expected_data=uint(expected_data_raw,True); expected_root=uint(expected_root_raw,True); lock_device=uint(lock_device_raw); lock_inode=uint(lock_inode_raw,True); record_device=uint(record_device_raw); record_inode=uint(record_inode_raw,True); docker_device=uint(docker_device_raw); docker_inode=uint(docker_inode_raw,True); colima_device=uint(colima_device_raw); colima_inode=uint(colima_inode_raw,True); disk_device=uint(disk_device_raw); disk_inode=uint(disk_inode_raw,True); expected_chain=parse_chain(expected_chain_raw); command_timeout=uint(timeout_raw,True)",
        "if re.fullmatch(r'[0-9a-f]{64}',expected_artifacts) is None or None in (expected_epoch,expected_cpu,expected_memory,expected_data,expected_root,lock_device,lock_inode,record_device,record_inode,docker_device,docker_inode,colima_device,colima_inode,disk_device,disk_inode,expected_chain,command_timeout): finish('CONFLICT authority-format')",
        "if test_crash not in ('none','after-released-marker'): finish('UNSUPPORTED test-crash-point')",
        "expected_wall=(expected_cpu,expected_memory,expected_data,expected_root)",
        "expected_lock=(lock_device,lock_inode); expected_record=(record_device,record_inode); expected_docker=(docker_device,docker_inode); expected_colima=(colima_device,colima_inode); expected_disk=(disk_device,disk_inode)",
        "lock_root=os.path.dirname(lock_path); lock_root_descriptor,lock_chain=open_directory(lock_root,'lock-root')",
        "lock_descriptor=open_lock(lock_root,lock_root_descriptor,lock_path,False,expected_lock); validate_lock_empty(lock_descriptor)",
        "root_descriptor,root_chain=open_directory(state_root,'state-root')",
        "state_directory,state_descriptor,record_name,opened_state_chain,docker_descriptor,docker_identity,docker_created=ensure_state_directory(state_root,root_descriptor,root_chain,record,False,os.environ.get('DOCKER_CONFIG',''))",
        "state_directory_chain=[entry for entry in opened_state_chain if docker_descriptor is None or entry[1] != docker_descriptor]",
        "state_base_chain=lock_chain+state_directory_chain",
        "colima_parent,colima_name,colima_parent_descriptor,colima_chain,colima_descriptor,colima_identity=open_colima_home(os.environ.get('COLIMA_HOME',''))",
        "state_chain=state_base_chain+colima_chain",
        "if docker_descriptor is not None: state_chain.append((os.environ.get('DOCKER_CONFIG',''),docker_descriptor,state_descriptor,record_name+'.docker'))",
        "if docker_descriptor is not None and docker_identity != expected_docker: finish('CONFLICT docker-identity')",
        "if colima_descriptor is not None and colima_identity != expected_colima: finish('CONFLICT colima-home-identity')",
        "def command(stage,args): return bounded_command(stage,args,command_timeout,lock_descriptor,lock_path,state_chain,expected_lock)",
        "def delete_command(args,post_chain): return bounded_command('delete',args,command_timeout,lock_descriptor,lock_path,state_chain,expected_lock,post_chain)",
        "def observe():",
        "    if colima_descriptor is None: return None",
        "    raw=command('list',[colima,'list','--json'])",
        "    if raw.returncode != 0: finish('FAILED list')",
        "    values=strict_colima_values(raw); matches=[value for value in values if value.get('name') == profile]",
        "    if len(matches) > 1: finish('CONFLICT duplicate-profile')",
        "    return matches[0] if matches else None",
        "def validate_authority(parsed):",
        "    validate_surviving_chain(state_chain,expected_chain)",
        "    if parsed.owner != expected_owner or parsed.invocation != expected_acquire_invocation or parsed.nonce != expected_nonce or parsed.machine != expected_machine or parsed.context != expected_context or parsed.epoch != expected_epoch or parsed.lock != expected_lock or parsed.docker != expected_docker or parsed.colima != expected_colima or parsed.disk != expected_disk or parsed.wall != expected_wall or parsed.artifacts != expected_artifacts or parsed.chain != tuple(expected_chain): finish('CONFLICT record-mismatch')",
        "    if parsed.state == 'managed' and parsed.record != expected_record: finish('CONFLICT record-identity')",
        "    if parsed.state in ('releasing','context-released','released') and (parsed.managed != expected_record or parsed.cleanup != expected_cleanup_invocation): finish('CONFLICT teardown-invocation')",
        "release_manifest=None; release_manifest_descriptor=None",
        "def validate_release_authority(parsed):",
        "    validate_authority(parsed)",
        "    if parsed.state not in ('releasing','context-released','released') or release_manifest is None or parsed.manifest != release_manifest.identity or parsed.manifest_digest != release_manifest.digest: finish('CONFLICT docker-manifest-identity')",
        "    checked=validate_release_manifest(state_descriptor,record_name,expected_owner,expected_nonce,parsed.manifest,parsed.manifest_digest); os.close(checked[0])",
        "def bind_release_manifest():",
        "    global release_manifest,release_manifest_descriptor",
        "    if release_manifest is None:",
        "        opened=create_release_manifest(state_descriptor,record_name,expected_owner,expected_nonce,docker_descriptor,colima_descriptor); release_manifest_descriptor=opened[0]; release_manifest=opened[1]",
        "    return release_manifest",
        "def load_bound_release_manifest(parsed):",
        "    global release_manifest,release_manifest_descriptor",
        "    opened=validate_release_manifest(state_descriptor,record_name,expected_owner,expected_nonce,parsed.manifest,parsed.manifest_digest)",
        "    if release_manifest_descriptor is not None: os.close(release_manifest_descriptor)",
        "    release_manifest_descriptor=opened[0]; release_manifest=opened[1]",
        "def transition(source_descriptor,source,target_state):",
        "    manifest=bind_release_manifest()",
        "    if source.state != 'managed': load_bound_release_manifest(source); manifest=release_manifest",
        "    elif manifest.entries != ownership_manifest(docker_descriptor,colima_descriptor): finish('CONFLICT docker-manifest-drift')",
        "    path,target=create_transition_stage(record_name,state_descriptor,target_state,expected_owner,expected_nonce,expected_acquire_invocation,expected_machine,expected_epoch,expected_context,expected_lock,expected_docker,expected_colima,expected_disk,expected_wall,expected_artifacts,state_chain,expected_cleanup_invocation,expected_record,manifest.identity,manifest.digest,expected_chain)",
        "    promote_transition(record_name,state_descriptor,source_descriptor,source,(path,target,1),state_chain,lock_descriptor,lock_path,expected_lock)",
        "    opened=open_record_retained(state_descriptor,record_name)",
        "    if opened is None: finish('FAILED record-missing')",
        "    return opened",
        "def require_same_machine(current):",
        "    if not exact_wall(current,expected_cpu,expected_memory,expected_data): finish('CONFLICT wall-mismatch')",
        "    if type(current.get('status')) is not str or current.get('status').lower() != 'running': finish('UNSUPPORTED stable-identity')",
        "    machine,epoch_value=read_machine(command,profile)",
        "    if machine != expected_machine or epoch_value != expected_epoch: finish('CONFLICT identity-'+machine)",
        "bound_artifacts=None",
        "def bind_exact_artifacts():",
        "    global bound_artifacts,state_chain",
        "    if bound_artifacts is None:",
        "        observed=observe_profile_artifacts(command,lima,profile,os.environ.get('COLIMA_HOME',''),colima_descriptor,expected_wall)",
        "        if observed is None or observed.disk != expected_disk or observed.digest != expected_artifacts: finish('CONFLICT disk-identity')",
        "        state_chain.extend(observed.chain); validate_chain_identity(state_chain,expected_chain); bound_artifacts=observed",
        "    validate_artifact_entries(bound_artifacts.entries); return bound_artifacts",
        "def release_artifact_binding():",
        "    global bound_artifacts,state_chain",
        "    if bound_artifacts is None: return []",
        "    artifact_chain=bound_artifacts.chain; close_artifact_entries(bound_artifacts.entries)",
        "    for entry in reversed(artifact_chain): os.close(entry[1])",
        "    state_chain=[entry for entry in state_chain if entry not in artifact_chain]; bound_artifacts=None; return artifact_chain",
        "def finish_released(record_descriptor,parsed,stages,outcome):",
        "    validate_release_authority(parsed); load_bound_release_manifest(parsed)",
        "    marker_descriptor,marker=publish_released_marker(record_name,state_descriptor,record_descriptor,parsed); validate_release_authority(marker)",
        "    if test_crash == 'after-released-marker': os.kill(os.getpid(),signal.SIGKILL)",
        "    anchor=stages.get('reserved')",
        "    if anchor is None or anchor[1].nonce != expected_nonce or anchor[1].owner != expected_owner or anchor[1].invocation != expected_acquire_invocation: finish('CONFLICT reserved-anchor')",
        "    unlink_parsed_record(state_descriptor,anchor[0],anchor[1])",
        "    unlink_release_manifest(state_descriptor,record_name,release_manifest_descriptor,release_manifest); os.close(marker_descriptor); finish(outcome)",
        "final,stages=load_protocol_state(record_name,state_descriptor,expected_owner,expected_acquire_invocation,docker_descriptor)",
        "if final is None:",
        "    marker=open_record_retained(state_descriptor,released_marker_name(record_name),(1,))",
        "    if marker is None or docker_descriptor is not None or colima_descriptor is not None: finish('CONFLICT record-missing')",
        "    validate_authority(marker[1])",
        "    if marker[1].state != 'released': finish('CONFLICT released-marker')",
        "    old_manifest=open_release_manifest(state_descriptor,record_name,expected_owner,expected_nonce)",
        "    if old_manifest is not None:",
        "        if old_manifest[1].identity != marker[1].manifest or old_manifest[1].digest != marker[1].manifest_digest: finish('CONFLICT docker-manifest-identity')",
        "        unlink_release_manifest(state_descriptor,record_name,old_manifest[0],old_manifest[1])",
        "    os.close(marker[0]); finish('RELEASED')",
        "record_descriptor,parsed=final; validate_authority(parsed); outcome='RELEASED'",
        "if parsed.state in ('releasing','context-released','released'): load_bound_release_manifest(parsed)",
        "if parsed.state in ('reserved','home-staged','home-ready','context-staged','prepared'): finish('CONFLICT record-not-managed')",
        "if parsed.state == 'managed':",
        "    if docker_descriptor is None or colima_descriptor is None: finish('CONFLICT namespace-identity')",
        "    validate_colima_home_marker(colima_descriptor,expected_owner,expected_nonce,expected_colima)",
        "    current=observe()",
        "    if current is not None: require_same_machine(current)",
        "    if current is None: finish('CONFLICT managed-profile-absent')",
        "    bind_exact_artifacts()",
        "    if context_fingerprint(command,docker,'colima-'+profile,docker_descriptor) != expected_context: finish('CONFLICT docker-context-identity')",
        "    old_manifest=open_release_manifest(state_descriptor,record_name,expected_owner,expected_nonce)",
        "    if old_manifest is not None and old_manifest[1].entries != ownership_manifest(docker_descriptor,colima_descriptor):",
        "        pending=stages.get('releasing')",
        "        if pending is not None: unlink_parsed_record(state_descriptor,pending[0],pending[1]); stages.pop('releasing')",
        "        unlink_release_manifest(state_descriptor,record_name,old_manifest[0],old_manifest[1]); old_manifest=None",
        "    bind_release_manifest(); pending=stages.get('releasing')",
        "    if set(stages)-{'reserved','releasing'}: finish('CONFLICT stage-state')",
        "    if pending is not None:",
        "        validate_release_authority(pending[1]); promote_transition(record_name,state_descriptor,record_descriptor,parsed,pending,state_chain,lock_descriptor,lock_path,expected_lock)",
        "        final=open_record_retained(state_descriptor,record_name); record_descriptor,parsed=final",
        "    else: final=transition(record_descriptor,parsed,'releasing'); record_descriptor,parsed=final",
        "    validate_release_authority(parsed)",
        "if parsed.state == 'releasing':",
        "    if set(stages)-{'reserved','context-released','releasing'}: finish('CONFLICT stage-state')",
        "    load_bound_release_manifest(parsed); validate_release_authority(parsed)",
        "    current=observe()",
        "    if current is not None:",
        "        if docker_descriptor is None or colima_descriptor is None: finish('CONFLICT namespace-identity')",
        "        require_same_machine(current); artifacts=bind_exact_artifacts()",
        "        if context_fingerprint(command,docker,'colima-'+profile,docker_descriptor) != expected_context: finish('CONFLICT docker-context-identity')",
        "        artifact_chain=artifacts.chain; post_chain=[entry for entry in state_chain if entry not in artifact_chain]",
        "        deleted=delete_command([colima,'delete','--profile',profile,'--force','--data'],post_chain)",
        "        if deleted.returncode != 0: finish('FAILED delete')",
        "        release_artifact_binding(); state_chain=post_chain",
        "        if observe() is not None: finish('FAILED settle-present')",
        "        outcome='DELETED'",
        "    else: outcome='RELEASED'",
        "    residual=observe_profile_artifacts(command,lima,profile,os.environ.get('COLIMA_HOME',''),colima_descriptor)",
        "    if residual is not None or not profile_artifacts_absent(colima_descriptor,profile): finish('CONFLICT residual-profile-data')",
        "    remove_exact_context(command,docker,'colima-'+profile,docker_descriptor,expected_context)",
        "    if not manifest_allows_current(release_manifest,docker_descriptor,colima_descriptor): finish('CONFLICT namespace-manifest-drift')",
        "    pending=stages.get('context-released')",
        "    if pending is not None:",
        "        validate_release_authority(pending[1]); promote_transition(record_name,state_descriptor,record_descriptor,parsed,pending,state_chain,lock_descriptor,lock_path,expected_lock)",
        "        final=open_record_retained(state_descriptor,record_name); record_descriptor,parsed=final",
        "    else: final=transition(record_descriptor,parsed,'context-released'); record_descriptor,parsed=final",
        "    validate_release_authority(parsed)",
        "if parsed.state == 'context-released':",
        "    if set(stages)-{'reserved','released','context-released'}: finish('CONFLICT stage-state')",
        "    load_bound_release_manifest(parsed); validate_release_authority(parsed)",
        "    if observe() is not None: finish('CONFLICT released-profile-present')",
        "    if colima_descriptor is not None:",
        "        residual=observe_profile_artifacts(command,lima,profile,os.environ.get('COLIMA_HOME',''),colima_descriptor)",
        "        if residual is not None or not profile_artifacts_absent(colima_descriptor,profile): finish('CONFLICT residual-profile-data')",
        "    if docker_descriptor is not None:",
        "        if named_context_present(command,docker,'colima-'+profile): finish('CONFLICT docker-context-present')",
        "    if not manifest_allows_current(release_manifest,docker_descriptor,colima_descriptor): finish('CONFLICT namespace-manifest-drift')",
        "    if docker_descriptor is not None:",
        "        state_chain=remove_docker_namespace(state_directory,state_descriptor,record_name,docker_descriptor,expected_docker,state_chain,lock_descriptor,lock_path,expected_lock,release_manifest.entries); docker_descriptor=None",
        "    if colima_descriptor is not None:",
        "        state_chain=remove_colima_namespace(os.environ.get('COLIMA_HOME',''),colima_descriptor,expected_colima,state_chain,lock_descriptor,lock_path,expected_lock,release_manifest.entries); colima_descriptor=None",
        "    pending=stages.get('released')",
        "    if pending is not None:",
        "        validate_release_authority(pending[1]); promote_transition(record_name,state_descriptor,record_descriptor,parsed,pending,state_chain,lock_descriptor,lock_path,expected_lock)",
        "        final=open_record_retained(state_descriptor,record_name); record_descriptor,parsed=final",
        "    else: final=transition(record_descriptor,parsed,'released'); record_descriptor,parsed=final",
        "    finish_released(record_descriptor,parsed,stages,outcome)",
        "if parsed.state == 'released':",
        "    if set(stages)-{'reserved'} or docker_descriptor is not None or colima_descriptor is not None: finish('CONFLICT released-state')",
        "    finish_released(record_descriptor,parsed,stages,'RELEASED')",
        "finish('CONFLICT record-state')"
      ]
