module HostBootstrap.Ensure.Colima.Backend.Program.Common
  ( commonProgram,
  )
where

import HostBootstrap.Ensure.Colima.Backend.Program.Context (contextProgram)
import HostBootstrap.Ensure.Colima.Backend.Program.Filesystem (filesystemProgram)
import HostBootstrap.Ensure.Colima.Backend.Program.Namespace (namespaceProgram)
import HostBootstrap.Ensure.Colima.Backend.Program.Supervisor (commandSupervisorProgram)

-- The embedded program is deliberately split from the acquire and cleanup
-- entry points.  One Python process owns every descriptor in the bracket: the
-- flock descriptor, the root-to-leaf state-directory chain, the isolated
-- Docker-config directory, and any origin/stage record being transitioned.
commonProgram :: [String]
commonProgram =
  ["import ctypes,errno,fcntl,hashlib,json,os,re,secrets,selectors,signal,stat,subprocess,sys,threading,time,types"]
    ++ filesystemProgram
    ++ namespaceProgram
    ++ [
    "def valid_nonce(value): return re.fullmatch(r'[0-9a-f]{64}',value) is not None",
    "def valid_machine(value): return re.fullmatch(r'[0-9a-f]{32}',value) is not None",
    "def valid_owner(value):",
    "    matched=re.fullmatch(r'v2-(?:[0-9a-f]+-){6}([1-9][0-9]*)-(?:[0-9a-f]+-){3}[0-9a-f]+',value)",
    "    return len(value) <= 4096 and matched is not None and int(matched.group(1)) < uint64_limit",
    "def uint(value,positive=False):",
    "    if not isinstance(value,str) or re.fullmatch(r'(?:0|[1-9][0-9]*)',value) is None: return None",
    "    number=int(value)",
    "    if number >= uint64_limit or (positive and number == 0): return None",
    "    return number",
    "command_supervisor_program=" ++ show commandSupervisorProgram,
    "active_process=None",
    "command_output_limit=16*1024*1024",
    "class CommandDeadline(Exception): pass",
    "class CommandOutputLimit(Exception): pass",
    "def close_process_pipes(process):",
    "    for stream in (process.stdin,process.stdout,process.stderr):",
    "        if stream is not None:",
    "            try: stream.close()",
    "            except OSError: pass",
    "def terminate_process_group(process):",
    "    try: os.killpg(process.pid,signal.SIGTERM)",
    "    except ProcessLookupError: pass",
    "    try: process.wait(timeout=3)",
    "    except subprocess.TimeoutExpired:",
    "        try: os.killpg(process.pid,signal.SIGKILL)",
    "        except ProcessLookupError: pass",
    "        try: process.wait(timeout=2)",
    "        except subprocess.TimeoutExpired: pass",
    "    close_process_pipes(process)",
    "def collect_process_output(process,timeout_seconds):",
    "    selected=selectors.DefaultSelector(); chunks=[[],[]]; total=0; deadline=time.monotonic()+timeout_seconds",
    "    try:",
    "        for index,stream in enumerate((process.stdout,process.stderr)):",
    "            os.set_blocking(stream.fileno(),False); selected.register(stream,selectors.EVENT_READ,index)",
    "        while selected.get_map():",
    "            remaining=deadline-time.monotonic()",
    "            if remaining <= 0: raise CommandDeadline()",
    "            for key,_events in selected.select(min(remaining,0.2)):",
    "                try: chunk=os.read(key.fileobj.fileno(),16384)",
    "                except BlockingIOError: continue",
    "                if chunk:",
    "                    total += len(chunk)",
    "                    if total > command_output_limit: raise CommandOutputLimit()",
    "                    chunks[key.data].append(chunk)",
    "                else: selected.unregister(key.fileobj)",
    "        remaining=deadline-time.monotonic()",
    "        if remaining <= 0: raise CommandDeadline()",
    "        try: returncode=process.wait(timeout=remaining)",
    "        except subprocess.TimeoutExpired: raise CommandDeadline()",
    "        return returncode,b''.join(chunks[0]),b''.join(chunks[1])",
    "    finally: selected.close()",
    "def stop_active_process(_signal,_frame):",
    "    global active_process",
    "    if active_process is not None:",
    "        process=active_process; active_process=None; terminate_process_group(process)",
    "    raise SystemExit(128)",
    "signal.signal(signal.SIGTERM,stop_active_process); signal.signal(signal.SIGINT,stop_active_process)",
    "def bounded_command(stage,args,timeout_seconds,lock_descriptor,lock_path,state_chain,lock_expected=None,post_state_chain=None):",
    "    global active_process",
    "    validate_lock(lock_descriptor,lock_path,lock_expected); validate_state_chain(state_chain)",
    "    supervised=[sys.executable,'-I','-S','-c',command_supervisor_program]+args",
    "    try: active_process=subprocess.Popen(supervised,stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE,pass_fds=(lock_descriptor,),start_new_session=True)",
    "    except OSError: finish('FAILED launch-'+stage)",
    "    try: returncode,out_bytes,err_bytes=collect_process_output(active_process,timeout_seconds)",
    "    except CommandDeadline:",
    "        process=active_process; active_process=None; terminate_process_group(process); finish('FAILED timeout-'+stage)",
    "    except CommandOutputLimit:",
    "        process=active_process; active_process=None; terminate_process_group(process); finish('FAILED output-limit-'+stage)",
    "    process=active_process; active_process=None; close_process_pipes(process)",
    "    try: out=out_bytes.decode('utf-8'); err=err_bytes.decode('utf-8')",
    "    except UnicodeDecodeError: finish('FAILED output-encoding-'+stage)",
    "    validate_lock(lock_descriptor,lock_path,lock_expected); validate_state_chain(state_chain if post_state_chain is None else post_state_chain)",
    "    return types.SimpleNamespace(returncode=returncode,stdout=out,stderr=err)",
    "def write_all(descriptor,data):",
    "    offset=0",
    "    while offset < len(data):",
    "        written=os.write(descriptor,data[offset:])",
    "        if written <= 0: finish('FAILED record-write')",
    "        offset += written",
    "def read_descriptor(descriptor):",
    "    os.lseek(descriptor,0,os.SEEK_SET); chunks=[]; total=0",
    "    while True:",
    "        chunk=os.read(descriptor,1024)",
    "        if not chunk: return b''.join(chunks)",
    "        total += len(chunk)",
    "        if total > 8192: finish('CONFLICT record-size')",
    "        chunks.append(chunk)",
    "def read_owned_content(descriptor):",
    "    os.lseek(descriptor,0,os.SEEK_SET); chunks=[]; total=0",
    "    while True:",
    "        chunk=os.read(descriptor,16384)",
    "        if not chunk: return b''.join(chunks)",
    "        total += len(chunk)",
    "        if total > 16*1024*1024: finish('CONFLICT docker-file-size')",
    "        chunks.append(chunk)",
    "def optional_identity_text(value): return 'absent' if value is None else identity_text(value)",
    "def wall_text(value): return 'absent' if value is None else ':'.join(str(part) for part in value)",
    "def parse_wall(value):",
    "    if value == 'absent': return None",
    "    parts=[uint(part,True) for part in value.split(':')]",
    "    return None if len(parts) != 4 or any(part is None for part in parts) else tuple(parts)",
    "def chain_identity(chain): return tuple(identity(os.fstat(entry[1])) for entry in chain)",
    "def chain_text(chain): return ','.join(identity_text(value) for value in chain_identity(chain))",
    "def validate_chain_identity(chain,expected):",
    "    validate_state_chain(chain)",
    "    if chain_identity(chain) != tuple(expected): finish('CONFLICT state-chain-identity')",
    "def validate_surviving_chain(chain,expected):",
    "    validate_state_chain(chain); observed=chain_identity(chain)",
    "    if len(observed) > len(expected) or observed != tuple(expected[:len(observed)]): finish('CONFLICT state-chain-identity')",
    "def parse_chain(value):",
    "    if value == '': return None",
    "    parsed=[parse_pair(part) for part in value.split(',')]",
    "    return None if any(part is None for part in parsed) else tuple(parsed)",
    "def record_bytes(state,owner,nonce,invocation,machine,epoch_value,context,lock_identity,docker_identity,colima_identity,disk_identity,wall_value,artifacts_digest,chain_identity,record_identity,cleanup_invocation=None,managed_identity=None,manifest_identity=None,manifest_digest=None):",
    "    values=['version 3','state '+state,'owner '+owner,'nonce '+nonce,'invocation '+invocation,'machine '+machine,'epoch '+epoch_value,'context '+context,'lock '+identity_text(lock_identity),'docker '+optional_identity_text(docker_identity),'colima '+optional_identity_text(colima_identity),'disk '+optional_identity_text(disk_identity),'wall '+wall_text(wall_value),'artifacts '+('absent' if artifacts_digest is None else artifacts_digest),'chain '+','.join(identity_text(value) for value in chain_identity),'record '+identity_text(record_identity)]",
    "    if cleanup_invocation is not None: values.append('cleanup '+cleanup_invocation)",
    "    if managed_identity is not None: values.append('managed '+identity_text(managed_identity))",
    "    if manifest_identity is not None and manifest_digest is not None: values.append('manifest '+identity_text(manifest_identity)+':'+manifest_digest)",
    "    return ('\\n'.join(values)+'\\n').encode('ascii')",
    "def parse_pair(value):",
    "    fields=value.split(':')",
    "    if len(fields) != 2: return None",
    "    left=uint(fields[0]); right=uint(fields[1],True)",
    "    return None if left is None or right is None else (left,right)",
    "def parse_record(data,actual_identity):",
    "    try: lines=data.decode('ascii').splitlines()",
    "    except Exception: return None",
    "    if len(lines) not in (16,19) or lines[0] != 'version 3': return None",
    "    names=['state','owner','nonce','invocation','machine','epoch','context','lock','docker','colima','disk','wall','artifacts','chain','record']",
    "    values={}",
    "    for name,line in zip(names,lines[1:16]):",
    "        prefix=name+' '",
    "        if not line.startswith(prefix): return None",
    "        values[name]=line[len(prefix):]",
    "    state=values['state']; owner=values['owner']; nonce=values['nonce']; invocation=values['invocation']",
    "    if state not in ('reserved','home-staged','home-ready','context-staged','prepared','managed','releasing','context-released','released') or not valid_owner(owner) or not valid_nonce(nonce) or not valid_nonce(invocation): return None",
    "    lock_identity=parse_pair(values['lock']); docker_identity=None if values['docker'] == 'absent' else parse_pair(values['docker']); colima_identity=None if values['colima'] == 'absent' else parse_pair(values['colima']); disk_identity=None if values['disk'] == 'absent' else parse_pair(values['disk']); wall_value=parse_wall(values['wall']); artifacts_digest=None if values['artifacts'] == 'absent' else values['artifacts']; chain_identity=parse_chain(values['chain']); recorded_identity=parse_pair(values['record'])",
    "    if lock_identity is None or chain_identity is None or recorded_identity != actual_identity: return None",
    "    cleanup_invocation=None; managed_identity=None; manifest_identity=None; manifest_digest=None",
    "    if state in ('releasing','context-released','released'):",
    "        if len(lines) != 19 or not lines[16].startswith('cleanup ') or not lines[17].startswith('managed ') or not lines[18].startswith('manifest '): return None",
    "        cleanup_invocation=lines[16][8:]",
    "        if not valid_nonce(cleanup_invocation): return None",
    "        managed_identity=parse_pair(lines[17][8:])",
    "        manifest_fields=lines[18][9:].split(':')",
    "        if len(manifest_fields) != 3 or re.fullmatch(r'[0-9a-f]{64}',manifest_fields[2]) is None: return None",
    "        manifest_identity=parse_pair(':'.join(manifest_fields[:2])); manifest_digest=manifest_fields[2]",
    "        if managed_identity is None or manifest_identity is None: return None",
    "    elif len(lines) != 16: return None",
    "    machine=values['machine']; epoch_value=values['epoch']; context=values['context']",
    "    if state in ('reserved','home-staged','home-ready','context-staged','prepared'):",
    "        if machine != 'absent' or epoch_value != 'absent' or context != 'absent' or disk_identity is not None or wall_value is not None or artifacts_digest is not None: return None",
    "        if state == 'reserved' and (docker_identity is not None or colima_identity is not None): return None",
    "        if state in ('home-staged','home-ready') and (docker_identity is not None or colima_identity is None): return None",
    "        if state in ('context-staged','prepared') and (docker_identity is None or colima_identity is None): return None",
    "    else:",
    "        if docker_identity is None or colima_identity is None or disk_identity is None or wall_value is None or re.fullmatch(r'[0-9a-f]{64}',artifacts_digest or '') is None or not valid_machine(machine) or uint(epoch_value,True) is None or re.fullmatch(r'[0-9a-f]{64}',context) is None: return None",
    "    canonical=record_bytes(state,owner,nonce,invocation,machine,epoch_value,context,lock_identity,docker_identity,colima_identity,disk_identity,wall_value,artifacts_digest,chain_identity,recorded_identity,cleanup_invocation,managed_identity,manifest_identity,manifest_digest)",
    "    if canonical != data: return None",
    "    return types.SimpleNamespace(state=state,owner=owner,nonce=nonce,invocation=invocation,cleanup=cleanup_invocation,machine=machine,epoch=None if epoch_value == 'absent' else int(epoch_value),context=context,lock=lock_identity,docker=docker_identity,colima=colima_identity,disk=disk_identity,wall=wall_value,artifacts=artifacts_digest,chain=chain_identity,record=recorded_identity,managed=managed_identity,manifest=manifest_identity,manifest_digest=manifest_digest,data=data)",
    "def open_record_retained(directory,path,links=(1,2,3)):",
    "    try: descriptor=os.open(path,os.O_RDONLY|nofollow,dir_fd=directory)",
    "    except FileNotFoundError: return None",
    "    except OSError: finish('CONFLICT record-open')",
    "    opened=os.fstat(descriptor); validate_file(opened,'CONFLICT',links)",
    "    try: path_info=stat_at(directory,path)",
    "    except OSError: finish('CONFLICT record-path')",
    "    if identity(opened) != identity(path_info): finish('CONFLICT record-identity')",
    "    data=read_descriptor(descriptor); parsed=parse_record(data,identity(opened))",
    "    if parsed is None: finish('CONFLICT record-format')",
    "    after=os.fstat(descriptor)",
    "    if identity(after) != identity(opened): finish('CONFLICT record-identity')",
    "    return descriptor,parsed",
    "def unlink_parsed_record(directory,path,parsed,links=(1,)):",
    "    opened=open_record_retained(directory,path,links)",
    "    if opened is None: finish('CONFLICT record-path')",
    "    descriptor,current=opened; info=os.fstat(descriptor)",
    "    if current.record != parsed.record or current.data != parsed.data or identity(info) != parsed.record or info.st_nlink not in links: finish('CONFLICT record-changed')",
    "    path_info=stat_at(directory,path)",
    "    if identity(path_info) != parsed.record: finish('CONFLICT record-identity')",
    "    os.unlink(path,dir_fd=directory); sync_directory_fd(directory); os.close(descriptor)",
    "def exact_unlink(directory,path,expected_identity,sync=True):",
    "    try: observed=stat_at(directory,path)",
    "    except OSError: finish('CONFLICT record-path')",
    "    if identity(observed) != expected_identity: finish('CONFLICT record-identity')",
    "    os.unlink(path,dir_fd=directory)",
    "    if sync: sync_directory_fd(directory)",
    "def stage_path(record,state,nonce): return record+'.'+state+'.'+nonce+'.stage'",
    "def stage_header(state,owner,nonce,invocation): return ('version 3\\nstate '+state+'\\nowner '+owner+'\\nnonce '+nonce+'\\ninvocation '+invocation+'\\n').encode('ascii')",
    "def write_stage(directory,path,builder):",
    "    try: descriptor=os.open(path,os.O_RDWR|os.O_CREAT|os.O_EXCL|nofollow,0o600,dir_fd=directory)",
    "    except FileExistsError: finish('CONFLICT stage-present')",
    "    except OSError as error:",
    "        if error.errno in (errno.EINVAL,errno.ENOTSUP,getattr(errno,'EOPNOTSUPP',errno.ENOTSUP)): finish('UNSUPPORTED stage-create')",
    "        finish('FAILED stage-create')",
    "    try:",
    "        info=os.fstat(descriptor); validate_file(info,'FAILED'); expected_identity=identity(info); data=builder(expected_identity)",
    "        write_all(descriptor,data); os.fsync(descriptor)",
    "        if identity(os.fstat(descriptor)) != expected_identity: finish('FAILED stage-identity')",
    "        observed=read_descriptor(descriptor)",
    "        if observed != data: finish('FAILED stage-readback')",
    "    finally: os.close(descriptor)",
    "    path_info=stat_at(directory,path)",
    "    if identity(path_info) != expected_identity: finish('FAILED stage-identity')",
    "    return expected_identity,data",
    "def load_protocol_state(record,directory,owner,invocation,docker_descriptor=None):",
    "    final=open_record_retained(directory,record); stages={}",
    "    pattern=re.compile(re.escape(record)+r'\\.(reserved|home-staged|home-ready|context-staged|prepared|managed|releasing|context-released|released)\\.([0-9a-f]{64})\\.stage')",
    "    try: names=os.listdir(directory)",
    "    except OSError: finish('UNSUPPORTED state-list')",
    "    for name in names:",
    "        matched=pattern.fullmatch(name)",
    "        if matched is None: continue",
    "        state,nonce=matched.groups()",
    "        try: descriptor=os.open(name,os.O_RDONLY|nofollow,dir_fd=directory)",
    "        except OSError: finish('CONFLICT stage-open')",
    "        info=os.fstat(descriptor); validate_file(info,'CONFLICT',(1,2,3)); stage_identity=identity(info); data=read_descriptor(descriptor); os.close(descriptor)",
    "        path_info=stat_at(directory,name)",
    "        if identity(path_info) != stage_identity: finish('CONFLICT stage-identity')",
    "        parsed=parse_record(data,stage_identity)",
    "        if parsed is None:",
    "            if stage_header(state,owner,nonce,invocation).startswith(data) and info.st_nlink == 1: exact_unlink(directory,name,stage_identity)",
    "            else: finish('CONFLICT stage-content')",
    "            continue",
    "        if parsed.state != state or parsed.nonce != nonce or parsed.owner != owner or parsed.invocation != invocation: finish('CONFLICT stage-content')",
    "        if state in stages: finish('CONFLICT duplicate-stage')",
    "        stages[state]=(name,parsed,info.st_nlink)",
    "    if final is None:",
    "        if set(stages) == {'reserved'} and stages['reserved'][2] == 1:",
    "            unlink_parsed_record(directory,stages['reserved'][0],stages['reserved'][1]); stages={} ",
    "        elif stages: finish('CONFLICT orphan-stage')",
    "        return None,stages",
    "    descriptor,parsed=final",
    "    if parsed.owner != owner or parsed.invocation != invocation: finish('CONFLICT owner-mismatch')",
    "    link_count=os.fstat(descriptor).st_nlink",
    "    anchor=stages.get('reserved')",
    "    if parsed.state == 'reserved':",
    "        if link_count != 2 or anchor is None or anchor[1].record != parsed.record or anchor[1].data != parsed.data or anchor[2] != 2: finish('CONFLICT reserved-anchor')",
    "    else:",
    "        if link_count != 1 or anchor is None or anchor[1].nonce != parsed.nonce or anchor[1].owner != parsed.owner or anchor[2] != 1: finish('CONFLICT reserved-anchor')",
    "        sync_directory_fd(directory)",
    "    return final,stages",
    "def publish_reserved(record,directory,owner,nonce,invocation,lock_identity,state_chain):",
    "    stage=stage_path(record,'reserved',nonce)",
    "    stage_identity,data=write_stage(directory,stage,lambda record_identity: record_bytes('reserved',owner,nonce,invocation,'absent','absent','absent',lock_identity,None,None,None,None,None,chain_identity(state_chain),record_identity))",
    "    try: os.link(stage,record,src_dir_fd=directory,dst_dir_fd=directory,follow_symlinks=False)",
    "    except FileExistsError: finish('CONFLICT record-present')",
    "    except OSError as error:",
    "        if error.errno in (errno.EINVAL,errno.ENOTSUP,getattr(errno,'EOPNOTSUPP',errno.ENOTSUP)): finish('UNSUPPORTED record-publish')",
    "        finish('FAILED record-publish')",
    "    sync_directory_fd(directory)",
    "    opened=open_record_retained(directory,record)",
    "    if opened is None or opened[1].record != stage_identity or opened[1].data != data or os.fstat(opened[0]).st_nlink != 2: finish('FAILED record-publish-readback')",
    "    os.close(opened[0]); return stage_identity",
    "def context_stage_name(record,nonce): return record+'.docker.'+nonce+'.stage'",
    "def create_context_stage(state,state_descriptor,record,nonce,docker_config,expected_identity=None):",
    "    target=record+'.docker'",
    "    if docker_config != os.path.join(state,target): finish('UNSUPPORTED docker-namespace')",
    "    try: stat_at(state_descriptor,target); finish('CONFLICT docker-namespace-present')",
    "    except FileNotFoundError: pass",
    "    stage=context_stage_name(record,nonce)",
    "    try: stage_path_value,stage_descriptor,created=open_child(state,state_descriptor,stage,True)",
    "    except Exception: raise",
    "    if not created and expected_identity is not None and identity(os.fstat(stage_descriptor)) != expected_identity: finish('CONFLICT docker-stage-unbound')",
    "    if os.listdir(stage_descriptor): finish('CONFLICT docker-stage-content')",
    "    sync_directory_fd(stage_descriptor); sync_directory_fd(state_descriptor)",
    "    return stage_path_value,stage_descriptor,identity(os.fstat(stage_descriptor))",
    "def publish_context_target(state,state_descriptor,record,nonce,docker_config,expected_identity):",
    "    target=record+'.docker'; stage=context_stage_name(record,nonce)",
    "    if docker_config != os.path.join(state,target): finish('UNSUPPORTED docker-namespace')",
    "    try: stage_info=stat_at(state_descriptor,stage)",
    "    except FileNotFoundError: stage_info=None",
    "    except OSError: finish('CONFLICT docker-stage')",
    "    try: target_info=stat_at(state_descriptor,target)",
    "    except FileNotFoundError: target_info=None",
    "    except OSError: finish('CONFLICT docker-namespace')",
    "    if stage_info is not None and target_info is None:",
    "        if identity(stage_info) != expected_identity: finish('CONFLICT docker-stage-identity')",
    "        rename_exclusive(state_descriptor,stage,target); sync_directory_fd(state_descriptor)",
    "        target_info=stat_at(state_descriptor,target)",
    "    elif stage_info is not None or target_info is None: finish('CONFLICT docker-publish-state')",
    "    if identity(target_info) != expected_identity: finish('CONFLICT docker-identity')",
    "    docker_path=os.path.join(state,target); docker_descriptor=os.open(target,os.O_RDONLY|odirectory|nofollow,dir_fd=state_descriptor)",
    "    opened=os.fstat(docker_descriptor); validate_directory(opened,'CONFLICT')",
    "    if identity(opened) != expected_identity: finish('CONFLICT docker-identity')",
    "    return docker_path,docker_descriptor,expected_identity",
    "def create_transition_stage(record,directory,state,owner,nonce,invocation,machine,epoch_value,context,lock_identity,docker_identity,colima_identity,disk_identity,wall_value,artifacts_digest,state_chain,cleanup_invocation=None,managed_identity=None,manifest_identity=None,manifest_digest=None,authority_chain=None):",
    "    path=stage_path(record,state,nonce)",
    "    retained_chain=chain_identity(state_chain) if authority_chain is None else tuple(authority_chain)",
    "    stage_identity,data=write_stage(directory,path,lambda record_identity: record_bytes(state,owner,nonce,invocation,machine,str(epoch_value),context,lock_identity,docker_identity,colima_identity,disk_identity,wall_value,artifacts_digest,retained_chain,record_identity,cleanup_invocation,managed_identity,manifest_identity,manifest_digest))",
    "    return path,parse_record(data,stage_identity)",
    "def promote_transition(record,directory,source_descriptor,source,stage_entry,state_chain,lock_descriptor,lock_path,lock_expected):",
    "    stage_name,target,_links=stage_entry",
    "    validate_lock(lock_descriptor,lock_path,lock_expected); validate_state_chain(state_chain)",
    "    opened=os.fstat(source_descriptor); validate_file(opened,'CONFLICT',(1,2,3))",
    "    if identity(opened) != source.record or read_descriptor(source_descriptor) != source.data: finish('CONFLICT record-changed')",
    "    path_info=stat_at(directory,record)",
    "    if identity(path_info) != source.record: finish('CONFLICT record-identity')",
    "    stage_info=stat_at(directory,stage_name)",
    "    if identity(stage_info) != target.record or stage_info.st_nlink != 1: finish('CONFLICT stage-identity')",
    "    os.replace(stage_name,record,src_dir_fd=directory,dst_dir_fd=directory); sync_directory_fd(directory)",
    "    observed=open_record_retained(directory,record)",
    "    if observed is None or observed[1].data != target.data or observed[1].record != target.record: finish('FAILED record-transition')",
    "    os.close(observed[0]); os.close(source_descriptor)",
    "    validate_lock(lock_descriptor,lock_path,lock_expected); validate_state_chain(state_chain)",
    "    return target.record",
    "def unlink_open_record(record,directory,descriptor,parsed):",
    "    opened=os.fstat(descriptor); validate_file(opened,'CONFLICT',(1,))",
    "    if identity(opened) != parsed.record or read_descriptor(descriptor) != parsed.data: finish('CONFLICT record-changed')",
    "    path_info=stat_at(directory,record)",
    "    if identity(path_info) != parsed.record: finish('CONFLICT record-identity')",
    "    os.unlink(record,dir_fd=directory); sync_directory_fd(directory); os.close(descriptor)",
    "def released_marker_name(record): return record+'.released'",
    "def publish_released_marker(record,directory,descriptor,parsed):",
    "    marker=released_marker_name(record)",
    "    opened=os.fstat(descriptor); validate_file(opened,'CONFLICT',(1,))",
    "    if identity(opened) != parsed.record or read_descriptor(descriptor) != parsed.data: finish('CONFLICT record-changed')",
    "    try: stat_at(directory,marker); finish('CONFLICT released-marker-present')",
    "    except FileNotFoundError: pass",
    "    except OSError: finish('CONFLICT released-marker')",
    "    source_info=stat_at(directory,record)",
    "    if identity(source_info) != parsed.record: finish('CONFLICT record-identity')",
    "    os.rename(record,marker,src_dir_fd=directory,dst_dir_fd=directory); sync_directory_fd(directory)",
    "    marker_record=open_record_retained(directory,marker,(1,))",
    "    if marker_record is None or marker_record[1].state != 'released' or marker_record[1].record != parsed.record or marker_record[1].data != parsed.data: finish('FAILED released-marker')",
    "    os.close(descriptor); return marker_record",
    "def strict_colima_values(raw):",
    "    if raw.returncode != 0: finish('FAILED list')",
    "    if raw.stderr != '': finish('FAILED list-stderr')",
    "    if raw.stdout == '': return []",
    "    if '\\r' in raw.stdout or not raw.stdout.endswith('\\n') or raw.stdout == '\\n': finish('FAILED list-framing')",
    "    lines=raw.stdout[:-1].split('\\n')",
    "    if any(line == '' for line in lines): finish('FAILED list-framing')",
    "    try: values=[json.loads(line) for line in lines]",
    "    except Exception: finish('FAILED list-decode')",
    "    if any(not isinstance(value,dict) or type(value.get('name')) is not str or not value.get('name') or len(value.get('name')) > 255 or any(ord(character) < 33 or ord(character) > 126 for character in value.get('name')) for value in values): finish('FAILED list-shape')",
    "    if len({value['name'] for value in values}) != len(values): finish('CONFLICT list-duplicate')",
    "    return values",
    "def exact_wall(value,cpu,memory,disk):",
    "    return type(value.get('cpus')) is int and type(value.get('memory')) is int and type(value.get('disk')) is int and value.get('cpus') == cpu and value.get('memory') == memory and value.get('disk') == disk and type(value.get('runtime')) is str and value.get('runtime').lower() == 'docker'",
    "def read_machine(command,profile):",
    "    raw=command('identity',[colima,'ssh','--profile',profile,'--','cat','/etc/machine-id'])",
    "    if raw.returncode != 0 or raw.stderr != '' or re.fullmatch(r'[0-9a-f]{32}\\n',raw.stdout) is None: finish('FAILED identity-observe')",
    "    machine=raw.stdout[:-1]; value=14695981039346656037",
    "    for byte in machine.encode('ascii'): value=((value ^ byte)*1099511628211) & (uint64_limit-1)",
    "    return machine,(value if value != 0 else 1)"
  ]
    ++ contextProgram
