module HostBootstrap.Ensure.Colima.Backend.Program.Context
  ( contextProgram,
  )
where

-- Named Docker-context identity and conditional namespace release.  These
-- definitions execute in the same Python module as commonProgram.
contextProgram :: [String]
contextProgram =
  [ "def directory_manifest(descriptor,mutable=False):",
    "    entries=[]",
    "    def add(value): entries.append(value)",
    "    def walk(current,prefix):",
    "        try: names=sorted(os.listdir(current))",
    "        except OSError: finish('UNSUPPORTED docker-list')",
    "        for name in names:",
    "            if name in ('.','..') or os.sep in name: finish('CONFLICT docker-entry')",
    "            relative=prefix+name",
    "            try: info=stat_at(current,name)",
    "            except OSError: finish('CONFLICT docker-entry')",
    "            if info.st_uid != os.geteuid(): finish('CONFLICT docker-owner')",
    "            if stat.S_ISREG(info.st_mode):",
    "                if info.st_nlink != 1: finish('CONFLICT docker-links')",
    "                try: child=os.open(name,os.O_RDONLY|nofollow,dir_fd=current)",
    "                except OSError: finish('CONFLICT docker-file')",
    "                opened=os.fstat(child)",
    "                if not stat.S_ISREG(opened.st_mode) or opened.st_uid != os.geteuid() or opened.st_nlink != 1 or (stat.S_IMODE(opened.st_mode) & 0o022) != 0: finish('CONFLICT docker-file')",
    "                content=b'' if mutable else read_owned_content(child); os.close(child)",
    "                if identity(opened) != identity(info): finish('CONFLICT docker-file')",
    "                add(('m:' if mutable else 'f:')+relative+':'+identity_text(identity(info))+':'+oct(stat.S_IMODE(info.st_mode))+('' if mutable else ':'+hashlib.sha256(content).hexdigest()))",
    "            elif stat.S_ISDIR(info.st_mode):",
    "                try: child=os.open(name,os.O_RDONLY|odirectory|nofollow,dir_fd=current)",
    "                except OSError: finish('CONFLICT docker-directory')",
    "                opened=os.fstat(child); validate_directory(opened,'CONFLICT')",
    "                if identity(opened) != identity(info): finish('CONFLICT docker-directory')",
    "                add('d:'+relative+':'+identity_text(identity(info))+':'+oct(stat.S_IMODE(info.st_mode))); walk(child,relative+'/'); os.close(child)",
    "            elif stat.S_ISLNK(info.st_mode):",
    "                try: target=os.readlink(name,dir_fd=current)",
    "                except OSError: finish('CONFLICT docker-symlink')",
    "                add('l:'+relative+':'+identity_text(identity(info))+':'+oct(stat.S_IMODE(info.st_mode))+':'+os.fsencode(target).hex())",
    "            elif stat.S_ISSOCK(info.st_mode): add('s:'+relative+':'+identity_text(identity(info))+':'+oct(stat.S_IMODE(info.st_mode)))",
    "            else: finish('CONFLICT docker-entry-type')",
    "    walk(descriptor,''); return entries",
    "def directory_snapshot(descriptor):",
    "    digest=hashlib.sha256()",
    "    for entry in directory_manifest(descriptor): digest.update(entry.encode('utf-8')); digest.update(b'\\0')",
    "    return digest.hexdigest()",
    "def ownership_manifest(docker_descriptor,colima_descriptor):",
    "    docker_entries=[] if docker_descriptor is None else ['docker/'+entry for entry in directory_manifest(docker_descriptor)]",
    "    colima_entries=[] if colima_descriptor is None else ['colima/'+entry for entry in directory_manifest(colima_descriptor,True)]",
    "    return docker_entries+colima_entries",
    "def release_manifest_name(record): return record+'.release-manifest'",
    "def release_manifest_stage_name(record,nonce): return release_manifest_name(record)+'.'+nonce+'.stage'",
    "def release_manifest_header(owner,nonce,record_identity): return ('version 1\\nowner '+owner+'\\nnonce '+nonce+'\\nidentity '+identity_text(record_identity)+'\\n').encode('ascii')",
    "def release_manifest_bytes(owner,nonce,record_identity,entries):",
    "    data=release_manifest_header(owner,nonce,record_identity)+b'entries '+json.dumps(entries,separators=(',',':')).encode('ascii')+b'\\n'",
    "    if len(data) > 1024*1024: finish('CONFLICT docker-manifest-size')",
    "    return data",
    "def parse_release_manifest(data,actual_identity,owner,nonce):",
    "    try: lines=data.decode('ascii').splitlines()",
    "    except Exception: return None",
    "    expected=['version 1','owner '+owner,'nonce '+nonce,'identity '+identity_text(actual_identity)]",
    "    if len(lines) != 5 or lines[:4] != expected or not lines[4].startswith('entries '): return None",
    "    try: entries=json.loads(lines[4][8:])",
    "    except Exception: return None",
    "    if not isinstance(entries,list) or any(type(entry) is not str for entry in entries) or len(set(entries)) != len(entries): return None",
    "    canonical=release_manifest_bytes(owner,nonce,actual_identity,entries)",
    "    if canonical != data: return None",
    "    return types.SimpleNamespace(identity=actual_identity,digest=hashlib.sha256(data).hexdigest(),entries=entries,data=data)",
    "def open_manifest_entry(directory,name,owner,nonce,links=(1,2)):",
    "    try: descriptor=os.open(name,os.O_RDONLY|nofollow,dir_fd=directory)",
    "    except FileNotFoundError: return None",
    "    except OSError: finish('CONFLICT docker-manifest-open')",
    "    info=os.fstat(descriptor); validate_file(info,'CONFLICT',links); manifest_identity=identity(info); data=read_owned_content(descriptor)",
    "    path_info=stat_at(directory,name)",
    "    if identity(path_info) != manifest_identity: finish('CONFLICT docker-manifest-identity')",
    "    return descriptor,parse_release_manifest(data,manifest_identity,owner,nonce),data,manifest_identity",
    "def unlink_manifest_entry(directory,name,descriptor,expected_identity,expected_data,links):",
    "    info=os.fstat(descriptor); validate_file(info,'CONFLICT',links)",
    "    if identity(info) != expected_identity or read_owned_content(descriptor) != expected_data: finish('CONFLICT docker-manifest-changed')",
    "    path_info=stat_at(directory,name)",
    "    if identity(path_info) != expected_identity: finish('CONFLICT docker-manifest-identity')",
    "    os.unlink(name,dir_fd=directory); sync_directory_fd(directory); os.close(descriptor)",
    "def open_release_manifest(directory,record,owner,nonce):",
    "    name=release_manifest_name(record); stage_name=release_manifest_stage_name(record,nonce)",
    "    final=open_manifest_entry(directory,name,owner,nonce,(1,2)); stage=open_manifest_entry(directory,stage_name,owner,nonce,(1,2))",
    "    if final is not None:",
    "        if final[1] is None: finish('CONFLICT docker-manifest-format')",
    "        if stage is not None:",
    "            if stage[1] is None or stage[3] != final[3] or stage[2] != final[2] or os.fstat(stage[0]).st_nlink != 2: finish('CONFLICT docker-manifest-stage')",
    "            unlink_manifest_entry(directory,stage_name,stage[0],stage[3],stage[2],(2,))",
    "        info=os.fstat(final[0]); validate_file(info,'CONFLICT',(1,))",
    "        if identity(info) != final[3] or read_owned_content(final[0]) != final[2] or identity(stat_at(directory,name)) != final[3]: finish('CONFLICT docker-manifest-changed')",
    "        return final[0],final[1]",
    "    if stage is None: return None",
    "    if stage[1] is None:",
    "        header=release_manifest_header(owner,nonce,stage[3])",
    "        if not header.startswith(stage[2]) and not stage[2].startswith(header): finish('CONFLICT docker-manifest-stage')",
    "        unlink_manifest_entry(directory,stage_name,stage[0],stage[3],stage[2],(1,)); return None",
    "    try: os.link(stage_name,name,src_dir_fd=directory,dst_dir_fd=directory,follow_symlinks=False); sync_directory_fd(directory)",
    "    except FileExistsError: finish('CONFLICT docker-manifest-race')",
    "    except OSError as error:",
    "        if error.errno in (errno.EINVAL,errno.ENOTSUP,getattr(errno,'EOPNOTSUPP',errno.ENOTSUP)): finish('UNSUPPORTED docker-manifest-publish')",
    "        finish('FAILED docker-manifest-publish')",
    "    final=open_manifest_entry(directory,name,owner,nonce,(2,))",
    "    if final is None or final[1] is None or final[3] != stage[3] or final[2] != stage[2]: finish('FAILED docker-manifest-publish')",
    "    unlink_manifest_entry(directory,stage_name,stage[0],stage[3],stage[2],(2,))",
    "    validate_file(os.fstat(final[0]),'CONFLICT',(1,)); return final[0],final[1]",
    "def create_release_manifest(directory,record,owner,nonce,docker_descriptor,colima_descriptor):",
    "    existing=open_release_manifest(directory,record,owner,nonce)",
    "    if existing is not None:",
    "        if existing[1].entries != ownership_manifest(docker_descriptor,colima_descriptor): finish('CONFLICT docker-manifest-drift')",
    "        return existing",
    "    name=release_manifest_name(record); stage_name=release_manifest_stage_name(record,nonce)",
    "    try: descriptor=os.open(stage_name,os.O_RDWR|os.O_CREAT|os.O_EXCL|nofollow,0o600,dir_fd=directory)",
    "    except FileExistsError: finish('CONFLICT docker-manifest-race')",
    "    except OSError: finish('UNSUPPORTED docker-manifest-create')",
    "    info=os.fstat(descriptor); validate_file(info,'FAILED'); manifest_identity=identity(info); data=release_manifest_bytes(owner,nonce,manifest_identity,ownership_manifest(docker_descriptor,colima_descriptor))",
    "    write_all(descriptor,data); os.fsync(descriptor)",
    "    if read_owned_content(descriptor) != data: finish('FAILED docker-manifest-readback')",
    "    try: os.link(stage_name,name,src_dir_fd=directory,dst_dir_fd=directory,follow_symlinks=False); sync_directory_fd(directory)",
    "    except FileExistsError: finish('CONFLICT docker-manifest-race')",
    "    except OSError as error:",
    "        if error.errno in (errno.EINVAL,errno.ENOTSUP,getattr(errno,'EOPNOTSUPP',errno.ENOTSUP)): finish('UNSUPPORTED docker-manifest-publish')",
    "        finish('FAILED docker-manifest-publish')",
    "    final=open_manifest_entry(directory,name,owner,nonce,(2,))",
    "    if final is None or final[1] is None or final[3] != manifest_identity or final[2] != data: finish('FAILED docker-manifest-publish')",
    "    unlink_manifest_entry(directory,stage_name,descriptor,manifest_identity,data,(2,))",
    "    validate_file(os.fstat(final[0]),'CONFLICT',(1,)); return final[0],final[1]",
    "def validate_release_manifest(directory,record,owner,nonce,expected_identity,expected_digest):",
    "    opened=open_release_manifest(directory,record,owner,nonce)",
    "    if opened is None or opened[1].identity != expected_identity or opened[1].digest != expected_digest: finish('CONFLICT docker-manifest-identity')",
    "    return opened",
    "def unlink_release_manifest(directory,record,descriptor,manifest):",
    "    unlink_manifest_entry(directory,release_manifest_name(record),descriptor,manifest.identity,manifest.data,(1,))",
    "def manifest_allows_current(manifest,docker_descriptor,colima_descriptor):",
    "    return set(ownership_manifest(docker_descriptor,colima_descriptor)).issubset(set(manifest.entries))",
    "def context_fingerprint(command,docker,context,docker_descriptor):",
    "    raw=command('context',[docker,'context','inspect',context])",
    "    if raw.returncode != 0 or raw.stderr != '': finish('CONFLICT docker-context')",
    "    try: value=json.loads(raw.stdout)",
    "    except Exception: finish('CONFLICT docker-context-decode')",
    "    if not isinstance(value,list) or len(value) != 1 or not isinstance(value[0],dict): finish('CONFLICT docker-context-shape')",
    "    canonical=json.dumps(value[0],sort_keys=True,separators=(',',':'))",
    "    return hashlib.sha256((canonical+'\\n'+directory_snapshot(docker_descriptor)).encode('utf-8')).hexdigest()",
    "def named_context_present(command,docker,context):",
    "    raw=command('context-list',[docker,'context','ls','--format','{{json .}}'])",
    "    if raw.returncode != 0 or raw.stderr != '': finish('FAILED docker-context-list')",
    "    if raw.stdout == '' or '\\r' in raw.stdout or not raw.stdout.endswith('\\n') or raw.stdout == '\\n': finish('FAILED docker-context-list-framing')",
    "    lines=raw.stdout[:-1].split('\\n')",
    "    if any(line == '' for line in lines): finish('FAILED docker-context-list-framing')",
    "    try: values=[json.loads(line) for line in lines]",
    "    except Exception: finish('FAILED docker-context-list-decode')",
    "    if any(not isinstance(value,dict) or type(value.get('Name')) is not str for value in values): finish('FAILED docker-context-list-shape')",
    "    matches=[value for value in values if value.get('Name') == context]",
    "    if len(matches) > 1: finish('CONFLICT docker-context-duplicate')",
    "    return len(matches) == 1",
    "def remove_exact_context(command,docker,context,docker_descriptor,expected_context):",
    "    if not named_context_present(command,docker,context): return",
    "    if context_fingerprint(command,docker,context,docker_descriptor) != expected_context: finish('CONFLICT docker-context-identity')",
    "    removed=command('context-remove',[docker,'context','rm','--force',context])",
    "    if removed.returncode != 0 or removed.stderr != '': finish('FAILED docker-context-remove')",
    "    if named_context_present(command,docker,context): finish('FAILED docker-context-present')",
    "def clear_owned_directory(descriptor,path,state_chain,lock_descriptor,lock_path,lock_expected,allowed_entries,namespace_prefix,mutable):",
    "    validate_lock(lock_descriptor,lock_path,lock_expected); validate_state_chain(state_chain)",
    "    allowed=set(allowed_entries)",
    "    def require_allowed(row):",
    "        if namespace_prefix+row not in allowed: finish('CONFLICT namespace-manifest-drift')",
    "    def clear(current,prefix):",
    "        try: names=os.listdir(current)",
    "        except OSError: finish('UNSUPPORTED docker-list')",
    "        for name in names:",
    "            if name in ('.','..') or os.sep in name: finish('CONFLICT docker-entry')",
    "            try: info=stat_at(current,name)",
    "            except OSError: finish('CONFLICT docker-entry')",
    "            if info.st_uid != os.geteuid(): finish('CONFLICT docker-owner')",
    "            relative=prefix+name",
    "            if stat.S_ISREG(info.st_mode):",
    "                if info.st_nlink != 1: finish('CONFLICT docker-links')",
    "                child=os.open(name,os.O_RDONLY|nofollow,dir_fd=current); opened=os.fstat(child)",
    "                if identity(opened) != identity(info) or opened.st_nlink != 1 or opened.st_uid != os.geteuid() or (stat.S_IMODE(opened.st_mode) & 0o022) != 0: finish('CONFLICT docker-file')",
    "                content=b'' if mutable else read_owned_content(child)",
    "                row=('m:' if mutable else 'f:')+relative+':'+identity_text(identity(info))+':'+oct(stat.S_IMODE(info.st_mode))+('' if mutable else ':'+hashlib.sha256(content).hexdigest()); require_allowed(row)",
    "                latest=stat_at(current,name)",
    "                if identity(latest) != identity(info) or identity(os.fstat(child)) != identity(info): finish('CONFLICT docker-file')",
    "                os.unlink(name,dir_fd=current); os.close(child)",
    "            elif stat.S_ISDIR(info.st_mode):",
    "                try: child=os.open(name,os.O_RDONLY|odirectory|nofollow,dir_fd=current)",
    "                except OSError: finish('CONFLICT docker-directory')",
    "                opened=os.fstat(child); validate_directory(opened,'CONFLICT')",
    "                if identity(opened) != identity(info): finish('CONFLICT docker-directory')",
    "                require_allowed('d:'+relative+':'+identity_text(identity(info))+':'+oct(stat.S_IMODE(info.st_mode)))",
    "                clear(child,relative+'/'); os.close(child)",
    "                latest=stat_at(current,name)",
    "                if identity(latest) != identity(info): finish('CONFLICT docker-directory')",
    "                try: os.rmdir(name,dir_fd=current)",
    "                except OSError: finish('CONFLICT docker-directory')",
    "            elif stat.S_ISLNK(info.st_mode):",
    "                target=os.readlink(name,dir_fd=current); require_allowed('l:'+relative+':'+identity_text(identity(info))+':'+oct(stat.S_IMODE(info.st_mode))+':'+os.fsencode(target).hex())",
    "                latest=stat_at(current,name)",
    "                if identity(latest) != identity(info) or os.readlink(name,dir_fd=current) != target: finish('CONFLICT docker-symlink')",
    "                os.unlink(name,dir_fd=current)",
    "            elif stat.S_ISSOCK(info.st_mode):",
    "                require_allowed('s:'+relative+':'+identity_text(identity(info))+':'+oct(stat.S_IMODE(info.st_mode)))",
    "                latest=stat_at(current,name)",
    "                if identity(latest) != identity(info): finish('CONFLICT docker-socket')",
    "                os.unlink(name,dir_fd=current)",
    "            else: finish('CONFLICT docker-entry-type')",
    "        sync_directory_fd(current)",
    "    clear(descriptor,'')",
    "    validate_lock(lock_descriptor,lock_path,lock_expected); validate_state_chain(state_chain)",
    "def remove_docker_namespace(state,state_descriptor,record,docker_descriptor,docker_identity,state_chain,lock_descriptor,lock_path,lock_expected,allowed_entries):",
    "    docker_name=record+'.docker'; docker_path=os.path.join(state,docker_name)",
    "    clear_owned_directory(docker_descriptor,docker_path,state_chain,lock_descriptor,lock_path,lock_expected,allowed_entries,'docker/',False)",
    "    observed=stat_at(state_descriptor,docker_name)",
    "    if identity(observed) != docker_identity: finish('CONFLICT docker-identity')",
    "    remaining=[entry for entry in state_chain if entry[1] != docker_descriptor]",
    "    os.close(docker_descriptor); os.rmdir(docker_name,dir_fd=state_descriptor); sync_directory_fd(state_descriptor)",
    "    try: stat_at(state_descriptor,docker_name); finish('FAILED docker-namespace-present')",
    "    except FileNotFoundError: pass",
    "    except OSError: finish('FAILED docker-namespace-readback')",
    "    validate_lock(lock_descriptor,lock_path,lock_expected); validate_state_chain(remaining)",
    "    return remaining"
  ]
