module HostBootstrap.Ensure.Colima.Backend.Program.Filesystem
  ( filesystemProgram,
  )
where

-- Descriptor-held filesystem and flock primitives shared by every Colima
-- protocol entry point.  Absolute paths are traversed component-by-component
-- with openat/O_NOFOLLOW, and every parent descriptor remains live for the
-- entire observe/mutate/settle bracket.
filesystemProgram :: [String]
filesystemProgram =
  [ "def finish(value): print(value,flush=True); raise SystemExit(0)",
    "nofollow=getattr(os,'O_NOFOLLOW',None); odirectory=getattr(os,'O_DIRECTORY',None)",
    "if nofollow is None or odirectory is None or not hasattr(fcntl,'flock') or not hasattr(os,'fsync') or not hasattr(os,'link') or not hasattr(os,'replace'): finish('UNSUPPORTED required-api')",
    "uint64_limit=1 << 64",
    "def identity(info): return (info.st_dev,info.st_ino)",
    "def identity_text(value): return str(value[0])+':'+str(value[1])",
    "def validate_file(info,kind,links=(1,)):",
    "    if not stat.S_ISREG(info.st_mode) or info.st_uid != os.geteuid() or info.st_nlink not in links or stat.S_IMODE(info.st_mode) != 0o600: finish(kind+' file-identity')",
    "def validate_directory(info,kind):",
    "    if not stat.S_ISDIR(info.st_mode) or info.st_uid != os.geteuid() or (stat.S_IMODE(info.st_mode) & 0o022) != 0: finish(kind+' directory-identity')",
    "def validate_parent_directory(info,kind):",
    "    mode=stat.S_IMODE(info.st_mode); owned=info.st_uid == os.geteuid() and (mode & 0o022) == 0; sticky_root=info.st_uid == 0 and (mode & 0o1000) != 0 and (mode & 0o002) != 0",
    "    if not stat.S_ISDIR(info.st_mode) or not (owned or (info.st_uid == 0 and (mode & 0o022) == 0) or sticky_root): finish(kind+' directory-identity')",
    "def stat_at(directory,name): return os.stat(name,dir_fd=directory,follow_symlinks=False)",
    "def sync_directory_fd(descriptor):",
    "    try:",
    "        info=os.fstat(descriptor); validate_parent_directory(info,'UNSUPPORTED'); os.fsync(descriptor)",
    "    except OSError as error:",
    "        if error.errno in (errno.EINVAL,errno.ENOTSUP,getattr(errno,'EOPNOTSUPP',errno.ENOTSUP)): finish('UNSUPPORTED directory-fsync')",
    "        finish('FAILED directory-fsync')",
    "def validate_state_chain(chain):",
    "    for path,descriptor,parent,name in chain:",
    "        opened=os.fstat(descriptor); validate_parent_directory(opened,'UNSUPPORTED')",
    "        try: path_info=os.lstat('/') if parent is None else stat_at(parent,name)",
    "        except OSError: finish('CONFLICT state-directory')",
    "        if identity(opened) != identity(path_info): finish('CONFLICT state-directory')",
    "def open_directory(path,kind):",
    "    if not os.path.isabs(path) or os.path.normpath(path) != path: finish('UNSUPPORTED '+kind)",
    "    try: descriptor=os.open('/',os.O_RDONLY|odirectory|nofollow)",
    "    except OSError: finish('UNSUPPORTED '+kind)",
    "    opened=os.fstat(descriptor); validate_parent_directory(opened,'UNSUPPORTED')",
    "    chain=[('/',descriptor,None,None)]; current=descriptor; prefix='/'",
    "    for component in [value for value in path.split(os.sep) if value]:",
    "        try:",
    "            path_info=stat_at(current,component)",
    "            child=os.open(component,os.O_RDONLY|odirectory|nofollow,dir_fd=current)",
    "        except OSError as error:",
    "            if error.errno in (errno.ELOOP,errno.EINVAL,errno.ENOTSUP,getattr(errno,'EOPNOTSUPP',errno.ENOTSUP),errno.ENOENT): finish('UNSUPPORTED '+kind)",
    "            finish('FAILED '+kind)",
    "        child_info=os.fstat(child); validate_parent_directory(child_info,'UNSUPPORTED')",
    "        if identity(child_info) != identity(path_info): finish('CONFLICT '+kind)",
    "        prefix=os.path.join(prefix,component); chain.append((prefix,child,current,component)); current=child",
    "    validate_directory(os.fstat(current),'UNSUPPORTED')",
    "    validate_state_chain(chain)",
    "    return current,chain",
    "def open_child(parent,parent_descriptor,name,create):",
    "    target=os.path.join(parent,name); created=False",
    "    try:",
    "        if create: os.mkdir(name,0o700,dir_fd=parent_descriptor); sync_directory_fd(parent_descriptor); created=True",
    "    except FileExistsError: pass",
    "    except OSError as error:",
    "        if error.errno in (errno.ENOTSUP,getattr(errno,'EOPNOTSUPP',errno.ENOTSUP),errno.EINVAL): finish('UNSUPPORTED state-directory')",
    "        finish('FAILED state-directory')",
    "    try: path_info=stat_at(parent_descriptor,name); descriptor=os.open(name,os.O_RDONLY|odirectory|nofollow,dir_fd=parent_descriptor)",
    "    except OSError as error:",
    "        if error.errno in (errno.ELOOP,errno.EINVAL,errno.ENOTSUP,getattr(errno,'EOPNOTSUPP',errno.ENOTSUP)): finish('UNSUPPORTED state-directory')",
    "        finish('CONFLICT state-directory')",
    "    opened=os.fstat(descriptor); validate_directory(opened,'UNSUPPORTED')",
    "    if identity(opened) != identity(path_info): finish('CONFLICT state-directory')",
    "    return target,descriptor,created",
    "def ensure_child(parent,parent_descriptor,name): return open_child(parent,parent_descriptor,name,True)",
    "def ensure_state_directory(root,root_descriptor,root_chain,record,allow_create,docker_config):",
    "    if not os.path.isabs(root) or not os.path.isabs(record) or not os.path.isabs(docker_config): finish('UNSUPPORTED state-path')",
    "    validate_directory(os.fstat(root_descriptor),'UNSUPPORTED'); validate_state_chain(root_chain)",
    "    host_state,host_descriptor,_=open_child(root,root_descriptor,'.hostbootstrap',allow_create)",
    "    state,state_descriptor,_=open_child(host_state,host_descriptor,'colima',allow_create)",
    "    if os.path.dirname(record) != state: finish('UNSUPPORTED record-path')",
    "    record_name=os.path.basename(record)",
    "    if record_name in ('','.','..') or os.sep in record_name or len(os.fsencode(record_name)) > 96: finish('UNSUPPORTED record-path')",
    "    docker_name=record_name+'.docker'",
    "    if docker_config != os.path.join(state,docker_name): finish('UNSUPPORTED docker-namespace')",
    "    try: stat_at(state_descriptor,docker_name); docker_present=True",
    "    except FileNotFoundError: docker_present=False",
    "    except OSError: finish('UNSUPPORTED docker-namespace')",
    "    base_chain=list(root_chain)+[(host_state,host_descriptor,root_descriptor,'.hostbootstrap'),(state,state_descriptor,host_descriptor,'colima')]",
    "    if not docker_present:",
    "        validate_state_chain(base_chain); return state,state_descriptor,record_name,base_chain,None,None,False",
    "    docker_path,docker_descriptor,docker_created=open_child(state,state_descriptor,docker_name,False)",
    "    chain=base_chain+[(docker_path,docker_descriptor,state_descriptor,docker_name)]",
    "    validate_state_chain(chain)",
    "    return state,state_descriptor,record_name,chain,docker_descriptor,identity(os.fstat(docker_descriptor)),docker_created",
    "lock_bindings={}",
    "def lock_header(name,value): return ('version 1\\nprofile '+name+'\\nidentity '+identity_text(value)+'\\n').encode('ascii')",
    "def validate_lock_header(descriptor,name,value):",
    "    if read_descriptor(descriptor) != lock_header(name,value): finish('CONFLICT lock-binding')",
    "def lock_stage_name(name,nonce): return name+'.init.'+nonce+'.stage'",
    "def open_lock_entry(directory,name,links):",
    "    try: descriptor=os.open(name,os.O_RDWR|nofollow,dir_fd=directory)",
    "    except FileNotFoundError: return None",
    "    except OSError: finish('CONFLICT lock-open')",
    "    info=os.fstat(descriptor); validate_file(info,'CONFLICT',links)",
    "    path_info=stat_at(directory,name)",
    "    if identity(info) != identity(path_info): finish('CONFLICT lock-identity')",
    "    return descriptor",
    "def unlink_lock_stage(directory,name,descriptor,expected_identity):",
    "    opened=os.fstat(descriptor); validate_file(opened,'CONFLICT',(1,2,3))",
    "    if identity(opened) != expected_identity: finish('CONFLICT lock-stage-identity')",
    "    data=read_descriptor(descriptor)",
    "    if not lock_header(name.split('.init.',1)[0],expected_identity).startswith(data): finish('CONFLICT lock-stage-content')",
    "    path_info=stat_at(directory,name)",
    "    if identity(path_info) != expected_identity: finish('CONFLICT lock-stage-identity')",
    "    os.unlink(name,dir_fd=directory); os.close(descriptor); sync_directory_fd(directory)",
    "def cleanup_lock_stages(directory,name,locked_identity):",
    "    pattern=re.compile(re.escape(name)+r'\\.init\\.([0-9a-f]{64})\\.stage')",
    "    try: names=os.listdir(directory)",
    "    except OSError: finish('UNSUPPORTED lock-list')",
    "    for stage in names:",
    "        if pattern.fullmatch(stage) is None: continue",
    "        opened=open_lock_entry(directory,stage,(1,2,3))",
    "        if opened is None: continue",
    "        stage_identity=identity(os.fstat(opened))",
    "        if stage_identity == locked_identity or lock_header(name,stage_identity).startswith(read_descriptor(opened)):",
    "            unlink_lock_stage(directory,stage,opened,stage_identity)",
    "        else: finish('CONFLICT lock-stage-content')",
    "def initialize_lock(directory,name):",
    "    nonce=secrets.token_hex(32); stage=lock_stage_name(name,nonce)",
    "    try: descriptor=os.open(stage,os.O_RDWR|os.O_CREAT|os.O_EXCL|nofollow,0o600,dir_fd=directory)",
    "    except FileExistsError: finish('CONFLICT lock-stage-race')",
    "    except OSError: finish('UNSUPPORTED lock-stage-create')",
    "    info=os.fstat(descriptor); validate_file(info,'FAILED'); stage_identity=identity(info); data=lock_header(name,stage_identity)",
    "    write_all(descriptor,data); os.fsync(descriptor)",
    "    if read_descriptor(descriptor) != data: finish('FAILED lock-stage-readback')",
    "    try: os.link(stage,name+'.anchor',src_dir_fd=directory,dst_dir_fd=directory,follow_symlinks=False); sync_directory_fd(directory); return descriptor,stage,True",
    "    except FileExistsError:",
    "        unlink_lock_stage(directory,stage,descriptor,stage_identity); return None,None,False",
    "    except OSError as error:",
    "        if error.errno in (errno.EINVAL,errno.ENOTSUP,getattr(errno,'EOPNOTSUPP',errno.ENOTSUP)): finish('UNSUPPORTED lock-publish')",
    "        finish('FAILED lock-publish')",
    "def open_lock(root,root_descriptor,path,allow_create,expected=None):",
    "    if not os.path.isabs(path) or os.path.dirname(path) != root: finish('UNSUPPORTED lock-path')",
    "    name=os.path.basename(path); anchor=name+'.anchor'",
    "    if name in ('','.','..') or os.sep in name or len(os.fsencode(anchor)) > 96: finish('UNSUPPORTED lock-path')",
    "    descriptor=open_lock_entry(root_descriptor,anchor,(2,3))",
    "    created=False; own_stage=None",
    "    if descriptor is None:",
    "        try: stat_at(root_descriptor,name); finish('CONFLICT lock-anchor-missing')",
    "        except FileNotFoundError: pass",
    "        except OSError: finish('CONFLICT lock-anchor')",
    "        if not allow_create: finish('CONFLICT lock-missing')",
    "        descriptor,own_stage,created=initialize_lock(root_descriptor,name)",
    "        if descriptor is None:",
    "            descriptor=open_lock_entry(root_descriptor,anchor,(2,3))",
    "            if descriptor is None: finish('CONFLICT lock-init-race')",
    "    try:",
    "        fcntl.flock(descriptor,fcntl.LOCK_EX)",
    "        opened=os.fstat(descriptor); validate_file(opened,'UNSUPPORTED',(2,3)); locked_identity=identity(opened)",
    "        anchor_info=stat_at(root_descriptor,anchor)",
    "        if identity(anchor_info) != locked_identity: finish('CONFLICT lock-anchor-identity')",
    "        canonical=open_lock_entry(root_descriptor,name,(2,3))",
    "        if canonical is None:",
    "            if not allow_create: finish('CONFLICT lock-missing')",
    "            try: os.link(anchor,name,src_dir_fd=root_descriptor,dst_dir_fd=root_descriptor,follow_symlinks=False); sync_directory_fd(root_descriptor)",
    "            except FileExistsError: finish('CONFLICT lock-publish-race')",
    "            except OSError: finish('UNSUPPORTED lock-publish')",
    "        else:",
    "            if identity(os.fstat(canonical)) != locked_identity: finish('CONFLICT lock-identity')",
    "            os.close(canonical)",
    "        validate_lock_header(descriptor,name,locked_identity)",
    "        cleanup_lock_stages(root_descriptor,name,locked_identity)",
    "        opened=os.fstat(descriptor); validate_file(opened,'UNSUPPORTED',(2,))",
    "        if expected is not None and identity(opened) != expected: finish('CONFLICT lock-identity')",
    "        lock_bindings[descriptor]=(root_descriptor,name,anchor,path); return descriptor",
    "    except OSError as error:",
    "        os.close(descriptor)",
    "        if error.errno in (errno.EINVAL,errno.ENOTSUP,getattr(errno,'EOPNOTSUPP',errno.ENOTSUP)): finish('UNSUPPORTED lock-backend')",
    "        finish('FAILED lock-backend')",
    "def validate_lock(descriptor,path,expected=None):",
    "    opened=os.fstat(descriptor); validate_file(opened,'UNSUPPORTED',(2,)); binding=lock_bindings.get(descriptor)",
    "    if binding is None or binding[3] != path: finish('CONFLICT lock-binding')",
    "    try: canonical=stat_at(binding[0],binding[1]); anchor=stat_at(binding[0],binding[2])",
    "    except OSError: finish('CONFLICT lock-identity')",
    "    if identity(opened) != identity(canonical) or identity(opened) != identity(anchor): finish('CONFLICT lock-identity')",
    "    if expected is not None and identity(opened) != expected: finish('CONFLICT lock-identity')",
    "    validate_lock_header(descriptor,binding[1],identity(opened))",
    "def validate_lock_empty(descriptor):",
    "    binding=lock_bindings.get(descriptor)",
    "    if binding is None: finish('CONFLICT lock-binding')",
    "    validate_lock_header(descriptor,binding[1],identity(os.fstat(descriptor)))"
  ]
