module HostBootstrap.Ensure.Colima.Backend.Program.Namespace
  ( namespaceProgram,
  )
where

-- Profile-global Colima-home ownership and exact Lima data-disk observation.
-- The home is created only after a nonce-bearing origin exists, through a
-- nonce stage and Darwin's no-replace rename.  Every later bracket opens the
-- canonical directory without following links and validates its self-bound
-- marker before a profile/disk absence observation can authorize anything.
namespaceProgram :: [String]
namespaceProgram =
  [ "def colima_home_parts(path):",
    "    if not os.path.isabs(path) or os.path.normpath(path) != path: finish('UNSUPPORTED colima-home')",
    "    if os.environ.get('LIMA_HOME') != os.path.join(path,'_lima') or os.environ.get('COLIMA_CACHE_HOME') != os.path.join(path,'cache') or os.environ.get('TMPDIR') != os.path.join(path,'tmp'): finish('UNSUPPORTED colima-environment')",
    "    parent=os.path.dirname(path); name=os.path.basename(path)",
    "    if re.fullmatch(r'\\.h[0-9a-f]{32}',name) is None: finish('UNSUPPORTED colima-home')",
    "    descriptor,chain=open_directory(parent,'colima-home-root'); return parent,name,descriptor,chain",
    "def open_colima_home(path):",
    "    parent,name,parent_descriptor,chain=colima_home_parts(path)",
    "    try: path_info=stat_at(parent_descriptor,name)",
    "    except FileNotFoundError: return parent,name,parent_descriptor,chain,None,None",
    "    except OSError: finish('CONFLICT colima-home')",
    "    try: descriptor=os.open(name,os.O_RDONLY|odirectory|nofollow,dir_fd=parent_descriptor)",
    "    except OSError: finish('CONFLICT colima-home')",
    "    opened=os.fstat(descriptor); validate_directory(opened,'CONFLICT')",
    "    if identity(opened) != identity(path_info): finish('CONFLICT colima-home-identity')",
    "    fixed=open_fixed_home_children(path,descriptor,False)",
    "    chain=chain+[(path,descriptor,parent_descriptor,name)]+[(entry[0],entry[1],descriptor,entry[3]) for entry in fixed]; validate_state_chain(chain)",
    "    return parent,name,parent_descriptor,chain,descriptor,identity(opened)",
    "def colima_home_stage_name(name,nonce): return name+'.init.'+nonce+'.stage'",
    "def open_fixed_home_children(home_path,descriptor,create):",
    "    results=[]",
    "    for name in ('cache','tmp','_lima'):",
    "        path,child,created=open_child(home_path,descriptor,name,create); results.append((path,child,identity(os.fstat(child)),name))",
    "    return results",
    "def colima_home_marker(owner,nonce,home_identity,fixed): return ('version 1\\nowner '+owner+'\\nnonce '+nonce+'\\nidentity '+identity_text(home_identity)+'\\ncache '+identity_text(fixed[0][2])+'\\ntmp '+identity_text(fixed[1][2])+'\\nlima '+identity_text(fixed[2][2])+'\\n').encode('ascii')",
    "def validate_colima_home_marker(descriptor,owner,nonce,home_identity):",
    "    marker_name='.hostbootstrap-origin'; fixed=open_fixed_home_children(os.environ.get('COLIMA_HOME',''),descriptor,False)",
    "    try: marker=os.open(marker_name,os.O_RDONLY|nofollow,dir_fd=descriptor)",
    "    except OSError: finish('CONFLICT colima-home-marker')",
    "    info=os.fstat(marker); validate_file(info,'CONFLICT',(1,)); data=read_descriptor(marker)",
    "    if data != colima_home_marker(owner,nonce,home_identity,fixed) or identity(stat_at(descriptor,marker_name)) != identity(info): finish('CONFLICT colima-home-marker')",
    "    os.close(marker); return fixed",
    "def write_colima_home_marker(descriptor,owner,nonce,home_identity):",
    "    name='.hostbootstrap-origin'; fixed=open_fixed_home_children(os.environ.get('COLIMA_HOME',''),descriptor,True); expected=colima_home_marker(owner,nonce,home_identity,fixed)",
    "    try: marker=os.open(name,os.O_RDWR|os.O_CREAT|os.O_EXCL|nofollow,0o600,dir_fd=descriptor)",
    "    except FileExistsError:",
    "        marker=os.open(name,os.O_RDWR|nofollow,dir_fd=descriptor); info=os.fstat(marker); validate_file(info,'CONFLICT',(1,)); observed=read_descriptor(marker)",
    "        if observed != expected and not expected.startswith(observed): finish('CONFLICT colima-home-marker')",
    "        if observed != expected: os.ftruncate(marker,0); write_all(marker,expected); os.fsync(marker)",
    "    except OSError: finish('UNSUPPORTED colima-home-marker')",
    "    else: write_all(marker,expected); os.fsync(marker)",
    "    if read_descriptor(marker) != expected or identity(stat_at(descriptor,name)) != identity(os.fstat(marker)): finish('FAILED colima-home-marker')",
    "    os.close(marker); sync_directory_fd(descriptor); return fixed",
    "def create_colima_home_stage(path,owner,nonce,expected_identity=None):",
    "    parent,name,parent_descriptor,chain=colima_home_parts(path)",
    "    try: stat_at(parent_descriptor,name); finish('CONFLICT colima-home-present')",
    "    except FileNotFoundError: pass",
    "    stage=colima_home_stage_name(name,nonce); stage_path_value=os.path.join(parent,stage)",
    "    stage_path_value,stage_descriptor,created=open_child(parent,parent_descriptor,stage,True)",
    "    if not created and expected_identity is not None and identity(os.fstat(stage_descriptor)) != expected_identity: finish('CONFLICT colima-home-stage-unbound')",
    "    allowed=set() if created else set(os.listdir(stage_descriptor))",
    "    if allowed-{'cache','tmp','_lima','.hostbootstrap-origin'}: finish('CONFLICT colima-home-stage')",
    "    home_identity=identity(os.fstat(stage_descriptor))",
    "    fixed=write_colima_home_marker(stage_descriptor,owner,nonce,home_identity) if created or expected_identity is None else validate_colima_home_marker(stage_descriptor,owner,nonce,home_identity)",
    "    if expected_identity is None and any(os.listdir(entry[1]) for entry in fixed): finish('CONFLICT colima-home-stage-content')",
    "    sync_directory_fd(parent_descriptor)",
    "    chain=chain+[(stage_path_value,stage_descriptor,parent_descriptor,stage)]+[(entry[0],entry[1],stage_descriptor,entry[3]) for entry in fixed]",
    "    return parent,name,parent_descriptor,chain,stage_descriptor,home_identity",
    "def rename_exclusive(directory,source,target):",
    "    try:",
    "        library=ctypes.CDLL(None,use_errno=True)",
    "        if sys.platform == 'darwin': function=library.renameatx_np; no_replace=4",
    "        elif sys.platform.startswith('linux'): function=library.renameat2; no_replace=1",
    "        else: finish('UNSUPPORTED rename-exclusive')",
    "    except Exception: finish('UNSUPPORTED rename-exclusive')",
    "    function.argtypes=[ctypes.c_int,ctypes.c_char_p,ctypes.c_int,ctypes.c_char_p,ctypes.c_uint]; function.restype=ctypes.c_int",
    "    result=function(directory,os.fsencode(source),directory,os.fsencode(target),no_replace)",
    "    if result != 0:",
    "        failure=ctypes.get_errno()",
    "        if failure == errno.EEXIST: finish('CONFLICT colima-home-present')",
    "        if failure in (errno.EINVAL,errno.ENOTSUP,getattr(errno,'EOPNOTSUPP',errno.ENOTSUP),getattr(errno,'ENOSYS',errno.EINVAL)): finish('UNSUPPORTED rename-exclusive')",
    "        finish('FAILED rename-exclusive')",
    "def publish_colima_home(path,owner,nonce,expected_identity):",
    "    parent,name,parent_descriptor,chain=colima_home_parts(path); stage=colima_home_stage_name(name,nonce)",
    "    try: stage_info=stat_at(parent_descriptor,stage)",
    "    except FileNotFoundError: stage_info=None",
    "    except OSError: finish('CONFLICT colima-home-stage')",
    "    try: target_info=stat_at(parent_descriptor,name)",
    "    except FileNotFoundError: target_info=None",
    "    except OSError: finish('CONFLICT colima-home')",
    "    if stage_info is not None and target_info is None:",
    "        if identity(stage_info) != expected_identity: finish('CONFLICT colima-home-stage-identity')",
    "        rename_exclusive(parent_descriptor,stage,name); sync_directory_fd(parent_descriptor); target_info=stat_at(parent_descriptor,name)",
    "    elif stage_info is not None or target_info is None: finish('CONFLICT colima-home-publish-state')",
    "    if identity(target_info) != expected_identity: finish('CONFLICT colima-home-identity')",
    "    descriptor=os.open(name,os.O_RDONLY|odirectory|nofollow,dir_fd=parent_descriptor); opened=os.fstat(descriptor); validate_directory(opened,'CONFLICT')",
    "    if identity(opened) != expected_identity: finish('CONFLICT colima-home-identity')",
    "    fixed=validate_colima_home_marker(descriptor,owner,nonce,expected_identity)",
    "    chain=chain+[(path,descriptor,parent_descriptor,name)]+[(entry[0],entry[1],descriptor,entry[3]) for entry in fixed]; validate_state_chain(chain)",
    "    return descriptor,expected_identity,chain",
    "def strict_lima_values(raw):",
    "    if raw.returncode != 0 or raw.stderr != '': finish('FAILED disk-list')",
    "    if raw.stdout == '': return []",
    "    if '\\r' in raw.stdout or not raw.stdout.endswith('\\n') or raw.stdout == '\\n': finish('FAILED disk-list-framing')",
    "    lines=raw.stdout[:-1].split('\\n')",
    "    if any(line == '' for line in lines): finish('FAILED disk-list-framing')",
    "    try: values=[json.loads(line) for line in lines]",
    "    except Exception: finish('FAILED disk-list-decode')",
    "    required=('name','dir','instance','instanceDir','format','mountPoint')",
    "    if any(not isinstance(value,dict) or any(type(value.get(key)) is not str for key in required) or type(value.get('size')) is not int or value.get('size') <= 0 or not value.get('name') or not os.path.isabs(value.get('dir')) or os.path.normpath(value.get('dir')) != value.get('dir') for value in values): finish('FAILED disk-list-shape')",
    "    if len({value['name'] for value in values}) != len(values): finish('CONFLICT disk-list-duplicate')",
    "    return values",
    "def open_relative_directory(root_path,root_descriptor,components):",
    "    current=root_descriptor; current_path=root_path; chain=[]",
    "    for component in components:",
    "        try: path_info=stat_at(current,component); child=os.open(component,os.O_RDONLY|odirectory|nofollow,dir_fd=current)",
    "        except OSError: finish('CONFLICT disk-path')",
    "        opened=os.fstat(child); validate_directory(opened,'CONFLICT')",
    "        if identity(opened) != identity(path_info): finish('CONFLICT disk-identity')",
    "        current_path=os.path.join(current_path,component); chain.append((current_path,child,current,component)); current=child",
    "    return current,identity(os.fstat(current)),chain",
    "def disk_path_absent(root_descriptor,components):",
    "    current=root_descriptor; opened=[]",
    "    try:",
    "        for component in components:",
    "            try: info=stat_at(current,component)",
    "            except FileNotFoundError: return True",
    "            if not stat.S_ISDIR(info.st_mode): finish('CONFLICT disk-path')",
    "            child=os.open(component,os.O_RDONLY|odirectory|nofollow,dir_fd=current); opened.append(child); current=child",
    "        return False",
    "    finally:",
    "        for descriptor in reversed(opened): os.close(descriptor)",
    "def validate_artifact_file(info):",
    "    if not stat.S_ISREG(info.st_mode) or info.st_uid != os.geteuid() or info.st_nlink != 1 or (stat.S_IMODE(info.st_mode) & 0o022) != 0: finish('CONFLICT profile-artifact')",
    "def open_artifact_file(parent_descriptor,name):",
    "    try: path_info=stat_at(parent_descriptor,name); descriptor=os.open(name,os.O_RDONLY|nofollow,dir_fd=parent_descriptor)",
    "    except OSError: finish('CONFLICT profile-artifact')",
    "    opened=os.fstat(descriptor); validate_artifact_file(opened)",
    "    if identity(opened) != identity(path_info): finish('CONFLICT profile-artifact-identity')",
    "    return descriptor,identity(opened)",
    "def artifact_file_entry(label,parent_descriptor,name,digest_content):",
    "    descriptor,value=open_artifact_file(parent_descriptor,name); content=read_owned_content(descriptor) if digest_content else b''",
    "    return (label,'file',parent_descriptor,name,descriptor,value,None,hashlib.sha256(content).hexdigest() if digest_content else str(os.fstat(descriptor).st_size))",
    "def artifact_link_entry(label,parent_descriptor,name,expected_target):",
    "    try: before=stat_at(parent_descriptor,name); target=os.readlink(name,dir_fd=parent_descriptor); after=stat_at(parent_descriptor,name)",
    "    except OSError: finish('CONFLICT profile-artifact')",
    "    if not stat.S_ISLNK(before.st_mode) or before.st_uid != os.geteuid() or identity(before) != identity(after) or target != expected_target: finish('CONFLICT profile-artifact-link')",
    "    return (label,'link',parent_descriptor,name,None,identity(before),target,'')",
    "def validate_artifact_entries(entries):",
    "    for label,kind,parent,name,descriptor,expected,target,content_digest in entries:",
    "        current=stat_at(parent,name)",
    "        if identity(current) != expected: finish('CONFLICT profile-artifact-identity')",
    "        if kind == 'file':",
    "            opened=os.fstat(descriptor); validate_artifact_file(opened)",
    "            if identity(opened) != expected: finish('CONFLICT profile-artifact-identity')",
    "            observed=hashlib.sha256(read_owned_content(descriptor)).hexdigest() if content_digest and len(content_digest) == 64 else str(opened.st_size)",
    "            if observed != content_digest: finish('CONFLICT profile-artifact-content')",
    "        elif kind == 'link':",
    "            if not stat.S_ISLNK(current.st_mode) or os.readlink(name,dir_fd=parent) != target: finish('CONFLICT profile-artifact-link')",
    "def close_artifact_entries(entries):",
    "    for entry in entries:",
    "        if entry[4] is not None:",
    "            try: os.close(entry[4])",
    "            except OSError: pass",
    "def artifact_digest(entries,directory_chain,wall):",
    "    values=['wall='+wall_text(wall)]",
    "    values += ['directory='+identity_text(identity(os.fstat(entry[1]))) for entry in directory_chain]",
    "    values += [entry[0]+'='+entry[1]+':'+identity_text(entry[5])+':'+(entry[6] or '')+':'+entry[7] for entry in entries]",
    "    return hashlib.sha256(('\\n'.join(values)+'\\n').encode('utf-8')).hexdigest()",
    "def strict_profile_wall(config_entry):",
    "    descriptor=config_entry[4]",
    "    try: text=read_owned_content(descriptor).decode('utf-8')",
    "    except Exception: finish('CONFLICT profile-config')",
    "    if '\\r' in text or not text.endswith('\\n'): finish('CONFLICT profile-config-framing')",
    "    result=[]",
    "    for name in ('cpu','memory','disk','rootDisk'):",
    "        matches=re.findall(r'^'+name+r': ([1-9][0-9]*)$',text,re.MULTILINE)",
    "        if len(matches) != 1: finish('CONFLICT profile-config-wall')",
    "        result.append(int(matches[0]))",
    "    gib=1024**3; return (result[0],result[1]*gib,result[2]*gib,result[3]*gib)",
    "def observe_profile_artifacts(command,lima,profile,colima_path,colima_descriptor,expected_wall=None):",
    "    disk_name='colima-'+profile; disk_components=['_lima','_disks',disk_name]; disk_path=os.path.join(colima_path,*disk_components); instance_path=os.path.join(colima_path,'_lima',disk_name)",
    "    values=strict_lima_values(command('disk-list',[lima,'disk','list','--json'])); matches=[value for value in values if value['name'] == disk_name]",
    "    if len(matches) > 1: finish('CONFLICT disk-list-duplicate')",
    "    if not matches:",
    "        if not disk_path_absent(colima_descriptor,disk_components): finish('CONFLICT hidden-disk')",
    "        return None",
    "    value=matches[0]",
    "    if value['dir'] != disk_path or value['instance'] != disk_name or value['instanceDir'] != instance_path: finish('CONFLICT disk-path')",
    "    profile_descriptor,profile_identity,profile_chain=open_relative_directory(colima_path,colima_descriptor,[profile])",
    "    instance_descriptor,instance_identity,instance_chain=open_relative_directory(colima_path,colima_descriptor,['_lima',disk_name])",
    "    store_descriptor,store_identity,store_chain=open_relative_directory(colima_path,colima_descriptor,['_store'])",
    "    disk_descriptor,disk_directory_identity,disk_chain=open_relative_directory(colima_path,colima_descriptor,disk_components)",
    "    entries=[artifact_file_entry('profile-config',profile_descriptor,'colima.yaml',True),artifact_file_entry('instance-colima-config',instance_descriptor,'colima.yaml',True),artifact_file_entry('instance-lima-config',instance_descriptor,'lima.yaml',True),artifact_file_entry('store',store_descriptor,disk_name+'.json',True),artifact_file_entry('root-disk',instance_descriptor,'diffdisk',False),artifact_link_entry('root-link',instance_descriptor,'disk','diffdisk'),artifact_file_entry('datadisk',disk_descriptor,'datadisk',False),artifact_link_entry('in-use-by',disk_descriptor,'in_use_by',instance_path)]",
    "    wall=strict_profile_wall(entries[0])",
    "    if value['size'] != wall[2] or os.fstat(entries[4][4]).st_size != wall[3] or os.fstat(entries[6][4]).st_size != wall[2] or (expected_wall is not None and wall != expected_wall): finish('CONFLICT wall-mismatch')",
    "    chain=profile_chain+instance_chain+store_chain+disk_chain; validate_artifact_entries(entries)",
    "    digest=artifact_digest(entries,chain,wall)",
    "    return types.SimpleNamespace(disk_descriptor=disk_descriptor,disk=entries[6][5],chain=chain,entries=entries,digest=digest,wall=wall)",
    "def owned_path_absent(root_descriptor,components,final_directory):",
    "    current=root_descriptor; opened=[]",
    "    try:",
    "        for index,component in enumerate(components):",
    "            try: info=stat_at(current,component)",
    "            except FileNotFoundError: return True",
    "            if index == len(components)-1:",
    "                expected=stat.S_ISDIR(info.st_mode) if final_directory else stat.S_ISREG(info.st_mode)",
    "                if not expected or info.st_uid != os.geteuid(): finish('CONFLICT profile-artifact')",
    "                return False",
    "            if not stat.S_ISDIR(info.st_mode): finish('CONFLICT profile-artifact')",
    "            child=os.open(component,os.O_RDONLY|odirectory|nofollow,dir_fd=current); opened.append(child); current=child",
    "        return True",
    "    finally:",
    "        for descriptor in reversed(opened): os.close(descriptor)",
    "def profile_artifacts_absent(colima_descriptor,profile):",
    "    disk_name='colima-'+profile",
    "    checks=[([profile],True),(['_lima',disk_name],True),(['_lima','_disks',disk_name],True),(['_store',disk_name+'.json'],False)]",
    "    return all(owned_path_absent(colima_descriptor,parts,is_directory) for parts,is_directory in checks)",
    "def remove_colima_namespace(path,descriptor,expected_identity,state_chain,lock_descriptor,lock_path,lock_expected,allowed_entries):",
    "    descendants=[entry for entry in state_chain if entry[0].startswith(path+os.sep)]",
    "    for entry in reversed(descendants):",
    "        try: os.close(entry[1])",
    "        except OSError: pass",
    "    retained=[entry for entry in state_chain if not entry[0].startswith(path+os.sep)]",
    "    clear_owned_directory(descriptor,path,retained,lock_descriptor,lock_path,lock_expected,allowed_entries,'colima/',True)",
    "    parent_path,name,parent_descriptor,parent_chain=colima_home_parts(path)",
    "    observed=stat_at(parent_descriptor,name)",
    "    if identity(observed) != expected_identity or identity(os.fstat(descriptor)) != expected_identity: finish('CONFLICT colima-home-identity')",
    "    remaining=[entry for entry in retained if entry[1] != descriptor]",
    "    os.close(descriptor); os.rmdir(name,dir_fd=parent_descriptor); sync_directory_fd(parent_descriptor)",
    "    try: stat_at(parent_descriptor,name); finish('FAILED colima-home-present')",
    "    except FileNotFoundError: pass",
    "    except OSError: finish('FAILED colima-home-readback')",
    "    validate_lock(lock_descriptor,lock_path,lock_expected); validate_state_chain(remaining)",
    "    return remaining"
  ]
