{- | Every phantom index on each direct-Colima authority package is nominal. -}
module CoerceColimaAuthorityRoles where

import Data.Coerce (coerce)
import HostBootstrap.Ensure.Colima
  ( ColimaCleanupAuthority,
    LiveColimaWall,
    PreparedColimaCleanupCall,
    PreparedColimaWallCall,
  )

data PreparedScopeA
data PreparedScopeB
data PreparedSpecificationDigestA
data PreparedSpecificationDigestB
data PreparedPlanA
data PreparedPlanB
data PreparedConfigurationA
data PreparedConfigurationB
data PreparedProviderResourceA
data PreparedProviderResourceB
data PreparedProviderFrameA
data PreparedProviderFrameB
data PreparedBudgetA
data PreparedBudgetB
data PreparedCapabilityA
data PreparedCapabilityB
data PreparedWallA
data PreparedWallB
data PreparedWorkloadsA
data PreparedWorkloadsB
data PreparedPartitionA
data PreparedPartitionB
data PreparedReservationA
data PreparedReservationB
data PreparedFenceA
data PreparedFenceB
data LiveScopeA
data LiveScopeB
data LiveSpecificationDigestA
data LiveSpecificationDigestB
data LivePlanA
data LivePlanB
data LiveConfigurationA
data LiveConfigurationB
data LiveProviderResourceA
data LiveProviderResourceB
data LiveProviderFrameA
data LiveProviderFrameB
data LiveWallA
data LiveWallB
data LiveEpochA
data LiveEpochB
data LiveFenceA
data LiveFenceB
data CleanupScopeA
data CleanupScopeB
data CleanupSpecificationDigestA
data CleanupSpecificationDigestB
data CleanupPlanA
data CleanupPlanB
data CleanupConfigurationA
data CleanupConfigurationB
data CleanupProviderResourceA
data CleanupProviderResourceB
data CleanupProviderFrameA
data CleanupProviderFrameB
data CleanupWallA
data CleanupWallB
data CleanupEpochA
data CleanupEpochB
data CleanupFenceA
data CleanupFenceB
data PreparedCleanupScopeA
data PreparedCleanupScopeB
data PreparedCleanupSpecificationDigestA
data PreparedCleanupSpecificationDigestB
data PreparedCleanupPlanA
data PreparedCleanupPlanB
data PreparedCleanupConfigurationA
data PreparedCleanupConfigurationB
data PreparedCleanupProviderResourceA
data PreparedCleanupProviderResourceB
data PreparedCleanupProviderFrameA
data PreparedCleanupProviderFrameB
data PreparedCleanupWallA
data PreparedCleanupWallB
data PreparedCleanupEpochA
data PreparedCleanupEpochB
data PreparedCleanupFenceA
data PreparedCleanupFenceB

type Prepared scope spec plan config providerResource providerFrame budget capability wall workloads partition reservation fence =
  PreparedColimaWallCall scope spec plan config providerResource providerFrame budget capability wall workloads partition reservation fence

type Live scope spec plan config providerResource providerFrame wall epoch fence =
  LiveColimaWall scope spec plan config providerResource providerFrame wall epoch fence

type Cleanup scope spec plan config providerResource providerFrame wall epoch fence =
  ColimaCleanupAuthority scope spec plan config providerResource providerFrame wall epoch fence

type PreparedCleanup scope spec plan config providerResource providerFrame wall epoch fence =
  PreparedColimaCleanupCall scope spec plan config providerResource providerFrame wall epoch fence

coercePreparedScope ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeB PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA
coercePreparedScope = coerce

coercePreparedSpecificationDigest ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeA PreparedSpecificationDigestB PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA
coercePreparedSpecificationDigest = coerce

coercePreparedPlan ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanB PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA
coercePreparedPlan = coerce

coercePreparedConfiguration ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationB PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA
coercePreparedConfiguration = coerce

coercePreparedProviderResource ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceB PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA
coercePreparedProviderResource = coerce

coercePreparedProviderFrame ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameB PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA
coercePreparedProviderFrame = coerce

coercePreparedBudget ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetB PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA
coercePreparedBudget = coerce

coercePreparedCapability ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityB PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA
coercePreparedCapability = coerce

coercePreparedWall ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallB PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA
coercePreparedWall = coerce

coercePreparedWorkloads ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsB PreparedPartitionA PreparedReservationA PreparedFenceA
coercePreparedWorkloads = coerce

coercePreparedPartition ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionB PreparedReservationA PreparedFenceA
coercePreparedPartition = coerce

coercePreparedReservation ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationB PreparedFenceA
coercePreparedReservation = coerce

coercePreparedFence ::
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceA ->
  Prepared PreparedScopeA PreparedSpecificationDigestA PreparedPlanA PreparedConfigurationA PreparedProviderResourceA PreparedProviderFrameA PreparedBudgetA PreparedCapabilityA PreparedWallA PreparedWorkloadsA PreparedPartitionA PreparedReservationA PreparedFenceB
coercePreparedFence = coerce

coerceLiveScope ::
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA ->
  Live LiveScopeB LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA
coerceLiveScope = coerce

coerceLiveSpecificationDigest ::
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA ->
  Live LiveScopeA LiveSpecificationDigestB LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA
coerceLiveSpecificationDigest = coerce

coerceLivePlan ::
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA ->
  Live LiveScopeA LiveSpecificationDigestA LivePlanB LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA
coerceLivePlan = coerce

coerceLiveConfiguration ::
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA ->
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationB LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA
coerceLiveConfiguration = coerce

coerceLiveProviderResource ::
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA ->
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceB LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA
coerceLiveProviderResource = coerce

coerceLiveProviderFrame ::
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA ->
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameB LiveWallA LiveEpochA LiveFenceA
coerceLiveProviderFrame = coerce

coerceLiveWall ::
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA ->
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallB LiveEpochA LiveFenceA
coerceLiveWall = coerce

coerceLiveEpoch ::
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA ->
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochB LiveFenceA
coerceLiveEpoch = coerce

coerceLiveFence ::
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceA ->
  Live LiveScopeA LiveSpecificationDigestA LivePlanA LiveConfigurationA LiveProviderResourceA LiveProviderFrameA LiveWallA LiveEpochA LiveFenceB
coerceLiveFence = coerce

coerceCleanupScope ::
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA ->
  Cleanup CleanupScopeB CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA
coerceCleanupScope = coerce

coerceCleanupSpecificationDigest ::
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA ->
  Cleanup CleanupScopeA CleanupSpecificationDigestB CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA
coerceCleanupSpecificationDigest = coerce

coerceCleanupPlan ::
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA ->
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanB CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA
coerceCleanupPlan = coerce

coerceCleanupConfiguration ::
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA ->
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationB CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA
coerceCleanupConfiguration = coerce

coerceCleanupProviderResource ::
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA ->
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceB CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA
coerceCleanupProviderResource = coerce

coerceCleanupProviderFrame ::
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA ->
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameB CleanupWallA CleanupEpochA CleanupFenceA
coerceCleanupProviderFrame = coerce

coerceCleanupWall ::
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA ->
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallB CleanupEpochA CleanupFenceA
coerceCleanupWall = coerce

coerceCleanupEpoch ::
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA ->
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochB CleanupFenceA
coerceCleanupEpoch = coerce

coerceCleanupFence ::
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceA ->
  Cleanup CleanupScopeA CleanupSpecificationDigestA CleanupPlanA CleanupConfigurationA CleanupProviderResourceA CleanupProviderFrameA CleanupWallA CleanupEpochA CleanupFenceB
coerceCleanupFence = coerce

coercePreparedCleanupScope ::
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA ->
  PreparedCleanup PreparedCleanupScopeB PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA
coercePreparedCleanupScope = coerce

coercePreparedCleanupSpecificationDigest ::
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA ->
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestB PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA
coercePreparedCleanupSpecificationDigest = coerce

coercePreparedCleanupPlan ::
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA ->
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanB PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA
coercePreparedCleanupPlan = coerce

coercePreparedCleanupConfiguration ::
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA ->
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationB PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA
coercePreparedCleanupConfiguration = coerce

coercePreparedCleanupProviderResource ::
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA ->
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceB PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA
coercePreparedCleanupProviderResource = coerce

coercePreparedCleanupProviderFrame ::
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA ->
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameB PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA
coercePreparedCleanupProviderFrame = coerce

coercePreparedCleanupWall ::
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA ->
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallB PreparedCleanupEpochA PreparedCleanupFenceA
coercePreparedCleanupWall = coerce

coercePreparedCleanupEpoch ::
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA ->
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochB PreparedCleanupFenceA
coercePreparedCleanupEpoch = coerce

coercePreparedCleanupFence ::
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceA ->
  PreparedCleanup PreparedCleanupScopeA PreparedCleanupSpecificationDigestA PreparedCleanupPlanA PreparedCleanupConfigurationA PreparedCleanupProviderResourceA PreparedCleanupProviderFrameA PreparedCleanupWallA PreparedCleanupEpochA PreparedCleanupFenceB
coercePreparedCleanupFence = coerce
