{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}

{- | The hostbootstrap-demo's own project-config shape and its in-process
decoder/renderer.

These types used to live in @hostbootstrap-core@'s @Config.Schema@. The core is
now generic over a project's config type (the 'ProjectCfg' class, coupled to the
core only through the embedded 'Context.BinaryContext'), so the **project** owns
its actual @<project>.dhall@ record. This module is the demo's instance: the
@ProjectConfig@ / @Resources@ / @DeployConfig@ / @TestConfig@ records, the
project-specific render/decode helpers, the child-projection logic, and — the one
place defaults live — the @InitArgs@ builders ('demoInit' / 'demoTestInit' /
'demoTestConfig') the demo's 'HostBootstrap.CLI.ProjectSpec' threads in.
-}
module HostBootstrapDemo.Config (
    ProjectConfig (..),
    DeployConfig (..),
    Resources (..),
    TestConfig (..),

    -- * Render / decode
    renderProjectConfig,
    decodeProjectConfigText,
    decodeProjectConfigFile,
    projectConfigSchemaText,
    renderProjectConfigSummary,
    renderTestConfig,
    decodeTestConfigText,
    decodeTestConfigFile,
    testConfigSchemaText,

    -- * Resource conversions
    envelopeOfResources,
    resourcesFromEnvelope,

    -- * Construction
    projectConfigForRole,
    projectConfigFromContext,
    deriveProjectConfigForKind,
    defaultTestConfig,

    -- * Defaults (the one place defaults live)
    demoDefaultResources,
    demoDefaultDeployConfig,
    demoDefaultDockerfile,
    demoDefaultMessage,

    -- * InitArgs builders (threaded into the demo's ProjectSpec)
    demoInit,
    demoTestInit,
    demoTestConfig,
)
where

import Data.Maybe (fromMaybe)
import Data.Text (Text)
import qualified Data.Text as T
import Dhall (FromDhall, ToDhall, auto, inputFile)
import qualified Dhall
import qualified Dhall.Core
import Dhall.Marshal.Encode (Encoder (declared, embed))
import GHC.Generics (Generic)
import HostBootstrap.Config.Class (InitArgs (..), ProjectCfg (..))
import HostBootstrap.Context (BinaryContext)
import qualified HostBootstrap.Context as Context
import qualified HostBootstrap.Dhall.Hoist as Hoist
import Numeric.Natural (Natural)

-- | The per-project resource budget.
data Resources = Resources
    { cpu :: Natural
    , memory :: Text
    , storage :: Text
    }
    deriving (Eq, Show, Generic, FromDhall, ToDhall)

{- | Project deployment knobs that are authored at the host level and projected
into narrower child configs when a boundary is crossed.
-}
newtype DeployConfig = DeployConfig
    { haReplicas :: Natural
    }
    deriving (Eq, Show, Generic, FromDhall, ToDhall)

{- | The per-project @test.dhall@ shape (development_plan_standards § Z): the
selectable suites (the case ids plus @all@) plus the **test-config resource
overrides** projected into the test stack's config. The file is generated by
@test init@ and read by @test run@ (which builds the run config from it).
-}
data TestConfig = TestConfig
    { testSuites :: [Text]
    , testResources :: Resources
    }
    deriving (Eq, Show, Generic, FromDhall, ToDhall)

{- | The supported project-local config shape.

Project identity is deliberately not a top-level field; it is derived by the
bootstrapper from the Cabal file. Runtime identity is part of the nested
context and is validated against the derived project/binary name before
normal command dispatch.
-}
data ProjectConfig = ProjectConfig
    { dockerfile :: Text
    , resources :: Resources
    , context :: BinaryContext
    , deploy :: DeployConfig
    , message :: Text
    }
    deriving (Eq, Show, Generic, FromDhall, ToDhall)

{- | The demo's 'ProjectCfg' instance: the core reaches the embedded context
through these two methods and otherwise never touches the demo's fields.
-}
instance ProjectCfg ProjectConfig where
    cfgContext = context
    cfgWithContext ctx cfg = cfg{context = ctx}

{- | Render a project-local config to Dhall source text, hoisting the repeated
vocabulary unions into top-level @let@ bindings.
-}
renderProjectConfig :: ProjectConfig -> Text
renderProjectConfig = Hoist.renderHoisted Context.vocabUnions

-- | Decode a project-local config from Dhall source text.
decodeProjectConfigText :: Text -> IO ProjectConfig
decodeProjectConfigText = Dhall.input auto

-- | Decode a project-local config from a @<project>.dhall@ file.
decodeProjectConfigFile :: FilePath -> IO ProjectConfig
decodeProjectConfigFile = inputFile auto

-- | The reflected Dhall type accepted by the project-local config decoder.
projectConfigSchemaText :: Text
projectConfigSchemaText = Dhall.Core.pretty (declared (Dhall.inject :: Encoder ProjectConfig))

-- | The reflected Dhall type the @test.dhall@ decoder accepts.
testConfigSchemaText :: Text
testConfigSchemaText = Dhall.Core.pretty (declared (Dhall.inject :: Encoder TestConfig))

-- | Render a @test.dhall@ to deterministic Dhall source via its @ToDhall@ embedding.
renderTestConfig :: TestConfig -> Text
renderTestConfig cfg = Dhall.Core.pretty (embed (Dhall.inject :: Encoder TestConfig) cfg)

-- | Decode a @test.dhall@.
decodeTestConfigFile :: FilePath -> IO TestConfig
decodeTestConfigFile = inputFile auto

-- | Decode a @test.dhall@ from Dhall source text.
decodeTestConfigText :: Text -> IO TestConfig
decodeTestConfigText = Dhall.input auto

{- | The default @test.dhall@: the project's selectable suites plus the resource
override (seeded from the project config's resources).
-}
defaultTestConfig :: [Text] -> Resources -> TestConfig
defaultTestConfig suites res = TestConfig{testSuites = suites, testResources = res}

-- | Convert user-facing resources into the runtime authority envelope.
envelopeOfResources :: Resources -> Context.ResourceEnvelope
envelopeOfResources Resources{cpu = resourceCpu, memory = resourceMemory, storage = resourceStorage} =
    Context.ResourceEnvelope
        { Context.cpu = resourceCpu
        , Context.memory = resourceMemory
        , Context.storage = resourceStorage
        }

{- | Convert a runtime authority envelope back into the project-level resource
shape used by generated child configs.
-}
resourcesFromEnvelope :: Context.ResourceEnvelope -> Resources
resourcesFromEnvelope envelope =
    Resources
        { cpu = Context.cpu envelope
        , memory = Context.memory envelope
        , storage = Context.storage envelope
        }

{- | Build a project-local config for a selected local role. The @message@ is
the config-driven worked example the webservice serves (Sprint 20.1).
-}
projectConfigForRole ::
    Text ->
    Text ->
    Text ->
    Text ->
    Resources ->
    DeployConfig ->
    Text ->
    Context.ContextKind ->
    ProjectConfig
projectConfigForRole projectName binaryName root cfgDockerfile cfgResources cfgDeploy cfgMessage kind =
    ProjectConfig
        { dockerfile = cfgDockerfile
        , resources = cfgResources
        , context =
            Context.contextForKind
                projectName
                binaryName
                root
                (envelopeOfResources cfgResources)
                kind
        , deploy = cfgDeploy
        , message = cfgMessage
        }

{- | Wrap an already-derived context in the project-local config shape. The
@message@ is forwarded from the parent so child frames carry the same served
message (Sprint 20.1).
-}
projectConfigFromContext :: Text -> DeployConfig -> Text -> Context.BinaryContext -> ProjectConfig
projectConfigFromContext cfgDockerfile cfgDeploy cfgMessage cfgContext' =
    ProjectConfig
        { dockerfile = cfgDockerfile
        , resources = resourcesFromEnvelope (Context.resourceEnvelope cfgContext')
        , context = cfgContext'
        , deploy = cfgDeploy
        , message = cfgMessage
        }

-- | Project a parent config into a narrower child config for a boundary crossing.
deriveProjectConfigForKind :: Context.ContextKind -> ProjectConfig -> Text -> Either String ProjectConfig
deriveProjectConfigForKind kind parent root
    | kind `notElem` Context.childContextKinds parentContext =
        Left $
            "project config: child context "
                <> show kind
                <> " is not allowed in "
                <> show (Context.contextKind parentContext)
    | otherwise =
        case kind of
            Context.HostOrchestrator ->
                Left "project config: host-orchestrator is not a child context"
            Context.VMOrchestrator ->
                projected (Context.deriveVMContext parentContext root)
            Context.VMProjectContainer ->
                projected (Context.deriveContainerContext parentContext root)
            Context.ImageBuildContainer ->
                Left "project config: image-build-container is not a child context"
            Context.ClusterService ->
                projected (Context.deriveServiceContext parentContext root)
            Context.Daemon ->
                projected (Context.deriveDaemonContext parentContext root)
            Context.OneShotJob ->
                projected (Context.deriveOneShotContext parentContext root)
            Context.TestHarness ->
                projected (Context.deriveTestHarnessContext parentContext root)
  where
    ProjectConfig
        { dockerfile = parentDockerfile
        , context = parentContext
        , deploy = parentDeploy
        , message = parentMessage
        } = parent
    projected = Right . projectConfigFromContext parentDockerfile parentDeploy parentMessage

-- | A short human-readable summary of a decoded project-local config.
renderProjectConfigSummary :: ProjectConfig -> String
renderProjectConfigSummary
    ProjectConfig
        { dockerfile = cfgDockerfile
        , resources = cfgResources
        , context = cfgContext'
        , deploy = cfgDeploy
        , message = cfgMessage
        } =
        T.unpack $
            T.unlines
                [ "project:      " <> Context.project cfgContext'
                , "binary:       " <> Context.binary cfgContext'
                , "dockerfile:   " <> cfgDockerfile
                , "context-kind: " <> T.pack (show (Context.contextKind cfgContext'))
                , "role:         " <> Context.roleName cfgContext'
                , "resources:    cpu="
                    <> T.pack (show cfgResources.cpu)
                    <> " memory="
                    <> cfgResources.memory
                    <> " storage="
                    <> cfgResources.storage
                , "ha-replicas:  " <> T.pack (show cfgDeploy.haReplicas)
                , "message:      " <> cfgMessage
                ]

-- ---------------------------------------------------------------------------
-- Defaults + InitArgs builders (the one place config defaults live).
-- ---------------------------------------------------------------------------

-- | The demo project name, derived from the Cabal file.
demoProjectName :: Text
demoProjectName = "hostbootstrap-demo"

{- | The demo's resource defaults (the full-lifecycle ceiling: cpu 6 / 10GiB /
80GiB). Core ships **no** resource defaults; this is the demo's.
-}
demoDefaultResources :: Resources
demoDefaultResources = Resources{cpu = 6, memory = "10GiB", storage = "80GiB"}

-- | The demo's deploy defaults (one HA replica). Core ships no deploy defaults.
demoDefaultDeployConfig :: DeployConfig
demoDefaultDeployConfig = DeployConfig{haReplicas = 1}

-- | The demo's default Dockerfile path. Core ships no Dockerfile default.
demoDefaultDockerfile :: Text
demoDefaultDockerfile = "docker/Dockerfile"

{- | The demo's default served @message@ (the config-driven worked example, Sprint
20.1): @project init@ seeds it, the webservice reads it from its mounted config and
serves it, and the SPA renders it in the @#message@ element. Core ships none.
-}
demoDefaultMessage :: Text
demoDefaultMessage = "Hello, world!"

{- | The demo's @init@ builder: interpret the parsed 'InitArgs' into a concrete
'ProjectConfig', supplying the demo's defaults for every omitted knob. This is
the **only** default-bearing function (core ships none). Reused by @project init@
/ @service init@ and by 'demoTestConfig' (so the harness generates its run config
through the same builder production uses).
-}
demoInit :: InitArgs -> ProjectConfig
demoInit = demoInitWithMessage demoDefaultMessage

{- | The message-parameterized 'demoInit': interpret the parsed 'InitArgs' with an
explicit served @message@ (the default-bearing 'demoInit' supplies
'demoDefaultMessage'; the harness's second variant supplies its own, Sprint 20.3).
-}
demoInitWithMessage :: Text -> InitArgs -> ProjectConfig
demoInitWithMessage cfgMessage args =
    let cfgResources =
            Resources
                { cpu = fromMaybe demoDefaultResources.cpu args.mCpu
                , memory = fromMaybe demoDefaultResources.memory args.memory
                , storage = fromMaybe demoDefaultResources.storage args.storage
                }
        cfgDeploy = DeployConfig{haReplicas = fromMaybe demoDefaultDeployConfig.haReplicas args.haReplicas}
        cfgDockerfile = fromMaybe demoDefaultDockerfile args.dockerfile
        root = fromMaybe "." args.sourceRoot
        baseCfg =
            projectConfigForRole
                demoProjectName
                demoProjectName
                (T.pack root)
                cfgDockerfile
                cfgResources
                cfgDeploy
                cfgMessage
                args.role
     in baseCfg{context = foldr Context.addRole baseCfg.context args.alsoRoles}

{- | The demo's @test init@ builder: a 'TestConfig' seeded from the demo's default
resources and the demo's selectable suites. Needs **no** pre-existing project
config (the case-id list is fixed in the project; the resources are the demo's
defaults).
-}
demoTestInit :: InitArgs -> TestConfig
demoTestInit _ = defaultTestConfig demoTestSuiteIds demoDefaultResources

{- | The demo's selectable test-suite ids (the case ids plus @all@). Kept in sync
with the demo's case matrix manually; a richer reflection lives in Commands.
-}
demoTestSuiteIds :: [Text]
demoTestSuiteIds = ["pristine-bootstrap", "web-build", "e2e-tabs", "all"]

{- | The demo's @test run@ config generator: build the run's labeled
'ProjectConfig' variants from the 'TestConfig' (host-orchestrator configs sized to
the test resources, with the demo's defaults), so the harness drives the **same**
chain interpreter production uses against configs it generated, once per variant.
Reuses 'demoInitWithMessage' so production and test share one builder.

Returns TWO variants (Sprint 20.3) whose labels are their served @message@ — the
harness threads each label into the per-variant assertion env as the expected
message, and the polymorphic Playwright asserts the SPA renders it. The first
variant uses the demo default; the second a distinct message — so a passing run
proves the served message really is config-driven (changing the config changes the
served value), not hard-coded.
-}
demoTestConfig :: TestConfig -> IO [(Text, ProjectConfig)]
demoTestConfig tc =
    pure
        [ ("Hello, world!", configFor "Hello, world!")
        , ("Hello, Universe!", configFor "Hello, Universe!")
        ]
  where
    configFor msg =
        demoInitWithMessage
            msg
            InitArgs
                { role = Context.HostOrchestrator
                , alsoRoles = []
                , output = Nothing
                , sourceRoot = Just "."
                , mCpu = Just tc.testResources.cpu
                , memory = Just tc.testResources.memory
                , storage = Just tc.testResources.storage
                , dockerfile = Just demoDefaultDockerfile
                , haReplicas = Just demoDefaultDeployConfig.haReplicas
                , force = True
                , ifMissing = False
                }
